# Sahasrabuddhe verification

In [1]:
import chainladder as cl

genins = cl.load_sample("genins")
genins

           12         24         36         48         60         72         84         96         108        120
2001  357848.0  1124788.0  1735330.0  2218270.0  2745596.0  3319994.0  3466336.0  3606286.0  3833515.0  3901463.0
2002  352118.0  1236139.0  2170033.0  3353322.0  3799067.0  4120063.0  4647867.0  4914039.0  5339085.0        NaN
2003  290507.0  1292306.0  2218525.0  3235179.0  3985995.0  4132918.0  4628910.0  4909315.0        NaN        NaN
2004  310608.0  1418858.0  2195047.0  3757447.0  4029929.0  4381982.0  4588268.0        NaN        NaN        NaN
2005  443160.0  1136350.0  2128333.0  2897821.0  3402672.0  3873311.0        NaN        NaN        NaN        NaN
2006  396132.0  1333217.0  2180715.0  2985752.0  3691712.0        NaN        NaN        NaN        NaN        NaN
2007  440832.0  1288463.0  2419861.0  3483130.0        NaN        NaN        NaN        NaN        NaN        NaN
2008  359480.0  1421128.0  2864498.0        NaN        NaN        NaN        NaN        NaN        NaN        NaN
2009  376686.0  1363294.0        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN
2010  344014.0        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN

In [2]:
# Limits
triangle_limit = 1000000
basic_limit = 500000
policy_limit = 2000000

In [3]:
# B1: Exposure Period Trend Index [ 2% EP Trend; 5% between EP 6 and 7 ]
#
# "a one-time increase TO 5%" replaces the 2% for the single EP 6 -> EP 7 step
# rather than stacking on top of it, so the assumption is three segments of
# annual trend rather than one rate plus a bump.
#
# Two arguments do the work that used to need a carrier triangle of 1s:
#
#   full_triangle=True  returns the factor surface over the whole 10 x 10
#                       origin x development rectangle.  The exhibits are full
#                       rectangles, but genins is a triangle, so without this
#                       everything below the latest diagonal comes back NaN.
#
#   base_period=2001    anchors the factors on EP 1 instead of the default
#                       (the latest origin).  The paper's index runs EP 1 =
#                       1.000 and rises; the default would put 1.000 at EP 10.
#
# `trend_` is a multiplier TO the base period's cost level -- it answers "what
# do I multiply EP i by to state it at EP 1's level".  A cost level INDEX runs
# the other way, so the index is its reciprocal.
B1 = (
    1
    / cl
    .Trend(
        trends=[0.02, 0.05, 0.02],
        dates=[
            ("2006-12-31", None),  # 2% from the earliest origin up to EP 6
            ("2007-12-31", "2006-12-31"),  # 5% for the single EP 6 -> EP 7 step
            ("2010-12-31", "2007-12-31"),  # 2% from EP 7 through the latest origin
        ],
        axis="origin",
        base_period=2001,
        full_triangle=True,
    )
    .fit(genins)
    .trend_
)

B1

           12        24        36        48        60        72        84        96        108       120
2001  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
2002  1.020000  1.020000  1.020000  1.020000  1.020000  1.020000  1.020000  1.020000  1.020000  1.020000
2003  1.040400  1.040400  1.040400  1.040400  1.040400  1.040400  1.040400  1.040400  1.040400  1.040400
2004  1.061208  1.061208  1.061208  1.061208  1.061208  1.061208  1.061208  1.061208  1.061208  1.061208
2005  1.082432  1.082432  1.082432  1.082432  1.082432  1.082432  1.082432  1.082432  1.082432  1.082432
2006  1.104081  1.104081  1.104081  1.104081  1.104081  1.104081  1.104081  1.104081  1.104081  1.104081
2007  1.159285  1.159285  1.159285  1.159285  1.159285  1.159285  1.159285  1.159285  1.159285  1.159285
2008  1.182471  1.182471  1.182471  1.182471  1.182471  1.182471  1.182471  1.182471  1.182471  1.182471
2009  1.206120  1.206120  1.206120  1.206120  1.206120  1.206120  1.206120  1.206120  1.206120  1.206120
2010  1.230242  1.230242  1.230242  1.230242  1.230242  1.230242  1.230242  1.230242  1.230242  1.230242

In [4]:
cl.Trend(
    trends=[0.02, 0.05, 0.02],
    dates=[
        ("2006-12-31", None),  # 2% from the earliest origin up to EP 6
        ("2007-12-31", "2006-12-31"),  # 5% for the single EP 6 -> EP 7 step
        ("2010-12-31", "2007-12-31"),  # 2% from EP 7 through the latest origin
    ],
    axis="origin",
    base_period=2001,
    full_triangle=True,
).fit(genins).trend_

           12        24        36        48        60        72        84        96        108       120
2001  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
2002  0.980392  0.980392  0.980392  0.980392  0.980392  0.980392  0.980392  0.980392  0.980392  0.980392
2003  0.961169  0.961169  0.961169  0.961169  0.961169  0.961169  0.961169  0.961169  0.961169  0.961169
2004  0.942322  0.942322  0.942322  0.942322  0.942322  0.942322  0.942322  0.942322  0.942322  0.942322
2005  0.923845  0.923845  0.923845  0.923845  0.923845  0.923845  0.923845  0.923845  0.923845  0.923845
2006  0.905731  0.905731  0.905731  0.905731  0.905731  0.905731  0.905731  0.905731  0.905731  0.905731
2007  0.862601  0.862601  0.862601  0.862601  0.862601  0.862601  0.862601  0.862601  0.862601  0.862601
2008  0.845687  0.845687  0.845687  0.845687  0.845687  0.845687  0.845687  0.845687  0.845687  0.845687
2009  0.829105  0.829105  0.829105  0.829105  0.829105  0.829105  0.829105  0.829105  0.829105  0.829105
2010  0.812848  0.812848  0.812848  0.812848  0.812848  0.812848  0.812848  0.812848  0.812848  0.812848

In [5]:
# B2: Calendar Period Trend Index [ 1% Calendar Period Trend; -5% between CP 2 and 3 ]
#
# Same shape of assumption as B1, but on the valuation axis.  The index
# therefore depends only on calendar period k = i + j - 1, which is why the
# result is constant down each diagonal rather than across each row.
#
# CP 1 is 2001, so the one-time -5% sits on the 2002 -> 2003 valuation step,
# and base_period is the 2001 valuation rather than the 2001 origin.  On the
# valuation axis a base period names a month, so "2001-12" rather than 2001 --
# a bare year would resolve to January 2001, which is not a valuation date here.
#
# The last segment leaves `start` as None.  Under full_triangle=True that
# defaults to the rectangle's own last valuation (2020) rather than genins'
# valuation date (2010), which is what lets the factors keep accruing across
# the whole exhibit instead of flattening at the latest diagonal.
B2 = (
    1
    / cl
    .Trend(
        trends=[0.01, -0.05, 0.01],
        dates=[
            ("2002-12-31", None),  # 1% from the earliest valuation up to CP 2
            ("2003-12-31", "2002-12-31"),  # -5% for the single CP 2 -> CP 3 step
            (None, "2003-12-31"),  # 1% from CP 3 out to the last valuation
        ],
        axis="valuation",
        base_period="2001-12",
        full_triangle=True,
    )
    .fit(genins)
    .trend_
)

B2

           12        24        36        48        60        72        84        96        108       120
2001  1.000000  1.010000  0.959500  0.969095  0.978786  0.988574  0.998460  1.008444  1.018529  1.028714
2002  1.010000  0.959500  0.969095  0.978786  0.988574  0.998460  1.008444  1.018529  1.028714  1.039001
2003  0.959500  0.969095  0.978786  0.988574  0.998460  1.008444  1.018529  1.028714  1.039001  1.049391
2004  0.969095  0.978786  0.988574  0.998460  1.008444  1.018529  1.028714  1.039001  1.049391  1.059885
2005  0.978786  0.988574  0.998460  1.008444  1.018529  1.028714  1.039001  1.049391  1.059885  1.070484
2006  0.988574  0.998460  1.008444  1.018529  1.028714  1.039001  1.049391  1.059885  1.070484  1.081189
2007  0.998460  1.008444  1.018529  1.028714  1.039001  1.049391  1.059885  1.070484  1.081189  1.092001
2008  1.008444  1.018529  1.028714  1.039001  1.049391  1.059885  1.070484  1.081189  1.092001  1.102921
2009  1.018529  1.028714  1.039001  1.049391  1.059885  1.070484  1.081189  1.092001  1.102921  1.113950
2010  1.028714  1.039001  1.049391  1.059885  1.070484  1.081189  1.092001  1.102921  1.113950  1.125089

In [6]:
# B3: Combined Trend Index [ B1 * B2 ]
#
# Exposure period and calendar period trend compound, so the combined cost
# level index is the elementwise product.  This is the T(i, j) that equation
# 3.1 uses to shift the claim size model parameters, and it is the first index
# that varies in BOTH directions -- B1 is constant across j, B2 is constant
# down each diagonal, and the product is constant in neither.
#
# Both operands are full rectangles anchored on the same cell, so the product
# needs no further rebasing: cell (1, 1) is simultaneously EP 1 and CP 1.
B3 = B1 * B2

B3

           12        24        36        48        60        72        84        96        108       120
2001  1.000000  1.010000  0.959500  0.969095  0.978786  0.988574  0.998460  1.008444  1.018529  1.028714
2002  1.030200  0.978690  0.988477  0.998362  1.008345  1.018429  1.028613  1.038899  1.049288  1.059781
2003  0.998264  1.008246  1.018329  1.028512  1.038797  1.049185  1.059677  1.070274  1.080977  1.091786
2004  1.028411  1.038695  1.049082  1.059573  1.070169  1.080871  1.091679  1.102596  1.113622  1.124758
2005  1.059469  1.070064  1.080765  1.091572  1.102488  1.113513  1.124648  1.135895  1.147254  1.158726
2006  1.091465  1.102380  1.113404  1.124538  1.135783  1.147141  1.158612  1.170199  1.181901  1.193720
2007  1.157499  1.169074  1.180765  1.192572  1.204498  1.216543  1.228709  1.240996  1.253406  1.265940
2008  1.192455  1.204380  1.216424  1.228588  1.240874  1.253283  1.265816  1.278474  1.291258  1.304171
2009  1.228468  1.240752  1.253160  1.265691  1.278348  1.291132  1.304043  1.317084  1.330254  1.343557
2010  1.265567  1.278223  1.291005  1.303915  1.316954  1.330124  1.343425  1.356860  1.370428  1.384132

In [7]:
# Check the reconstruction against the exhibits as printed in the paper.
#
# The published grids carry three decimals, so agreement is asserted to half of
# the last printed digit.  Two consequences of that rounding are worth naming:
#
#   * B2 cell (1, 3) is exactly 1.01 * 0.95 = 0.9595.  The paper rounds half up
#     and prints 0.960; numpy rounds the float (which sits a hair below .9595)
#     down and shows 0.959.  Same number, different tie-break.
#
#   * B3 as printed is NOT the product of B1 and B2 as printed -- the paper
#     multiplied unrounded values, so the two disagree by up to 0.0013.  B3 is
#     therefore checked against its own published grid, not against B1 * B2.
import numpy as np

B1_published = np.tile(
    np.array([1.000, 1.020, 1.040, 1.061, 1.082, 1.104, 1.159, 1.182, 1.206, 1.230])[
        :, None
    ],
    (1, 10),
)

# B2 is constant along diagonals, so 19 calendar-period values determine it:
# exhibit row 1 gives k = 1..10, exhibit column 10 gives k = 10..19.
_cp = np.array([
    1.000,
    1.010,
    0.960,
    0.969,
    0.979,
    0.989,
    0.998,
    1.008,
    1.019,
    1.029,
    1.039,
    1.049,
    1.060,
    1.070,
    1.081,
    1.092,
    1.103,
    1.114,
    1.125,
])
_i, _j = np.indices((10, 10))
B2_published = _cp[_i + _j]

B3_published = np.array([
    [1.000, 1.010, 0.960, 0.969, 0.979, 0.989, 0.998, 1.008, 1.019, 1.029],
    [1.030, 0.979, 0.988, 0.998, 1.008, 1.018, 1.029, 1.039, 1.049, 1.060],
    [0.998, 1.008, 1.018, 1.029, 1.039, 1.049, 1.060, 1.070, 1.081, 1.092],
    [1.028, 1.039, 1.049, 1.060, 1.070, 1.081, 1.092, 1.103, 1.114, 1.125],
    [1.059, 1.070, 1.081, 1.092, 1.102, 1.114, 1.125, 1.136, 1.147, 1.159],
    [1.091, 1.102, 1.113, 1.125, 1.136, 1.147, 1.159, 1.170, 1.182, 1.194],
    [1.157, 1.169, 1.181, 1.193, 1.204, 1.217, 1.229, 1.241, 1.253, 1.266],
    [1.192, 1.204, 1.216, 1.229, 1.241, 1.253, 1.266, 1.278, 1.291, 1.304],
    [1.228, 1.241, 1.253, 1.266, 1.278, 1.291, 1.304, 1.317, 1.330, 1.344],
    [1.266, 1.278, 1.291, 1.304, 1.317, 1.330, 1.343, 1.357, 1.370, 1.384],
])

for name, computed, published in [
    ("B1", B1, B1_published),
    ("B2", B2, B2_published),
    ("B3", B3, B3_published),
]:
    deviation = np.abs(computed.values[0, 0] - published).max()
    assert deviation <= 0.0006, f"{name} deviates from the paper by {deviation:.6f}"
    print(f"{name}: matches the published exhibit (max deviation {deviation:.6f})")

B1: matches the published exhibit (max deviation 0.000471)
B2: matches the published exhibit (max deviation 0.000500)
B3: matches the published exhibit (max deviation 0.000500)

In [8]:
# Applying a trend to the values is just multiplication -- multiplying by a
# factor triangle and calling .trend() on the data give identical answers.
# Materializing the factors is only worth it when you want to inspect or reuse
# them, as here.
#
# B3 is a cost level INDEX (cell (1, 1) = 1.000), so it is not itself the thing
# you multiply by.  To restate every cell to exposure period n's cost level --
# the T(n, j) / T(i, j) ratio that equation 3.2 needs -- divide exposure period
# n's row by the whole index.  Taking a row rather than a single cell matters
# here and not for B1: B3 varies by development interval as well as by origin.
to_current = B3.iloc[0, 0, -1:, :] / B3

# The factors cover the full rectangle, but genins does not, so the product
# masks back to genins' own valuation date.  That is correct -- there is no
# data out there to restate.
genins * to_current

                12            24            36            48            60            72            84            96            108           120
2001  452880.752000  1.423495e+06  2.334883e+06  2.984678e+06  3.694194e+06  4.467045e+06  4.663948e+06  4.852250e+06  5.157987e+06  5.249410e+06
2002  432565.570737  1.614466e+06  2.834183e+06  4.379623e+06  4.961791e+06  5.381029e+06  6.070370e+06  6.418006e+06  6.973139e+06           NaN
2003  368295.614625  1.638345e+06  2.812576e+06  4.101458e+06  5.053319e+06  5.239583e+06  5.868386e+06  6.223875e+06           NaN           NaN
2004  382235.516036  1.746053e+06  2.701234e+06  4.623930e+06  4.959248e+06  5.392486e+06  5.646342e+06           NaN           NaN           NaN
2005  529367.663372  1.357404e+06  2.542356e+06  3.461532e+06  4.064592e+06  4.626784e+06           NaN           NaN           NaN           NaN
2006  459319.873047  1.545881e+06  2.528566e+06  3.462016e+06  4.280585e+06           NaN           NaN           NaN           NaN           NaN
2007  481989.690556  1.408759e+06  2.645788e+06  3.808328e+06           NaN           NaN           NaN           NaN           NaN           NaN
2008  381520.452139  1.508260e+06  3.040126e+06           NaN           NaN           NaN           NaN           NaN           NaN           NaN
2009  388061.917200  1.404465e+06           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN
2010  344014.000000           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN

In [9]:
# C1: Claims Size Model Parameters at Exposure Year 10 Cost Level
#     [ via claim size modeling ]
#
# These are an INPUT, not something derived -- section 2.2 assumes the actuary
# has already fitted a claim size model, and section 1.2 puts that fitting
# outside the paper's scope.  Example 1 uses an exponential purely for ease of
# presentation, which is the model cl.LEV implements.
#
# cl.LEV takes the result of that analysis as `means`, either as a mapping of
# development age to mean claim size or as a Triangle.  Given no `trend`, the
# mapping is laid onto the base exposure period and handed back unrestated --
# which is C1, anchored on the 2010 row because C1 is stated at exposure year
# 10's cost level.
theta_10 = {
    12: 28138,
    24: 84242,
    36: 133998,
    48: 182460,
    60: 204649,
    72: 228245,
    84: 252830,
    96: 265063,
    108: 275707,
    120: 280000,
}

C1 = cl.LEV(means=theta_10).fit(genins).means_
C1

          12       24        36        48        60        72        84        96        108       120
2010  28138.0  84242.0  133998.0  182460.0  204649.0  228245.0  252830.0  265063.0  275707.0  280000.0

In [10]:
# C2: Claims Size Model Parameters [ C1 * B3(i,j) / B3(10,j) ]
#
# Equation 3.1.  C1 holds one row of parameters, all at exposure year 10's cost
# level.  Every other (i, j) cell sits at a different cost level, and B3 is
# exactly the index that says by how much -- so restating C1 onto the whole
# grid is C1 scaled by the ratio of each cell's index to row 10's.
#
# This is where this notebook differs from layers.ipynb.  There the restatement
# was written out as arithmetic on C1:
#
#     C2 = C1 * B3 / B3.iloc[0, 0, -1:, :]
#
# cl.LEV now owns it.  Passing `trend` makes `fit` do the scaling internally,
# so C2 comes back from a single call, and the row to divide by is named by
# `base_period` rather than by an .iloc into the index.  It defaults to the
# latest origin -- the same row the mapping was laid on -- so C1 and C2 agree
# on their base by construction instead of by the caller keeping two positional
# slices in step.
#
# This works because the exponential is a scale family: inflating claim sizes
# by a factor inflates the mean by the same factor, so adjusting the parameter
# for cost level is plain multiplication.  Section 2.2 requires exactly this
# ("that claims size model parameters can be adjusted for the impact of
# inflation"), and it is what limits the method to models of that shape.
#
# Row 10 reproduces C1 by construction: B3(10,j) / B3(10,j) is 1.
lev = cl.LEV(means=theta_10, trend=B3).fit(genins)

C2 = lev.means_
C2

               12            24             36             48             60             72             84             96             108            120
2001  22233.506237  66564.611286   99589.896059  135607.788436  152099.080870  169636.082821  187908.128632  196999.929991  204910.755926  208101.396263
2002  22904.958125  64501.108337  102597.510919  139703.143647  156692.473113  174759.092522  193582.954117  202949.327877  211099.060755  214386.058430
2003  22194.904423  66449.041808  105695.955749  143922.178585  161424.585801  180036.817117  199429.159331  209078.397579  217474.252390  220860.517394
2004  22865.190537  68455.802871  108887.973613  148268.628378  166299.608292  185473.928994  205451.919943  215392.565186  224041.974812  227530.505020
2005  23555.719291  70523.168118  112176.390416  152746.340955  171321.856462  191075.241649  211656.567925  221897.420654  230808.042452  234401.926271
2006  24267.102013  72652.967795  115564.117407  157359.280452  176495.776528  196845.713947  218048.596277  228598.722758  237778.445334  241480.864444
2007  25735.261685  77048.472346  122555.746510  166879.516919  187173.771007  208754.879641  231240.536352  242428.945485  252164.041276  256090.456743
2008  26512.466588  79375.336211  126256.930054  171919.278330  192826.418892  215059.277006  238224.000549  249750.299639  259779.395323  263824.388537
2009  27313.143079  81772.471365  130069.889342  177111.240536  198649.776742  221554.067171  245418.365366  257292.758688  267624.733062  271791.885071
2010  28138.000000  84242.000000  133998.000000  182460.000000  204649.000000  228245.000000  252830.000000  265063.000000  275707.000000  280000.000000

In [11]:
# C3: Unlimited Means
#
# For an exponential model the mean IS the parameter, so C3 restates C2 without
# changing it.  The paper prints it as its own exhibit because the general
# method needs M(Phi) -- the unlimited first moment -- as a distinct quantity
# from the parameters: for a lognormal or Pareto the two would differ, in
# dimension (Phi is a vector) and in existence (a Pareto with alpha <= 1 has
# no finite mean while its parameters are perfectly well defined).
#
# The limit is a property of the quantity being asked for, so it is named at
# construction: each exhibit in the C series is its own cl.LEV, and `lev_`
# carries the answer.  np.inf is the default, so C3 is also `lev.lev_` off the
# C2 instance above -- spelled out in full here to keep the series uniform.
C3 = cl.LEV(means=theta_10, trend=B3, limit=np.inf).fit(genins).lev_
C3

               12            24             36             48             60             72             84             96             108            120
2001  22233.506237  66564.611286   99589.896059  135607.788436  152099.080870  169636.082821  187908.128632  196999.929991  204910.755926  208101.396263
2002  22904.958125  64501.108337  102597.510919  139703.143647  156692.473113  174759.092522  193582.954117  202949.327877  211099.060755  214386.058430
2003  22194.904423  66449.041808  105695.955749  143922.178585  161424.585801  180036.817117  199429.159331  209078.397579  217474.252390  220860.517394
2004  22865.190537  68455.802871  108887.973613  148268.628378  166299.608292  185473.928994  205451.919943  215392.565186  224041.974812  227530.505020
2005  23555.719291  70523.168118  112176.390416  152746.340955  171321.856462  191075.241649  211656.567925  221897.420654  230808.042452  234401.926271
2006  24267.102013  72652.967795  115564.117407  157359.280452  176495.776528  196845.713947  218048.596277  228598.722758  237778.445334  241480.864444
2007  25735.261685  77048.472346  122555.746510  166879.516919  187173.771007  208754.879641  231240.536352  242428.945485  252164.041276  256090.456743
2008  26512.466588  79375.336211  126256.930054  171919.278330  192826.418892  215059.277006  238224.000549  249750.299639  259779.395323  263824.388537
2009  27313.143079  81772.471365  130069.889342  177111.240536  198649.776742  221554.067171  245418.365366  257292.758688  267624.733062  271791.885071
2010  28138.000000  84242.000000  133998.000000  182460.000000  204649.000000  228245.000000  252830.000000  265063.000000  275707.000000  280000.000000

In [12]:
# C4: Limited Expected Values at Policy Limits
#
# LEV(d) = theta * (1 - exp(-d / theta)), capping each claim at the policy
# limit.  At 2,000,000 the cap bites only slightly -- compare against C3 and
# the early development ages are unchanged to the printed precision, because a
# mean of ~22,000 puts almost no probability above two million.
C4 = cl.LEV(means=theta_10, trend=B3, limit=policy_limit).fit(genins).lev_
C4

               12            24             36             48             60             72             84             96             108            120
2001  22233.506237  66564.611286   99589.895869  135607.735087  152098.784764  169634.796912  187903.646005  196992.249598  204898.933678  208087.451819
2002  22904.958125  64501.108337  102597.510569  139703.058960  156692.024598  174757.220840  193576.645142  202938.672816  211082.847036  214367.017919
2003  22194.904423  66449.041808  105695.955109  143922.045846  161423.914067  180034.120285  199420.360749  209063.744144  217452.201681  220834.732274
2004  22865.190537  68455.802871  108887.972465  148268.422866  166298.613220  185470.081265  205439.757781  215372.582904  224012.228949  227495.865007
2005  23555.719291  70523.168118  112176.388389  152746.026549  171320.398025  191069.804028  211639.900595  221870.394725  230768.231886  234355.751228
2006  24267.102013  72652.967795  115564.113885  157358.804996  176493.660932  196838.100363  218025.945232  228562.460837  237725.571780  241419.776425
2007  25735.261685  77048.472346  122555.736486  166878.475762  187169.488516  208740.464175  231199.999514  242365.598711  252073.438021  255986.544622
2008  26512.466588  79375.336210  126256.913393  171917.754216  192820.384211  215039.610688  238170.187985  249667.185195  259661.623615  263689.797789
2009  27313.143079  81772.471363  130069.862032  177109.032297  198641.350688  221527.457359  245347.458286  257184.478360  267472.685986  271618.724296
2010  28138.000000  84241.999996  133997.955844  182456.832383  204637.339337  228209.281780  252737.239682  264922.901351  275511.996738  279778.662710

In [30]:
cl.LEV(means=theta_10, trend=B3, limit=policy_limit).fit(genins).means_

               12            24             36             48             60             72             84             96             108            120
2001  22233.506237  66564.611286   99589.896059  135607.788436  152099.080870  169636.082821  187908.128632  196999.929991  204910.755926  208101.396263
2002  22904.958125  64501.108337  102597.510919  139703.143647  156692.473113  174759.092522  193582.954117  202949.327877  211099.060755  214386.058430
2003  22194.904423  66449.041808  105695.955749  143922.178585  161424.585801  180036.817117  199429.159331  209078.397579  217474.252390  220860.517394
2004  22865.190537  68455.802871  108887.973613  148268.628378  166299.608292  185473.928994  205451.919943  215392.565186  224041.974812  227530.505020
2005  23555.719291  70523.168118  112176.390416  152746.340955  171321.856462  191075.241649  211656.567925  221897.420654  230808.042452  234401.926271
2006  24267.102013  72652.967795  115564.117407  157359.280452  176495.776528  196845.713947  218048.596277  228598.722758  237778.445334  241480.864444
2007  25735.261685  77048.472346  122555.746510  166879.516919  187173.771007  208754.879641  231240.536352  242428.945485  252164.041276  256090.456743
2008  26512.466588  79375.336211  126256.930054  171919.278330  192826.418892  215059.277006  238224.000549  249750.299639  259779.395323  263824.388537
2009  27313.143079  81772.471365  130069.889342  177111.240536  198649.776742  221554.067171  245418.365366  257292.758688  267624.733062  271791.885071
2010  28138.000000  84242.000000  133998.000000  182460.000000  204649.000000  228245.000000  252830.000000  265063.000000  275707.000000  280000.000000

In [13]:
# C5: Limited Expected Values at Limits of Data Triangle
#
# The same calculation at the limit the observed data is actually capped at.
# This is the denominator side of the limit adjustment: genins is reported at
# the triangle limit, so its development pattern is a triangle-limit pattern,
# and C5 is what that implies about expected claim size.
C5 = cl.LEV(means=theta_10, trend=B3, limit=triangle_limit).fit(genins).lev_
C5

               12            24             36             48             60             72             84             96             108            120
2001  22233.506237  66564.591387   99585.557090  135522.732052  151886.860388  169169.031808  186990.347550  195769.874310  203354.315794  206397.912107
2002  22904.958125  64501.096412  102591.511014  139594.373165  156427.371575  174187.171582  192477.825150  201478.805034  209249.006431  212365.657475
2003  22194.904423  66449.022456  105687.730390  143783.961079  161095.292075  179340.017977  198104.510732  207328.049979  215284.398171  218474.115311
2004  22865.190537  68455.771879  108876.791402  148094.068839  165892.815867  184629.148968  203871.179767  213317.948378  221460.440021  224723.075675
2005  23555.719291  70523.119123  112161.311522  152527.196253  170821.994293  190055.930691  209778.337380  219448.546606  227776.772307  231112.014555
2006  24267.102013  72652.891306  115543.943787  157085.752802  175884.717069  195621.499374  215826.203755  225719.585951  234232.716731  237640.084879
2007  25735.261685  77048.294468  122520.696736  166462.686191  186278.466572  207020.146568  228178.876659  238510.132950  247384.199958  250931.881109
2008  26512.466588  79375.068120  126211.064384  171407.394858  191747.694705  213002.720652  234643.575394  245194.220493  254248.151068  257865.502578
2009  27313.143079  81772.071792  130010.289510  176485.857532  197356.009455  219125.999578  241246.806956  252014.525621  261245.739557  264931.586730
2010  28138.000000  84241.410874  133921.078748  181699.760925  203104.220719  225389.740789  247987.212456  258969.153259  268374.622184  272127.615270

In [14]:
# C6: Limited Expected Values at Basic Limit
#
# Lowest of the three caps, so the largest gap from the unlimited mean -- by
# development age 120 the basic limit retains 233,050 of a 280,000 mean.
#
# With C4, C5 and C6 in hand the limit adjustment factors of equations 2.1/2.2
# follow directly, since each is a ratio of layer expectations.  A layer is
# itself just another cl.LEV: `attachment` and `limit` together give
# LEV(p) - LEV(d), which is equation 2.4.  E2 and E3 below are those layers.
C6 = cl.LEV(means=theta_10, trend=B3, limit=basic_limit).fit(genins).lev_
C6

               12            24             36             48             60             72             84             96             108            120
2001  22233.506233  66528.216355   98932.539645  132211.568763  146417.660245  160735.032079  174775.782093  181433.270650  187052.107487  189273.294094
2002  22904.958117  64473.375063  101812.924774  135804.993031  150247.365234  164761.673629  178956.466841  185673.864857  191336.856169  193573.903397
2003  22194.904419  66413.181622  104763.546392  139462.070459  154133.762572  168836.393047  183175.742563  189948.319916  195651.399482  197902.686513
2004  22865.190529  68409.742134  107784.520720  143181.222016  158074.681492  172956.554252  187430.651835  194253.571928  199992.605742  202256.490370
2005  23555.719277  70464.386576  110875.815194  146960.707765  162067.813299  177119.415350  191718.167009  198586.504009  204357.304689  206632.128946
2006  24267.101986  72578.421660  114037.242657  150798.631540  166110.719299  181322.138597  196035.201040  202943.957182  208742.298296  211026.394008
2007  25735.261591  76931.402740  120483.175345  158539.222529  174228.597875  189725.061095  204632.645993  211606.330567  217446.551397  219744.040271
2008  26512.466417  79229.460195  123850.509734  162538.306252  178403.987684  194028.786698  209018.809159  216017.791109  221872.888125  224174.679275
2009  27313.142773  81591.711627  127285.622208  166586.870738  182618.351890  198360.355726  213421.849212  220441.013183  226306.741413  228611.178520
2010  28137.999460  84019.223907  130787.502536  170682.342270  186868.743113  202716.611125  217838.544259  224872.786033  230744.928311  233050.370349

In [15]:
# cl.LEV is a transformer now, which is what lets the claim size model travel
# with the data rather than beside it.
#
# `transform` follows the library convention -- it copies the triangle it is
# given and attaches the fitted quantities, leaving the values alone:
lev_transformed = lev.transform(genins)

assert (lev_transformed == genins).all(), "transform leaves the values untouched"
assert np.allclose(
    np.nan_to_num(lev_transformed.means_.values),
    np.nan_to_num(C2.values),
), "the restated parameters ride along on the triangle"
assert np.allclose(
    np.nan_to_num(lev_transformed.lev_.values),
    np.nan_to_num(C3.values),
), "so does the layer expectation, here the unlimited mean"

print("transform attaches the fitted quantities and leaves the data alone")
print(f"  values unchanged : {(lev_transformed == genins).all()}")
print(f"  carries means_   : {hasattr(lev_transformed, 'means_')}")
print(f"  carries lev_     : {hasattr(lev_transformed, 'lev_')}")

# Which also means it composes.  Nothing downstream here consumes those off a
# triangle -- cl.Sahasrabuddhe builds its own cl.LEV from the same arguments --
# but a step that did would find them where the library puts every other
# fitted quantity.
cl.Pipeline([("lev", cl.LEV(means=theta_10, trend=B3))]).fit_transform(genins)

transform attaches the fitted quantities and leaves the data alone
  values unchanged : True
  carries means_   : True
  carries lev_     : True

           12         24         36         48         60         72         84         96         108        120
2001  357848.0  1124788.0  1735330.0  2218270.0  2745596.0  3319994.0  3466336.0  3606286.0  3833515.0  3901463.0
2002  352118.0  1236139.0  2170033.0  3353322.0  3799067.0  4120063.0  4647867.0  4914039.0  5339085.0        NaN
2003  290507.0  1292306.0  2218525.0  3235179.0  3985995.0  4132918.0  4628910.0  4909315.0        NaN        NaN
2004  310608.0  1418858.0  2195047.0  3757447.0  4029929.0  4381982.0  4588268.0        NaN        NaN        NaN
2005  443160.0  1136350.0  2128333.0  2897821.0  3402672.0  3873311.0        NaN        NaN        NaN        NaN
2006  396132.0  1333217.0  2180715.0  2985752.0  3691712.0        NaN        NaN        NaN        NaN        NaN
2007  440832.0  1288463.0  2419861.0  3483130.0        NaN        NaN        NaN        NaN        NaN        NaN
2008  359480.0  1421128.0  2864498.0        NaN        NaN        NaN        NaN        NaN        NaN        NaN
2009  376686.0  1363294.0        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN
2010  344014.0        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN

In [16]:
# Check the C series against the exhibits as printed in the paper.
#
# The published grids are rounded to whole currency units, so agreement is
# asserted to within 1.  C3 is checked against C2's grid: for an exponential
# the unlimited mean and the parameter are the same number, which is the
# invariant worth pinning rather than a separate table of figures.
C2_published = np.array([
    [22233, 66564, 99590, 135608, 152099, 169636, 187908, 197000, 204911, 208101],
    [22905, 64501, 102598, 139703, 156693, 174759, 193583, 202949, 211099, 214386],
    [22195, 66449, 105696, 143922, 161425, 180037, 199429, 209078, 217475, 220861],
    [22865, 68455, 108888, 148268, 166300, 185474, 205452, 215392, 224042, 227531],
    [23555, 70523, 112177, 152746, 171322, 191075, 211657, 221897, 230808, 234402],
    [24267, 72653, 115564, 157359, 176496, 196846, 218049, 228598, 237779, 241481],
    [25735, 77048, 122556, 166879, 187174, 208755, 231241, 242429, 252164, 256090],
    [26512, 79375, 126257, 171919, 192827, 215059, 238224, 249750, 259780, 263824],
    [27313, 81772, 130070, 177111, 198650, 221554, 245418, 257292, 267625, 271792],
    [28138, 84242, 133998, 182460, 204649, 228245, 252830, 265063, 275707, 280000],
])

C4_published = np.array([
    [22233, 66564, 99590, 135607, 152099, 169635, 187904, 196992, 204899, 208087],
    [22905, 64501, 102598, 139703, 156692, 174757, 193577, 202938, 211083, 214367],
    [22195, 66449, 105696, 143922, 161424, 180034, 199420, 209063, 217453, 220835],
    [22865, 68455, 108888, 148268, 166299, 185470, 205440, 215372, 224013, 227496],
    [23555, 70523, 112177, 152746, 171321, 191070, 211640, 221870, 230769, 234356],
    [24267, 72653, 115564, 157358, 176494, 196838, 218026, 228562, 237726, 241420],
    [25735, 77048, 122556, 166878, 187170, 208740, 231200, 242365, 252074, 255987],
    [26512, 79375, 126257, 171917, 192821, 215039, 238170, 249667, 259662, 263690],
    [27313, 81772, 130070, 177109, 198642, 221527, 245348, 257184, 267473, 271619],
    [28138, 84242, 133998, 182456, 204638, 228209, 252737, 264922, 275512, 279779],
])

C5_published = np.array([
    [22233, 66564, 99586, 135522, 151887, 169169, 186990, 195770, 203355, 206398],
    [22905, 64501, 102592, 139594, 156428, 174187, 192478, 201479, 209249, 212366],
    [22195, 66449, 105688, 143784, 161096, 179340, 198105, 207328, 215285, 218474],
    [22865, 68455, 108877, 148094, 165893, 184629, 203871, 213318, 221461, 224723],
    [23555, 70523, 112161, 152527, 170822, 190056, 209778, 219448, 227777, 231112],
    [24267, 72652, 115544, 157085, 175885, 195621, 215826, 225719, 234233, 237640],
    [25735, 77048, 122521, 166462, 186279, 207020, 228179, 238510, 247385, 250932],
    [26512, 79375, 126211, 171407, 191748, 213003, 234644, 245194, 254248, 257866],
    [27313, 81772, 130010, 176486, 197356, 219126, 241247, 252014, 261246, 264932],
    [28138, 84241, 133921, 181699, 203105, 225390, 247987, 258969, 268375, 272128],
])

C6_published = np.array([
    [22233, 66528, 98933, 132211, 146418, 160735, 174776, 181433, 187052, 189273],
    [22905, 64473, 101813, 135805, 150248, 164762, 178957, 185674, 191337, 193574],
    [22195, 66413, 104764, 139462, 154134, 168836, 183176, 189948, 195652, 197903],
    [22865, 68409, 107785, 143181, 158075, 172956, 187431, 194253, 199993, 202256],
    [23555, 70464, 110876, 146960, 162068, 177119, 191718, 198586, 204358, 206632],
    [24267, 72578, 114037, 150798, 166111, 181322, 196035, 202944, 208743, 211026],
    [25735, 76931, 120483, 158539, 174229, 189725, 204633, 211606, 217447, 219744],
    [26512, 79229, 123851, 162538, 178404, 194029, 209019, 216018, 221873, 224175],
    [27313, 81591, 127286, 166587, 182619, 198360, 213422, 220441, 226307, 228611],
    [28138, 84019, 130788, 170682, 186869, 202716, 217839, 224873, 230745, 233050],
])

for name, computed, published in [
    ("C2", C2, C2_published),
    ("C3", C3, C2_published),
    ("C4", C4, C4_published),
    ("C5", C5, C5_published),
    ("C6", C6, C6_published),
]:
    deviation = np.abs(computed.values[0, 0] - published).max()
    assert deviation < 1.0, f"{name} deviates from the paper by {deviation:.2f}"
    print(f"{name}: matches the published exhibit (max deviation {deviation:.2f})")

C2: matches the published exhibit (max deviation 0.80)
C3: matches the published exhibit (max deviation 0.80)
C4: matches the published exhibit (max deviation 0.90)
C5: matches the published exhibit (max deviation 0.89)
C6: matches the published exhibit (max deviation 0.74)

In [17]:
# D: Calculation of Development Factors at Basic Limit
#
# Sections A to C worked the restatement by hand, exhibit by exhibit, to show
# where each number comes from and to check it against the paper.  This is the
# same calculation as it would actually be written.
#
# Everything above collapses into one call.  cl.Sahasrabuddhe takes the claim
# size analysis and the cost level index and restates the triangle onto a
# single basis; `triangle_` is that restated data, and ordinary cl.Development
# fits on it.  There is nothing left in the triangle for the factors to be
# contaminated by, so no bespoke development code is needed -- and a tail,
# weights, or exclusions would follow as ordinary steps without any of this
# changing.
#
# Three limits are named, and they play different parts:
#
#   data_limit    where the observed data is capped -- the denominator of
#                 equation 3.2, varying cell by cell with cost level.
#
#   basic_limit   the common basis, B.  The triangle is restated onto it.
#
#   target_layer  the layer wanted out, as (attachment, exhaustion).
#                 Restating a triangle IS the move onto the basis, so here it
#                 has to be (0, basic_limit); naming any other layer raises
#                 rather than quietly doing something else.
#                 Section E below is where it starts to differ, because there
#                 what gets fitted is a pattern rather than a triangle.
#
# No C1 through C6 are passed.  The limits are named instead and the limited
# expected values derived from them, so there is no way to pair a C5 and a C6
# that were built at different limits.
#
# No base_period either.  It defaults to the latest origin, which is where a
# mapping of means is laid, so the two agree by construction.
basis = cl.Sahasrabuddhe(
    means=theta_10,
    trend=B3,
    data_limit=triangle_limit,
    basic_limit=basic_limit,
    target_layer=(0, basic_limit),
).fit(genins)

# D1: the triangle restated to exposure year 10 cost levels and basic limit.
D1 = basis.triangle_

development = cl.Development(average="volume").fit(D1)

D1

                12            24            36            48            60            72            84            96            108           120
2001  452880.743316  1.419731e+06  2.279040e+06  2.793771e+06  3.377949e+06  3.978376e+06  4.038185e+06  4.142392e+06  4.349867e+06  4.405265e+06
2002  432565.562442  1.610196e+06  2.766439e+06  4.100114e+06  4.538380e+06  4.794872e+06  5.260266e+06  5.484615e+06  5.887563e+06           NaN
2003  368295.607562  1.634013e+06  2.745402e+06  3.840400e+06  4.623710e+06  4.671635e+06  5.090015e+06  5.324756e+06           NaN           NaN
2004  382235.508706  1.741436e+06  2.636785e+06  4.330557e+06  4.539484e+06  4.811269e+06  4.902614e+06           NaN           NaN           NaN
2005  529367.653220  1.353815e+06  2.481777e+06  3.242745e+06  3.722314e+06  4.131334e+06           NaN           NaN           NaN           NaN
2006  459319.864239  1.541795e+06  2.468414e+06  3.244184e+06  3.922260e+06           NaN           NaN           NaN           NaN           NaN
2007  481989.681313  1.405036e+06  2.583136e+06  3.571424e+06           NaN           NaN           NaN           NaN           NaN           NaN
2008  381520.444823  1.504277e+06  2.968365e+06           NaN           NaN           NaN           NaN           NaN           NaN           NaN
2009  388061.909758  1.400758e+06           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN
2010  344013.993403           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN

In [18]:
# D2: Exposure Year 10 Incremental Basic Limit Development Factors
#     [ per D1; Volume Weighted Averages ]
#
# Ordinary age-to-age factors off the restated triangle.  "Volume weighted
# average" is chainladder's `average="volume"`, which is also its default.
#
# These factors are the deliverable: basic limit development at exposure year
# 10's cost level, estimated from data that was neither.
D2 = development.ldf_
D2

         12-24     24-36     36-48     48-60     60-72     72-84     84-96    96-108   108-120
(All)  3.51141  1.714074  1.398764  1.147195  1.076226  1.056689  1.039149  1.063407  1.012736

In [19]:
# D3: Exposure Year 10 Cumulative Development Factors [ per D2 ]
#
# The age-to-age factors chained from the right.
#
# chainladder stops at 108-Ult because no tail has been fitted, so the final
# age develops by the identity; the paper prints that as a tenth column of
# 1.000.  In production a tail step would follow `dev` in the Pipeline above,
# which is also what would populate it -- it is left off here so the factors
# stay comparable with the published exhibit.
D3 = development.cdf_
D3

          12-Ult    24-Ult    36-Ult    48-Ult    60-Ult    72-Ult    84-Ult   96-Ult   108-Ult
(All)  12.291862  3.500549  2.042239  1.460031  1.272696  1.182554  1.119112  1.07695  1.012736

In [20]:
# Check the D series against the exhibits as printed in the paper.
#
# D1 carries whole currency units, D2 and D3 three decimals, so each is checked
# at its own printed precision.  D3 is compared without the paper's trailing
# 1.000 column, for the reason given in the previous cell.
#
# One cell is excluded, and it is worth being explicit about why.  The paper's
# exhibit A1 prints 359,840 at exposure period 8, development interval 1.  The
# genins sample -- and the Taylor-Ashe triangle it comes from -- has 359,480.
# A transposed digit in the paper's own input, not a difference in method: the
# assertion below shows the paper's D1 is exactly what its A1 implies, so every
# exhibit downstream is internally consistent with it.  Nothing else in the
# notebook is affected, because D2 volume-weights that cell against eight
# others and the difference washes out below the printed precision.
TYPO = (7, 0)  # exposure period 8, development interval 1

D1_published = np.array(
    [
        [
            452881,
            1419731,
            2279040,
            2793772,
            3377947,
            3978376,
            4038185,
            4142394,
            4349865,
            4405265,
        ],
        [
            432566,
            1610197,
            2766439,
            4100116,
            4538378,
            4794873,
            5260266,
            5484617,
            5887561,
            None,
        ],
        [
            368296,
            1634013,
            2745402,
            3840401,
            4623708,
            4671636,
            5090015,
            5324759,
            None,
            None,
        ],
        [
            382236,
            1741436,
            2636785,
            4330559,
            4539482,
            4811270,
            4902613,
            None,
            None,
            None,
        ],
        [529368, 1353815, 2481777, 3242747, 3722312, 4131335, None, None, None, None],
        [459320, 1541795, 2468413, 3244186, 3922258, None, None, None, None, None],
        [481990, 1405037, 2583135, 3571425, None, None, None, None, None, None],
        [381903, 1504277, 2968365, None, None, None, None, None, None, None],
        [388062, 1400758, None, None, None, None, None, None, None, None],
        [344014, None, None, None, None, None, None, None, None, None],
    ],
    dtype="float64",
)

D2_published = np.array([3.511, 1.714, 1.399, 1.147, 1.076, 1.057, 1.039, 1.063, 1.013])
D3_published = np.array([
    12.291,
    3.501,
    2.042,
    1.460,
    1.273,
    1.183,
    1.119,
    1.077,
    1.013,
])

comparable = ~np.isnan(D1_published)
comparable[TYPO] = False
d1_dev = np.abs(D1.values[0, 0][comparable] - D1_published[comparable]).max()
assert d1_dev <= 3.0, f"D1 deviates from the paper by {d1_dev:.2f}"
print(
    f"D1: matches the published exhibit (max deviation {d1_dev:.2f}, 1 cell excluded)"
)

# The excluded cell: rerun it on the paper's own input and it reproduces the
# paper's own answer, which is what makes this a data typo rather than a bug.
ratio = C6.values[0, 0, -1, 0] / C5.values[0, 0][TYPO]
assert abs(359840 * ratio - D1_published[TYPO]) <= 1.0
assert abs(359480 * ratio - D1.values[0, 0][TYPO]) <= 1.0
print(
    f"    the excluded cell reconciles: paper's A1 359,840 -> {359840 * ratio:,.0f} "
    f"(paper prints {D1_published[TYPO]:,.0f}); "
    f"genins' 359,480 -> {359480 * ratio:,.0f}"
)

d2_dev = np.abs(D2.values[0, 0, 0] - D2_published).max()
assert d2_dev <= 0.0005, f"D2 deviates from the paper by {d2_dev:.6f}"
print(f"D2: matches the published exhibit (max deviation {d2_dev:.6f})")

d3_dev = np.abs(D3.values[0, 0, 0] - D3_published).max()
assert d3_dev <= 0.002, f"D3 deviates from the paper by {d3_dev:.6f}"
print(f"D3: matches the published exhibit (max deviation {d3_dev:.6f})")

D1: matches the published exhibit (max deviation 2.69, 1 cell excluded)
    the excluded cell reconciles: paper's A1 359,840 -> 381,903 (paper prints 381,903); genins' 359,480 -> 381,520
D2: matches the published exhibit (max deviation 0.000410)
D3: matches the published exhibit (max deviation 0.000862)

In [21]:
# E: Calculation of Development Factors by Layer
#
# D3 is one pattern: basic limit, exposure year 10 cost level.  Section 3 says
# a pattern for any OTHER layer follows from it by a ratio of layer
# expectations -- no refitting, no second triangle.  For a layer whose expected
# loss is L(i,j):
#
#     factor(i,j) = D3(j) * [ L(i,10) / C6(10,10) ] / [ L(i,j) / C6(10,j) ]
#
# L(i,10) / L(i,j) is how much of exposure period i's ultimate loss in that
# layer has emerged by age j, and the C6(10,.) terms put numerator and
# denominator on D3's own basis so the adjustment is dimensionless.
#
# This is the second thing cl.Sahasrabuddhe does, and which one it does is
# decided by what it is fitted on.  Section D fitted a triangle and got
# `triangle_`; fitting the development step instead gets the layer:
#
#   full_cdf_  the factors over the whole origin x development rectangle
#   full_ldf_  the same, age to age -- one row per cost level
#   cdf_       its latest diagonal, as an ordinary development pattern
#   ldf_       the same, age to age
#
# The target layer is named at construction as a pair of limits.  A
# ground-up layer attaches at zero: (0, basic_limit).
#
# The pattern is aligned to the rectangle's development ages by age, not by
# position.  That matters the moment a tail is fitted: cdf_ then has more
# entries than the triangle has ages, and zipping them positionally would
# quietly misalign every factor.

# E1: Basic Limit [ D3j * (C6i,10/C610,10) / (C6i,j/C610,j) ]
#
# Targeting the limit the pattern was fitted on, so this is the basic limit.
# Row 10 reproduces D3 exactly -- every ratio collapses to 1 -- and the other
# rows differ from it only by cost level.
# `data_limit` is not passed: it says where a triangle of claims is capped, and
# no claims are being restated here.  Only the target layer varies between the
# exhibits below, so that is all the helper takes.
def layer(target_layer):
    return cl.Sahasrabuddhe(
        means=theta_10,
        trend=B3,
        basic_limit=basic_limit,
        target_layer=target_layer,
    ).fit(development)


E1 = layer(target_layer=(0, basic_limit)).full_cdf_
E1

            12        24        36        48        60        72        84        96        108  120
2001  12.634047  3.590447  2.192669  1.530808  1.319190  1.211265  1.132835  1.084065  1.014624  1.0
2002  12.542336  3.789059  2.179048  1.524165  1.314775  1.208512  1.131509  1.083375  1.014441  1.0
2003  13.233037  3.760646  2.165033  1.517387  1.310284  1.205719  1.130166  1.082677  1.014255  1.0
2004  13.127703  3.731209  2.150647  1.510488  1.305725  1.202890  1.128809  1.081973  1.014068  1.0
2005  13.018549  3.700779  2.135915  1.503479  1.301105  1.200030  1.127439  1.081262  1.013879  1.0
2006  12.905653  3.669393  2.120865  1.496374  1.296434  1.197144  1.126059  1.080547  1.013689  1.0
2007  12.672130  3.604778  2.090324  1.482113  1.287091  1.191387  1.123313  1.079124  1.013312  1.0
2008  12.548665  3.570795  2.074492  1.474795  1.282311  1.188450  1.121914  1.078400  1.013120  1.0
2009  12.421868  3.536034  2.058454  1.467430  1.277510  1.185504  1.120514  1.077675  1.012928  1.0
2010  12.291862  3.500549  2.042239  1.460031  1.272696  1.182554  1.119112  1.076950  1.012736  1.0

In [22]:
# E1 as a development pattern.
#
# `full_cdf_` above is the full rectangle: nothing in the formula needs the
# data -- it is C6 and D3 all the way down, both defined for every (i, j) --
# so there is no reason to mask it to the triangle.  Each ROW is one exposure
# period's complete basic limit pattern, age 1 through 10, at that period's own
# cost level, and the cells below the latest diagonal are the factors a future
# valuation would use.
#
# Two ways to read the rectangle:
#
#   * Down a column: how the age-j-to-ultimate factor varies with cost level.
#     Column 1 runs 12.63, 12.54, 13.23, ..., 12.29 -- not monotonic, because
#     B3 is not monotonic in i.  The -5% calendar period step in B2 pushes the
#     early exposure periods around.
#
#   * Along the last column: every entry is 1.000 by construction, since
#     E1(i,10) = D3(10) * r(i,10)/r(i,10) regardless of cost level.
#
# `cdf_` collapses that to the ONE cell per row that each exposure period has
# actually reached -- the latest diagonal -- which is the pattern you would
# apply.  Reading a single row of the rectangle instead would apply one period's
# cost level to every other period.
layer(target_layer=(0, basic_limit)).cdf_

          12-Ult    24-Ult    36-Ult    48-Ult    60-Ult   72-Ult    84-Ult    96-Ult   108-Ult  120-Ult
(All)  12.291862  3.536034  2.074492  1.482113  1.296434  1.20003  1.128809  1.082677  1.014441      1.0

In [23]:
# E2: Basic Limit to Policy Limit
#     [ D3j * ((C4i,10-C6i,10)/C610,10) / ((C4i,j-C6i,j)/C610,j) ]
#
# C4 - C6 is the expected loss in the layer from the basic limit up to the
# policy limit.  Naming those two limits as the target attachment and
# exhaustion is what asks for it.
#
# The first column is enormous, and genuinely so: at age 12 almost nothing has
# emerged in a layer attaching at 500,000, so the factor needed to develop it
# to ultimate is astronomical.  The paper prints "very large" rather than a
# number.  This is the substantive point of developing by layer -- excess
# layers develop far more slowly than the ground-up data suggests.
E2 = layer(target_layer=(basic_limit, policy_limit)).full_cdf_
E2

               12          24         36        48        60        72        84        96        108  120
2001  7.338449e+09  652.392393  32.802503  5.923749  3.379574  2.174537  1.499164  1.256569  1.057066  1.0
2002  4.072028e+09  946.201046  30.374007  5.703890  3.292540  2.139801  1.487734  1.251528  1.055891  1.0
2003  9.317589e+09  807.040392  28.187688  5.498081  3.210093  2.106558  1.476699  1.246642  1.054748  1.0
2004  5.142957e+09  691.532697  26.214901  5.305185  3.131919  2.074719  1.466037  1.241903  1.053637  1.0
2005  2.888455e+09  595.215200  24.430826  5.124169  3.057724  2.044203  1.455732  1.237306  1.052555  1.0
2006  1.649822e+09  514.539733  22.813904  4.954097  2.987240  2.014934  1.445765  1.232844  1.051502  1.0
2007  5.726414e+08  390.696084  20.041666  4.647205  2.858021  1.960528  1.427015  1.224405  1.049502  1.0
2008  3.428915e+08  341.856949  18.819921  4.504917  2.797164  1.934553  1.417956  1.220306  1.048526  1.0
2009  2.084097e+08  300.267257  17.703576  4.370594  2.739128  1.909560  1.409172  1.216319  1.047575  1.0
2010  1.285202e+08  264.713658  16.681555  4.243641  2.683726  1.885493  1.400649  1.212436  1.046646  1.0

In [24]:
# E3: Policy Limit to Unlimited
#     [ D3j * ((C3i,10-C4i,10)/C610,10) / ((C3i,j-C4i,j)/C610,j) ]
#
# Everything above the policy limit -- the unlimited mean less what the policy
# limit retains -- so the layer exhausts at infinity.
#
# The first two columns come back non-finite here rather than merely large.
# That is not a failure of the arithmetic: at the earliest ages the expected
# loss above 2,000,000 underflows to zero in double precision, and the paper
# writes "very large" in the same cells for the same reason.
E3 = layer(target_layer=(policy_limit, np.inf)).full_cdf_
E3

      12            24            36          48         60         72        84        96        108  120
2001  NaN  2.956805e+09  84540.807477  279.494200  48.057882  11.154530  3.254072  1.886690  1.182713  1.0
2002  NaN  1.089961e+10  62194.143897  240.416049  43.322515  10.464219  3.157027  1.856973  1.177536  1.0
2003  NaN  5.778339e+09  46167.967193  207.716773  39.172686   9.835031  3.065596  1.828574  1.172533  1.0
2004  NaN  3.116347e+09  34572.085063  180.235744  35.525073   9.260493  2.979379  1.801423  1.167696  1.0
2005  NaN  1.712072e+09  26109.152351  157.042415  32.309555   8.734917  2.898010  1.775454  1.163021  1.0
2006  NaN  9.573302e+08  19880.824491  137.387344  29.466927   8.253295  2.821151  1.750605  1.158500  1.0
2007  NaN  3.193292e+08  11880.984314  106.721171  24.761740   7.414775  2.681482  1.704608  1.150008  1.0
2008  NaN  1.875867e+08   9258.015826   94.427472  22.760004   7.039675  2.616315  1.682757  1.145916  1.0
2009  NaN  1.119256e+08   7267.067736   83.850235  20.971848   6.693730  2.554574  1.661815  1.141957  1.0
2010  NaN  6.780012e+07   5744.909523   74.717559  19.370587   6.374193  2.496036  1.641737  1.138128  1.0

In [25]:
# E4: Limit of Data in Triangle [ D3j * (C5i,10/C610,10) / (C5i,j/C610,j) ]
#
# The layer the observed data actually sits in: ground up to the triangle
# limit.  This is the one to compare against, because it is the pattern the
# method says genins should have -- stated for the limit genins is reported at,
# rather than for the basic limit.
#
# E7 puts it next to what an unadjusted chainladder would have produced.
E4 = layer(target_layer=(0, triangle_limit)).full_cdf_
E4

            12        24        36        48        60        72        84        96        108  120
2001  13.777120  3.913155  2.375374  1.628523  1.386745  1.255003  1.154635  1.095575  1.017725  1.0
2002  13.759920  4.155107  2.372443  1.626736  1.385425  1.254090  1.154150  1.095312  1.017652  1.0
2003  14.608574  4.149315  2.369182  1.624764  1.383976  1.253093  1.153624  1.095027  1.017574  1.0
2004  14.585924  4.142882  2.365567  1.622597  1.382393  1.252010  1.153056  1.094720  1.017489  1.0
2005  14.560868  4.135767  2.361579  1.620228  1.380671  1.250839  1.152446  1.094391  1.017399  1.0
2006  14.533255  4.127925  2.357195  1.617647  1.378806  1.249579  1.151792  1.094040  1.017304  1.0
2007  14.470661  4.110151  2.347304  1.611906  1.374690  1.246820  1.150374  1.093281  1.017097  1.0
2008  14.434582  4.099908  2.341633  1.608661  1.372380  1.245284  1.149590  1.092863  1.016983  1.0
2009  14.395381  4.088780  2.335495  1.605183  1.369919  1.243656  1.148764  1.092423  1.016864  1.0
2010  14.352928  4.076730  2.328878  1.601471  1.367304  1.241935  1.147894  1.091962  1.016739  1.0

In [26]:
# E5: Unadjusted Incremental Development Factors at Limits of Data Triangle
#     [ per A1; Volume Weighted Averages ]
#
# The naive answer: fit development straight off the raw triangle, with no
# trend adjustment and no limit adjustment at all.  Everything from B1 onward
# exists to establish whether this is good enough.
unadjusted = cl.Development(average="volume").fit(genins)

E5 = unadjusted.ldf_
E5

          12-24     24-36     36-48     48-60     60-72     72-84     84-96    96-108   108-120
(All)  3.490607  1.747333  1.457413  1.173852  1.103824  1.086269  1.053874  1.076555  1.017725

In [27]:
# E6: Unadjusted Cumulative Development Factors [ per E5 ]
E6 = unadjusted.cdf_
E6

          12-Ult    24-Ult    36-Ult    48-Ult    60-Ult    72-Ult    84-Ult    96-Ult   108-Ult
(All)  14.446577  4.138701  2.368582  1.625196  1.384499  1.254276  1.154664  1.095637  1.017725

In [28]:
# E7: Differences [ E6 / E4, last diagonal - 1 ]
#
# The payoff.  E4 varies by exposure period, so the comparison is taken down
# its last diagonal -- the cell of each column that an unadjusted fit would
# actually have been estimating.
#
# The differences are small: under 1.2% everywhere, and inside 0.1% from
# development interval 7 on.  Section 4.1 makes this point explicitly -- in
# Example 1 the basic limit sits well ABOVE the working claims layer, so the
# limit adjustment has little left to do and the unadjusted pattern is close
# to right.  Example 2 is the same data with the basic limit inside the working
# layer, where the two diverge materially.
#
# Small differences here are a result, not a disappointment: they say the
# adjustment is unnecessary in this configuration, and the method tells you so
# rather than leaving you to assume it.
import pandas as pd

last_diagonal = np.array([E4.values[0, 0, 10 - 1 - j, j] for j in range(10)])
labels = list(E6.development) + ["120-Ult"]

E7 = pd.Series(
    (np.append(E6.values[0, 0, 0], 1.0) / last_diagonal - 1) * 100, index=labels
)
E7.round(1).to_frame("difference %").T

,12-Ult,24-Ult,36-Ult,48-Ult,60-Ult,72-Ult,84-Ult,96-Ult,108-Ult,120-Ult
difference %,0.7,1.2,1.2,0.8,0.4,0.3,0.1,0.1,0.0,0.0

In [29]:
# Check the E series against the exhibits as printed in the paper.
#
# E2 and E3 are compared only where the paper prints a number: it writes "very
# large" wherever the layer has essentially no expected loss at that age, and
# those cells are non-finite or astronomically large here for the same reason.
# `np.isfinite` on the published grid selects exactly the comparable cells.
VERY_LARGE = np.nan

E1_published = np.array(
    [
        [12.633, 3.590, 2.193, 1.531, 1.319, 1.211, 1.133, 1.084, 1.015, 1.000],
        [12.541, 3.789, 2.179, 1.524, 1.315, 1.209, 1.132, 1.083, 1.014, None],
        [13.232, 3.761, 2.165, 1.517, 1.310, 1.206, 1.130, 1.083, None, None],
        [13.126, 3.731, 2.151, 1.510, 1.306, 1.203, 1.129, None, None, None],
        [13.017, 3.701, 2.136, 1.503, 1.301, 1.200, None, None, None, None],
        [12.904, 3.669, 2.121, 1.496, 1.296, None, None, None, None, None],
        [12.671, 3.605, 2.090, 1.482, None, None, None, None, None, None],
        [12.547, 3.571, 2.074, None, None, None, None, None, None, None],
        [12.421, 3.536, None, None, None, None, None, None, None, None],
        [12.291, None, None, None, None, None, None, None, None, None],
    ],
    dtype="float64",
)

E2_published = np.array(
    [
        [VERY_LARGE, 652.420, 32.802, 5.924, 3.380, 2.175, 1.499, 1.257, 1.057, 1.000],
        [VERY_LARGE, 946.242, 30.374, 5.704, 3.293, 2.140, 1.488, 1.252, 1.056, None],
        [VERY_LARGE, 807.075, 28.187, 5.498, 3.210, 2.107, 1.477, 1.247, None, None],
        [VERY_LARGE, 691.561, 26.215, 5.305, 3.132, 2.075, 1.466, None, None, None],
        [VERY_LARGE, 595.239, 24.431, 5.124, 3.058, 2.044, None, None, None, None],
        [VERY_LARGE, 514.560, 22.814, 4.954, 2.987, None, None, None, None, None],
        [VERY_LARGE, 390.710, 20.042, 4.647, None, None, None, None, None, None],
        [VERY_LARGE, 341.869, 18.820, None, None, None, None, None, None, None],
        [VERY_LARGE, 300.278, None, None, None, None, None, None, None, None],
        [VERY_LARGE, None, None, None, None, None, None, None, None, None],
    ],
    dtype="float64",
)

E3_published = np.array(
    [
        [
            VERY_LARGE,
            VERY_LARGE,
            84538.278,
            279.503,
            48.056,
            11.155,
            3.254,
            1.887,
            1.183,
            1.000,
        ],
        [
            VERY_LARGE,
            VERY_LARGE,
            62192.336,
            240.423,
            43.321,
            10.464,
            3.157,
            1.857,
            1.178,
            None,
        ],
        [
            VERY_LARGE,
            VERY_LARGE,
            46166.664,
            207.723,
            39.172,
            9.835,
            3.066,
            1.829,
            None,
            None,
        ],
        [
            VERY_LARGE,
            VERY_LARGE,
            34571.138,
            180.241,
            35.524,
            9.261,
            2.979,
            None,
            None,
            None,
        ],
        [
            VERY_LARGE,
            VERY_LARGE,
            26108.458,
            157.047,
            32.309,
            8.735,
            None,
            None,
            None,
            None,
        ],
        [
            VERY_LARGE,
            VERY_LARGE,
            19880.311,
            137.391,
            29.466,
            None,
            None,
            None,
            None,
            None,
        ],
        [
            VERY_LARGE,
            VERY_LARGE,
            11880.695,
            106.724,
            None,
            None,
            None,
            None,
            None,
            None,
        ],
        [VERY_LARGE, VERY_LARGE, 9257.797, None, None, None, None, None, None, None],
        [VERY_LARGE, VERY_LARGE, None, None, None, None, None, None, None, None],
        [VERY_LARGE, None, None, None, None, None, None, None, None, None],
    ],
    dtype="float64",
)

E4_published = np.array(
    [
        [13.776, 3.913, 2.375, 1.629, 1.387, 1.255, 1.155, 1.096, 1.018, 1.000],
        [13.759, 4.155, 2.372, 1.627, 1.385, 1.254, 1.154, 1.095, 1.018, None],
        [14.607, 4.149, 2.369, 1.625, 1.384, 1.253, 1.154, 1.095, None, None],
        [14.584, 4.143, 2.366, 1.623, 1.382, 1.252, 1.153, None, None, None],
        [14.559, 4.136, 2.362, 1.620, 1.381, 1.251, None, None, None, None],
        [14.532, 4.128, 2.357, 1.618, 1.379, None, None, None, None, None],
        [14.469, 4.110, 2.347, 1.612, None, None, None, None, None, None],
        [14.433, 4.100, 2.342, None, None, None, None, None, None, None],
        [14.394, 4.089, None, None, None, None, None, None, None, None],
        [14.352, None, None, None, None, None, None, None, None, None],
    ],
    dtype="float64",
)

E5_published = np.array([3.490, 1.747, 1.457, 1.174, 1.104, 1.086, 1.054, 1.077, 1.018])
E6_published = np.array([
    14.445,
    4.139,
    2.369,
    1.625,
    1.384,
    1.254,
    1.155,
    1.096,
    1.018,
])
E7_published = np.array([0.7, 1.2, 1.2, 0.8, 0.4, 0.3, 0.1, 0.1, 0.0, 0.0])

for name, computed, published, tol in [
    ("E1", E1.values[0, 0], E1_published, 0.002),
    ("E2", E2.values[0, 0], E2_published, 0.002),
    ("E3", E3.values[0, 0], E3_published, 0.010),
    ("E4", E4.values[0, 0], E4_published, 0.002),
]:
    comparable = np.isfinite(published)
    # E3's largest printed factor carries five significant figures, so compare
    # it relatively rather than absolutely.
    deviation = np.abs(computed[comparable] / published[comparable] - 1).max()
    assert deviation <= tol, f"{name} deviates from the paper by {deviation:.5f}"
    print(
        f"{name}: matches the published exhibit "
        f"(max relative deviation {deviation:.5f}, {comparable.sum()} cells)"
    )

# E5 and E6 are fitted on the raw triangle, so the A1 typo found in the D
# series reaches them too -- and only through the 12-24 factor, whose
# denominator includes exposure period 8 at age 12.  The first factor is
# therefore checked by reconciliation rather than by tolerance, exactly as the
# excluded D1 cell was.
raw = genins.values[0, 0]
paper_ldf_12_24 = np.nansum(raw[:9, 1]) / (np.nansum(raw[:9, 0]) + (359840 - 359480))
assert abs(paper_ldf_12_24 - E5_published[0]) <= 0.0005
print(
    f"E5: first factor reconciles to the paper's A1 "
    f"({paper_ldf_12_24:.5f} vs published {E5_published[0]:.3f}); "
    f"genins gives {E5.values[0, 0, 0, 0]:.5f}"
)

for name, computed, published, tol, skip in [
    ("E5", E5.values[0, 0, 0], E5_published, 0.0005, 1),
    ("E6", E6.values[0, 0, 0], E6_published, 0.002, 0),
    ("E7", E7.values, E7_published, 0.05, 0),
]:
    deviation = np.abs(computed[skip:] - published[skip:]).max()
    assert deviation <= tol, f"{name} deviates from the paper by {deviation:.5f}"
    note = " (first factor excluded)" if skip else ""
    print(
        f"{name}: matches the published exhibit (max deviation {deviation:.5f}){note}"
    )

E1: matches the published exhibit (max relative deviation 0.00043, 55 cells)
E2: matches the published exhibit (max relative deviation 0.00038, 45 cells)
E3: matches the published exhibit (max relative deviation 0.00039, 36 cells)
E4: matches the published exhibit (max relative deviation 0.00039, 55 cells)
E5: first factor reconciles to the paper's A1 (3.49023 vs published 3.490); genins gives 3.49061
E5: matches the published exhibit (max deviation 0.00044) (first factor excluded)
E6: matches the published exhibit (max deviation 0.00158)
E7: matches the published exhibit (max deviation 0.04912)