# Sahasrabuddhe verification

This notebook reproduces the examples found at the end of the paper to verify that the new `LEV` and `Sahasrabuddhe` estimators work correctly.

## Example 1

### A1: Data and Information

The paper uses the well-known Mack triangle for its examples. This is the same as the `genins` sample triangle.

In [1]:
import chainladder as cl

genins = cl.load_sample("genins")
genins

           12         24         36         48         60         72         84         96         108        120
2001  357848.0  1124788.0  1735330.0  2218270.0  2745596.0  3319994.0  3466336.0  3606286.0  3833515.0  3901463.0
2002  352118.0  1236139.0  2170033.0  3353322.0  3799067.0  4120063.0  4647867.0  4914039.0  5339085.0        NaN
2003  290507.0  1292306.0  2218525.0  3235179.0  3985995.0  4132918.0  4628910.0  4909315.0        NaN        NaN
2004  310608.0  1418858.0  2195047.0  3757447.0  4029929.0  4381982.0  4588268.0        NaN        NaN        NaN
2005  443160.0  1136350.0  2128333.0  2897821.0  3402672.0  3873311.0        NaN        NaN        NaN        NaN
2006  396132.0  1333217.0  2180715.0  2985752.0  3691712.0        NaN        NaN        NaN        NaN        NaN
2007  440832.0  1288463.0  2419861.0  3483130.0        NaN        NaN        NaN        NaN        NaN        NaN
2008  359480.0  1421128.0  2864498.0        NaN        NaN        NaN        NaN        NaN        NaN        NaN
2009  376686.0  1363294.0        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN
2010  344014.0        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN

In [2]:
# Limits
triangle_limit = 1000000
basic_limit = 500000
policy_limit = 2000000

### B1: Exposure Period Trend Index

We'll need a 10 x 10 placeholder Triangle to visualize the trend indexes.

*2% EP (Exposure Period) Trend; 5% between EP 6 and 7*

In [3]:
# Create a placeholder triangle of ones.
ones = genins.copy()
ones.valuation_date = ones.valuation.max()
ones = (ones * 0 + 1).fillna(1)
ones

      12   24   36   48   60   72   84   96   108  120
2001  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
2002  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
2003  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
2004  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
2005  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
2006  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
2007  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
2008  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
2009  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
2010  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0

Since chainladder trends to the latest exposure period by default, some manipulation is required to set the earliest exposure period to 1.

In [4]:
B1 = (
    1
    / cl
    .Trend(
        trends=[0.02, 0.05, 0.02],
        dates=[
            ("2006-12-31", None),  # 2% from the earliest origin up to EP 6
            ("2007-12-31", "2006-12-31"),  # 5% for the single EP 6 -> EP 7 step
            ("2010-12-31", "2007-12-31"),  # 2% from EP 7 through the latest origin
        ],
        axis="origin",
    )
    .fit(ones)
    .trend_
)
B1 = B1 / B1.iloc[0, 0, :1, :]

B1

           12        24        36        48        60        72        84        96        108       120
2001  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
2002  1.020000  1.020000  1.020000  1.020000  1.020000  1.020000  1.020000  1.020000  1.020000  1.020000
2003  1.040400  1.040400  1.040400  1.040400  1.040400  1.040400  1.040400  1.040400  1.040400  1.040400
2004  1.061208  1.061208  1.061208  1.061208  1.061208  1.061208  1.061208  1.061208  1.061208  1.061208
2005  1.082432  1.082432  1.082432  1.082432  1.082432  1.082432  1.082432  1.082432  1.082432  1.082432
2006  1.104081  1.104081  1.104081  1.104081  1.104081  1.104081  1.104081  1.104081  1.104081  1.104081
2007  1.159285  1.159285  1.159285  1.159285  1.159285  1.159285  1.159285  1.159285  1.159285  1.159285
2008  1.182471  1.182471  1.182471  1.182471  1.182471  1.182471  1.182471  1.182471  1.182471  1.182471
2009  1.206120  1.206120  1.206120  1.206120  1.206120  1.206120  1.206120  1.206120  1.206120  1.206120
2010  1.230242  1.230242  1.230242  1.230242  1.230242  1.230242  1.230242  1.230242  1.230242  1.230242

### B2: Calendar Period Trend Index

*1% Calendar Period Trend; -5% between CP 2 and 3*

In [5]:
B2 = (
    1
    / cl
    .Trend(
        trends=[0.01, -0.05, 0.01],
        dates=[
            ("2002-12-31", None),  # 1% from the earliest valuation up to CP 2
            ("2003-12-31", "2002-12-31"),  # -5% for the single CP 2 -> CP 3 step
            (None, "2003-12-31"),  # 1% from CP 3 out to the last valuation
        ],
        axis="valuation",
    )
    .fit(ones)
    .trend_
)
B2 = B2 / B2.iloc[0, 0, :1, :1]

B2

           12        24        36        48        60        72        84        96        108       120
2001  1.000000  1.010000  0.959500  0.969095  0.978786  0.988574  0.998460  1.008444  1.018529  1.028714
2002  1.010000  0.959500  0.969095  0.978786  0.988574  0.998460  1.008444  1.018529  1.028714  1.039001
2003  0.959500  0.969095  0.978786  0.988574  0.998460  1.008444  1.018529  1.028714  1.039001  1.049391
2004  0.969095  0.978786  0.988574  0.998460  1.008444  1.018529  1.028714  1.039001  1.049391  1.059885
2005  0.978786  0.988574  0.998460  1.008444  1.018529  1.028714  1.039001  1.049391  1.059885  1.070484
2006  0.988574  0.998460  1.008444  1.018529  1.028714  1.039001  1.049391  1.059885  1.070484  1.081189
2007  0.998460  1.008444  1.018529  1.028714  1.039001  1.049391  1.059885  1.070484  1.081189  1.092001
2008  1.008444  1.018529  1.028714  1.039001  1.049391  1.059885  1.070484  1.081189  1.092001  1.102921
2009  1.018529  1.028714  1.039001  1.049391  1.059885  1.070484  1.081189  1.092001  1.102921  1.113950
2010  1.028714  1.039001  1.049391  1.059885  1.070484  1.081189  1.092001  1.102921  1.113950  1.125089

### B3: Combined Trend Index

`B1 * B2`

In [6]:
B3 = B1 * B2

B3

           12        24        36        48        60        72        84        96        108       120
2001  1.000000  1.010000  0.959500  0.969095  0.978786  0.988574  0.998460  1.008444  1.018529  1.028714
2002  1.030200  0.978690  0.988477  0.998362  1.008345  1.018429  1.028613  1.038899  1.049288  1.059781
2003  0.998264  1.008246  1.018329  1.028512  1.038797  1.049185  1.059677  1.070274  1.080977  1.091786
2004  1.028411  1.038695  1.049082  1.059573  1.070169  1.080871  1.091679  1.102596  1.113622  1.124758
2005  1.059469  1.070064  1.080765  1.091572  1.102488  1.113513  1.124648  1.135895  1.147254  1.158726
2006  1.091465  1.102380  1.113404  1.124538  1.135783  1.147141  1.158612  1.170199  1.181901  1.193720
2007  1.157499  1.169074  1.180765  1.192572  1.204498  1.216543  1.228709  1.240996  1.253406  1.265940
2008  1.192455  1.204380  1.216424  1.228588  1.240874  1.253283  1.265816  1.278474  1.291258  1.304171
2009  1.228468  1.240752  1.253160  1.265691  1.278348  1.291132  1.304043  1.317084  1.330254  1.343557
2010  1.265567  1.278223  1.291005  1.303915  1.316954  1.330124  1.343425  1.356860  1.370428  1.384132

Check the reconstruction against the exhibits in the paper.

In [7]:
import numpy as np

B1_published = np.tile(
    np.array([1.000, 1.020, 1.040, 1.061, 1.082, 1.104, 1.159, 1.182, 1.206, 1.230])[
        :, None
    ],
    (1, 10),
)

# B2 is constant along diagonals, so 19 calendar-period values determine it.
_cp = np.array([
    1.000,
    1.010,
    0.960,
    0.969,
    0.979,
    0.989,
    0.998,
    1.008,
    1.019,
    1.029,
    1.039,
    1.049,
    1.060,
    1.070,
    1.081,
    1.092,
    1.103,
    1.114,
    1.125,
])
_i, _j = np.indices((10, 10))
B2_published = _cp[_i + _j]

B3_published = np.array([
    [1.000, 1.010, 0.960, 0.969, 0.979, 0.989, 0.998, 1.008, 1.019, 1.029],
    [1.030, 0.979, 0.988, 0.998, 1.008, 1.018, 1.029, 1.039, 1.049, 1.060],
    [0.998, 1.008, 1.018, 1.029, 1.039, 1.049, 1.060, 1.070, 1.081, 1.092],
    [1.028, 1.039, 1.049, 1.060, 1.070, 1.081, 1.092, 1.103, 1.114, 1.125],
    [1.059, 1.070, 1.081, 1.092, 1.102, 1.114, 1.125, 1.136, 1.147, 1.159],
    [1.091, 1.102, 1.113, 1.125, 1.136, 1.147, 1.159, 1.170, 1.182, 1.194],
    [1.157, 1.169, 1.181, 1.193, 1.204, 1.217, 1.229, 1.241, 1.253, 1.266],
    [1.192, 1.204, 1.216, 1.229, 1.241, 1.253, 1.266, 1.278, 1.291, 1.304],
    [1.228, 1.241, 1.253, 1.266, 1.278, 1.291, 1.304, 1.317, 1.330, 1.344],
    [1.266, 1.278, 1.291, 1.304, 1.317, 1.330, 1.343, 1.357, 1.370, 1.384],
])

for name, computed, published in [
    ("B1", B1, B1_published),
    ("B2", B2, B2_published),
    ("B3", B3, B3_published),
]:
    deviation = np.abs(computed.values[0, 0] - published).max()
    assert deviation <= 0.0006, f"{name} deviates from the paper by {deviation:.6f}"
    print(f"{name}: matches the published exhibit (max deviation {deviation:.6f})")

B1: matches the published exhibit (max deviation 0.000471)
B2: matches the published exhibit (max deviation 0.000500)
B3: matches the published exhibit (max deviation 0.000500)

### T: the cost level index relative to the latest exposure period

Since chainladder's default trending behavior assumes the base period as the latest exposure period, we restate B3 to be relative to the 2010 cost level.

In [8]:
T = B3 / B3.iloc[0, 0, -1:, :]

T

           12        24        36        48        60        72        84        96        108       120
2001  0.790159  0.790159  0.743219  0.743219  0.743219  0.743219  0.743219  0.743219  0.743219  0.743219
2002  0.814022  0.765664  0.765664  0.765664  0.765664  0.765664  0.765664  0.765664  0.765664  0.765664
2003  0.788788  0.788788  0.788788  0.788788  0.788788  0.788788  0.788788  0.788788  0.788788  0.788788
2004  0.812609  0.812609  0.812609  0.812609  0.812609  0.812609  0.812609  0.812609  0.812609  0.812609
2005  0.837150  0.837150  0.837150  0.837150  0.837150  0.837150  0.837150  0.837150  0.837150  0.837150
2006  0.862432  0.862432  0.862432  0.862432  0.862432  0.862432  0.862432  0.862432  0.862432  0.862432
2007  0.914609  0.914609  0.914609  0.914609  0.914609  0.914609  0.914609  0.914609  0.914609  0.914609
2008  0.942230  0.942230  0.942230  0.942230  0.942230  0.942230  0.942230  0.942230  0.942230  0.942230
2009  0.970685  0.970685  0.970685  0.970685  0.970685  0.970685  0.970685  0.970685  0.970685  0.970685
2010  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000

### C1: Claims Size Model Parameters at Exposure Year 10 Cost Level

This paper assumes that mean claim sizes per development period can be supplied via an external model.

In [9]:
theta_10 = {
    12: 28138,
    24: 84242,
    36: 133998,
    48: 182460,
    60: 204649,
    72: 228245,
    84: 252830,
    96: 265063,
    108: 275707,
    120: 280000,
}

C1 = cl.LEV(means=theta_10).fit(genins).means_
C1

          12       24        36        48        60        72        84        96        108       120
2010  28138.0  84242.0  133998.0  182460.0  204649.0  228245.0  252830.0  265063.0  275707.0  280000.0

### C2: Claims Size Model Parameters

$C2_{i,j} = C1_j \, \dfrac{B3_{i,j}}{B3_{10,j}}$

Equation 3.1.  C1 holds one row of parameters, all at exposure year 10's cost
level. We now produce a triangle that restates the means from the claim size model to different cost levels.

In [10]:
lev = cl.LEV(
    means=theta_10,
    trend=T,
).fit(genins)

C2 = lev.means_
C2

               12            24             36             48             60             72             84             96             108            120
2001  22233.506237  66564.611286   99589.896059  135607.788436  152099.080870  169636.082821  187908.128632  196999.929991  204910.755926  208101.396263
2002  22904.958125  64501.108337  102597.510919  139703.143647  156692.473113  174759.092522  193582.954117  202949.327877  211099.060755  214386.058430
2003  22194.904423  66449.041808  105695.955749  143922.178585  161424.585801  180036.817117  199429.159331  209078.397579  217474.252390  220860.517394
2004  22865.190537  68455.802871  108887.973613  148268.628378  166299.608292  185473.928994  205451.919943  215392.565186  224041.974812  227530.505020
2005  23555.719291  70523.168118  112176.390416  152746.340955  171321.856462  191075.241649  211656.567925  221897.420654  230808.042452  234401.926271
2006  24267.102013  72652.967795  115564.117407  157359.280452  176495.776528  196845.713947  218048.596277  228598.722758  237778.445334  241480.864444
2007  25735.261685  77048.472346  122555.746510  166879.516919  187173.771007  208754.879641  231240.536352  242428.945485  252164.041276  256090.456743
2008  26512.466588  79375.336211  126256.930054  171919.278330  192826.418892  215059.277006  238224.000549  249750.299639  259779.395323  263824.388537
2009  27313.143079  81772.471365  130069.889342  177111.240536  198649.776742  221554.067171  245418.365366  257292.758688  267624.733062  271791.885071
2010  28138.000000  84242.000000  133998.000000  182460.000000  204649.000000  228245.000000  252830.000000  265063.000000  275707.000000  280000.000000

### C3: Unlimited Means

For an exponential model, the mean is the parameter, so C3 restates C2 without
changing it.  The paper prints it as its own exhibit because the general
method needs M(Phi) -- the unlimited first moment -- as a distinct quantity
from the parameters: for a lognormal or Pareto the two would differ.

In [11]:
C3 = cl.LEV(
    means=theta_10,
    trend=T,
    limit=np.inf,
).fit(genins).lev_
C3

               12            24             36             48             60             72             84             96             108            120
2001  22233.506237  66564.611286   99589.896059  135607.788436  152099.080870  169636.082821  187908.128632  196999.929991  204910.755926  208101.396263
2002  22904.958125  64501.108337  102597.510919  139703.143647  156692.473113  174759.092522  193582.954117  202949.327877  211099.060755  214386.058430
2003  22194.904423  66449.041808  105695.955749  143922.178585  161424.585801  180036.817117  199429.159331  209078.397579  217474.252390  220860.517394
2004  22865.190537  68455.802871  108887.973613  148268.628378  166299.608292  185473.928994  205451.919943  215392.565186  224041.974812  227530.505020
2005  23555.719291  70523.168118  112176.390416  152746.340955  171321.856462  191075.241649  211656.567925  221897.420654  230808.042452  234401.926271
2006  24267.102013  72652.967795  115564.117407  157359.280452  176495.776528  196845.713947  218048.596277  228598.722758  237778.445334  241480.864444
2007  25735.261685  77048.472346  122555.746510  166879.516919  187173.771007  208754.879641  231240.536352  242428.945485  252164.041276  256090.456743
2008  26512.466588  79375.336211  126256.930054  171919.278330  192826.418892  215059.277006  238224.000549  249750.299639  259779.395323  263824.388537
2009  27313.143079  81772.471365  130069.889342  177111.240536  198649.776742  221554.067171  245418.365366  257292.758688  267624.733062  271791.885071
2010  28138.000000  84242.000000  133998.000000  182460.000000  204649.000000  228245.000000  252830.000000  265063.000000  275707.000000  280000.000000

### C4: Limited Expected Values at Policy Limits

$\mathrm{LEV}(d) = \theta \, (1 - e^{-d / \theta})$, capping each claim at the policy limit.

In [12]:
C4 = cl.LEV(
    means=theta_10,
    trend=T,
    limit=policy_limit,
).fit(genins).lev_
C4

               12            24             36             48             60             72             84             96             108            120
2001  22233.506237  66564.611286   99589.895869  135607.735087  152098.784764  169634.796912  187903.646005  196992.249598  204898.933678  208087.451819
2002  22904.958125  64501.108337  102597.510569  139703.058960  156692.024598  174757.220840  193576.645142  202938.672816  211082.847036  214367.017919
2003  22194.904423  66449.041808  105695.955109  143922.045846  161423.914067  180034.120285  199420.360749  209063.744144  217452.201681  220834.732274
2004  22865.190537  68455.802871  108887.972465  148268.422866  166298.613220  185470.081265  205439.757781  215372.582904  224012.228949  227495.865007
2005  23555.719291  70523.168118  112176.388389  152746.026549  171320.398025  191069.804028  211639.900595  221870.394725  230768.231886  234355.751228
2006  24267.102013  72652.967795  115564.113885  157358.804996  176493.660932  196838.100363  218025.945232  228562.460837  237725.571780  241419.776425
2007  25735.261685  77048.472346  122555.736486  166878.475762  187169.488516  208740.464175  231199.999514  242365.598711  252073.438021  255986.544622
2008  26512.466588  79375.336210  126256.913393  171917.754216  192820.384211  215039.610688  238170.187985  249667.185195  259661.623615  263689.797789
2009  27313.143079  81772.471363  130069.862032  177109.032297  198641.350688  221527.457359  245347.458286  257184.478360  267472.685986  271618.724296
2010  28138.000000  84241.999996  133997.955844  182456.832383  204637.339337  228209.281780  252737.239682  264922.901351  275511.996738  279778.662710

In [13]:
cl.LEV(
    means=theta_10,
    trend=T,
    limit=policy_limit,
).fit(genins).means_

               12            24             36             48             60             72             84             96             108            120
2001  22233.506237  66564.611286   99589.896059  135607.788436  152099.080870  169636.082821  187908.128632  196999.929991  204910.755926  208101.396263
2002  22904.958125  64501.108337  102597.510919  139703.143647  156692.473113  174759.092522  193582.954117  202949.327877  211099.060755  214386.058430
2003  22194.904423  66449.041808  105695.955749  143922.178585  161424.585801  180036.817117  199429.159331  209078.397579  217474.252390  220860.517394
2004  22865.190537  68455.802871  108887.973613  148268.628378  166299.608292  185473.928994  205451.919943  215392.565186  224041.974812  227530.505020
2005  23555.719291  70523.168118  112176.390416  152746.340955  171321.856462  191075.241649  211656.567925  221897.420654  230808.042452  234401.926271
2006  24267.102013  72652.967795  115564.117407  157359.280452  176495.776528  196845.713947  218048.596277  228598.722758  237778.445334  241480.864444
2007  25735.261685  77048.472346  122555.746510  166879.516919  187173.771007  208754.879641  231240.536352  242428.945485  252164.041276  256090.456743
2008  26512.466588  79375.336211  126256.930054  171919.278330  192826.418892  215059.277006  238224.000549  249750.299639  259779.395323  263824.388537
2009  27313.143079  81772.471365  130069.889342  177111.240536  198649.776742  221554.067171  245418.365366  257292.758688  267624.733062  271791.885071
2010  28138.000000  84242.000000  133998.000000  182460.000000  204649.000000  228245.000000  252830.000000  265063.000000  275707.000000  280000.000000

### C5: Limited Expected Values at Limits of Data Triangle

In [14]:
C5 = cl.LEV(
    means=theta_10,
    trend=T,
    limit=triangle_limit,
).fit(genins).lev_
C5

               12            24             36             48             60             72             84             96             108            120
2001  22233.506237  66564.591387   99585.557090  135522.732052  151886.860388  169169.031808  186990.347550  195769.874310  203354.315794  206397.912107
2002  22904.958125  64501.096412  102591.511014  139594.373165  156427.371575  174187.171582  192477.825150  201478.805034  209249.006431  212365.657475
2003  22194.904423  66449.022456  105687.730390  143783.961079  161095.292075  179340.017977  198104.510732  207328.049979  215284.398171  218474.115311
2004  22865.190537  68455.771879  108876.791402  148094.068839  165892.815867  184629.148968  203871.179767  213317.948378  221460.440021  224723.075675
2005  23555.719291  70523.119123  112161.311522  152527.196253  170821.994293  190055.930691  209778.337380  219448.546606  227776.772307  231112.014555
2006  24267.102013  72652.891306  115543.943787  157085.752802  175884.717069  195621.499374  215826.203755  225719.585951  234232.716731  237640.084879
2007  25735.261685  77048.294468  122520.696736  166462.686191  186278.466572  207020.146568  228178.876659  238510.132950  247384.199958  250931.881109
2008  26512.466588  79375.068120  126211.064384  171407.394858  191747.694705  213002.720652  234643.575394  245194.220493  254248.151068  257865.502578
2009  27313.143079  81772.071792  130010.289510  176485.857532  197356.009455  219125.999578  241246.806956  252014.525621  261245.739557  264931.586730
2010  28138.000000  84241.410874  133921.078748  181699.760925  203104.220719  225389.740789  247987.212456  258969.153259  268374.622184  272127.615270

### C6: Limited Expected Values at Basic Limit

In [15]:
C6 = cl.LEV(
    means=theta_10,
    trend=T,
    limit=basic_limit,
).fit(genins).lev_
C6

               12            24             36             48             60             72             84             96             108            120
2001  22233.506233  66528.216355   98932.539645  132211.568763  146417.660245  160735.032079  174775.782093  181433.270650  187052.107487  189273.294094
2002  22904.958117  64473.375063  101812.924774  135804.993031  150247.365234  164761.673629  178956.466841  185673.864857  191336.856169  193573.903397
2003  22194.904419  66413.181622  104763.546392  139462.070459  154133.762572  168836.393047  183175.742563  189948.319916  195651.399482  197902.686513
2004  22865.190529  68409.742134  107784.520720  143181.222016  158074.681492  172956.554252  187430.651835  194253.571928  199992.605742  202256.490370
2005  23555.719277  70464.386576  110875.815194  146960.707765  162067.813299  177119.415350  191718.167009  198586.504009  204357.304689  206632.128946
2006  24267.101986  72578.421660  114037.242657  150798.631540  166110.719299  181322.138597  196035.201040  202943.957182  208742.298296  211026.394008
2007  25735.261591  76931.402740  120483.175345  158539.222529  174228.597875  189725.061095  204632.645993  211606.330567  217446.551397  219744.040271
2008  26512.466417  79229.460195  123850.509734  162538.306252  178403.987684  194028.786698  209018.809159  216017.791109  221872.888125  224174.679275
2009  27313.142773  81591.711627  127285.622208  166586.870738  182618.351890  198360.355726  213421.849212  220441.013183  226306.741413  228611.178520
2010  28137.999460  84019.223907  130787.502536  170682.342270  186868.743113  202716.611125  217838.544259  224872.786033  230744.928311  233050.370349

Check the transformer behavior.

In [16]:
lev_transformed = lev.transform(genins)

assert (lev_transformed == genins).all(), "transform leaves the values untouched"
assert np.allclose(
    np.nan_to_num(lev_transformed.means_.values),
    np.nan_to_num(C2.values),
), "the restated parameters ride along on the triangle"
assert np.allclose(
    np.nan_to_num(lev_transformed.lev_.values),
    np.nan_to_num(C3.values),
), "so does the layer expectation, here the unlimited mean"

print("transform attaches the fitted quantities and leaves the data alone")
print(f"  values unchanged : {(lev_transformed == genins).all()}")
print(f"  carries means_   : {hasattr(lev_transformed, 'means_')}")
print(f"  carries lev_     : {hasattr(lev_transformed, 'lev_')}")

transform attaches the fitted quantities and leaves the data alone
  values unchanged : True
  carries means_   : True
  carries lev_     : True

Check the C series against the exhibits as printed in the paper.

In [18]:
C2_published = np.array([
    [22233, 66564, 99590, 135608, 152099, 169636, 187908, 197000, 204911, 208101],
    [22905, 64501, 102598, 139703, 156693, 174759, 193583, 202949, 211099, 214386],
    [22195, 66449, 105696, 143922, 161425, 180037, 199429, 209078, 217475, 220861],
    [22865, 68455, 108888, 148268, 166300, 185474, 205452, 215392, 224042, 227531],
    [23555, 70523, 112177, 152746, 171322, 191075, 211657, 221897, 230808, 234402],
    [24267, 72653, 115564, 157359, 176496, 196846, 218049, 228598, 237779, 241481],
    [25735, 77048, 122556, 166879, 187174, 208755, 231241, 242429, 252164, 256090],
    [26512, 79375, 126257, 171919, 192827, 215059, 238224, 249750, 259780, 263824],
    [27313, 81772, 130070, 177111, 198650, 221554, 245418, 257292, 267625, 271792],
    [28138, 84242, 133998, 182460, 204649, 228245, 252830, 265063, 275707, 280000],
])

C4_published = np.array([
    [22233, 66564, 99590, 135607, 152099, 169635, 187904, 196992, 204899, 208087],
    [22905, 64501, 102598, 139703, 156692, 174757, 193577, 202938, 211083, 214367],
    [22195, 66449, 105696, 143922, 161424, 180034, 199420, 209063, 217453, 220835],
    [22865, 68455, 108888, 148268, 166299, 185470, 205440, 215372, 224013, 227496],
    [23555, 70523, 112177, 152746, 171321, 191070, 211640, 221870, 230769, 234356],
    [24267, 72653, 115564, 157358, 176494, 196838, 218026, 228562, 237726, 241420],
    [25735, 77048, 122556, 166878, 187170, 208740, 231200, 242365, 252074, 255987],
    [26512, 79375, 126257, 171917, 192821, 215039, 238170, 249667, 259662, 263690],
    [27313, 81772, 130070, 177109, 198642, 221527, 245348, 257184, 267473, 271619],
    [28138, 84242, 133998, 182456, 204638, 228209, 252737, 264922, 275512, 279779],
])

C5_published = np.array([
    [22233, 66564, 99586, 135522, 151887, 169169, 186990, 195770, 203355, 206398],
    [22905, 64501, 102592, 139594, 156428, 174187, 192478, 201479, 209249, 212366],
    [22195, 66449, 105688, 143784, 161096, 179340, 198105, 207328, 215285, 218474],
    [22865, 68455, 108877, 148094, 165893, 184629, 203871, 213318, 221461, 224723],
    [23555, 70523, 112161, 152527, 170822, 190056, 209778, 219448, 227777, 231112],
    [24267, 72652, 115544, 157085, 175885, 195621, 215826, 225719, 234233, 237640],
    [25735, 77048, 122521, 166462, 186279, 207020, 228179, 238510, 247385, 250932],
    [26512, 79375, 126211, 171407, 191748, 213003, 234644, 245194, 254248, 257866],
    [27313, 81772, 130010, 176486, 197356, 219126, 241247, 252014, 261246, 264932],
    [28138, 84241, 133921, 181699, 203105, 225390, 247987, 258969, 268375, 272128],
])

C6_published = np.array([
    [22233, 66528, 98933, 132211, 146418, 160735, 174776, 181433, 187052, 189273],
    [22905, 64473, 101813, 135805, 150248, 164762, 178957, 185674, 191337, 193574],
    [22195, 66413, 104764, 139462, 154134, 168836, 183176, 189948, 195652, 197903],
    [22865, 68409, 107785, 143181, 158075, 172956, 187431, 194253, 199993, 202256],
    [23555, 70464, 110876, 146960, 162068, 177119, 191718, 198586, 204358, 206632],
    [24267, 72578, 114037, 150798, 166111, 181322, 196035, 202944, 208743, 211026],
    [25735, 76931, 120483, 158539, 174229, 189725, 204633, 211606, 217447, 219744],
    [26512, 79229, 123851, 162538, 178404, 194029, 209019, 216018, 221873, 224175],
    [27313, 81591, 127286, 166587, 182619, 198360, 213422, 220441, 226307, 228611],
    [28138, 84019, 130788, 170682, 186869, 202716, 217839, 224873, 230745, 233050],
])

for name, computed, published in [
    ("C2", C2, C2_published),
    ("C3", C3, C2_published),
    ("C4", C4, C4_published),
    ("C5", C5, C5_published),
    ("C6", C6, C6_published),
]:
    deviation = np.abs(computed.values[0, 0] - published).max()
    assert deviation < 1.0, f"{name} deviates from the paper by {deviation:.2f}"
    print(f"{name}: matches the published exhibit (max deviation {deviation:.2f})")

C2: matches the published exhibit (max deviation 0.80)
C3: matches the published exhibit (max deviation 0.80)
C4: matches the published exhibit (max deviation 0.90)
C5: matches the published exhibit (max deviation 0.89)
C6: matches the published exhibit (max deviation 0.74)

### D: Calculation of Development Factors at Basic Limit

The Sahasrabuddhe estimator can be used to take a triangle at an observed limit and cost level, and restate it at another specified layer and cost level. Development factors can then be determined using the actuary's method of choice.

In [19]:
basic = cl.Sahasrabuddhe(
    means=theta_10,
    trend=T,
    observed_limit=triangle_limit,
    target_layer=(0, basic_limit),  # restate onto the basic limit
).fit(genins)

# D1: the triangle restated to exposure year 10 cost levels and basic limit.
D1 = basic.triangle_

development = cl.Development(average="volume").fit(D1)

D1

                12            24            36            48            60            72            84            96            108           120
2001  452880.743316  1.419731e+06  2.279040e+06  2.793771e+06  3.377949e+06  3.978376e+06  4.038185e+06  4.142392e+06  4.349867e+06  4.405265e+06
2002  432565.562442  1.610196e+06  2.766439e+06  4.100114e+06  4.538380e+06  4.794872e+06  5.260266e+06  5.484615e+06  5.887563e+06           NaN
2003  368295.607562  1.634013e+06  2.745402e+06  3.840400e+06  4.623710e+06  4.671635e+06  5.090015e+06  5.324756e+06           NaN           NaN
2004  382235.508706  1.741436e+06  2.636785e+06  4.330557e+06  4.539484e+06  4.811269e+06  4.902614e+06           NaN           NaN           NaN
2005  529367.653220  1.353815e+06  2.481777e+06  3.242745e+06  3.722314e+06  4.131334e+06           NaN           NaN           NaN           NaN
2006  459319.864239  1.541795e+06  2.468414e+06  3.244184e+06  3.922260e+06           NaN           NaN           NaN           NaN           NaN
2007  481989.681313  1.405036e+06  2.583136e+06  3.571424e+06           NaN           NaN           NaN           NaN           NaN           NaN
2008  381520.444823  1.504277e+06  2.968365e+06           NaN           NaN           NaN           NaN           NaN           NaN           NaN
2009  388061.909758  1.400758e+06           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN
2010  344013.993403           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN           NaN

### D2: Exposure Year 10 Incremental Basic Limit Development Factors

*Volume Weighted Averages*

In [20]:
D2 = development.ldf_
D2

         12-24     24-36     36-48     48-60     60-72     72-84     84-96    96-108   108-120
(All)  3.51141  1.714074  1.398764  1.147195  1.076226  1.056689  1.039149  1.063407  1.012736

### D3: Exposure Year 10 Cumulative Development Factors

In [21]:
D3 = development.cdf_
D3

          12-Ult    24-Ult    36-Ult    48-Ult    60-Ult    72-Ult    84-Ult   96-Ult   108-Ult
(All)  12.291862  3.500549  2.042239  1.460031  1.272696  1.182554  1.119112  1.07695  1.012736

Check the recreation of the D section against the paper.

One cell is excluded due to a typo.  The paper's
exhibit A1 has 359,840 at exposure period 8, development interval 1.  The
genins sample -- and the Taylor-Ashe triangle it comes from -- has 359,480.

In [22]:
TYPO = (7, 0)  # exposure period 8, development interval 1

D1_published = np.array(
    [
        [
            452881,
            1419731,
            2279040,
            2793772,
            3377947,
            3978376,
            4038185,
            4142394,
            4349865,
            4405265,
        ],
        [
            432566,
            1610197,
            2766439,
            4100116,
            4538378,
            4794873,
            5260266,
            5484617,
            5887561,
            None,
        ],
        [
            368296,
            1634013,
            2745402,
            3840401,
            4623708,
            4671636,
            5090015,
            5324759,
            None,
            None,
        ],
        [
            382236,
            1741436,
            2636785,
            4330559,
            4539482,
            4811270,
            4902613,
            None,
            None,
            None,
        ],
        [529368, 1353815, 2481777, 3242747, 3722312, 4131335, None, None, None, None],
        [459320, 1541795, 2468413, 3244186, 3922258, None, None, None, None, None],
        [481990, 1405037, 2583135, 3571425, None, None, None, None, None, None],
        [381903, 1504277, 2968365, None, None, None, None, None, None, None],
        [388062, 1400758, None, None, None, None, None, None, None, None],
        [344014, None, None, None, None, None, None, None, None, None],
    ],
    dtype="float64",
)

D2_published = np.array([3.511, 1.714, 1.399, 1.147, 1.076, 1.057, 1.039, 1.063, 1.013])
D3_published = np.array([
    12.291,
    3.501,
    2.042,
    1.460,
    1.273,
    1.183,
    1.119,
    1.077,
    1.013,
])

comparable = ~np.isnan(D1_published)
comparable[TYPO] = False
d1_dev = np.abs(D1.values[0, 0][comparable] - D1_published[comparable]).max()
assert d1_dev <= 3.0, f"D1 deviates from the paper by {d1_dev:.2f}"
print(
    f"D1: matches the published exhibit (max deviation {d1_dev:.2f}, 1 cell excluded)"
)

# The excluded cell: rerun it on the paper's own input and it reproduces the
# paper's own answer, which is what makes this a data typo rather than a bug.
ratio = C6.values[0, 0, -1, 0] / C5.values[0, 0][TYPO]
assert abs(359840 * ratio - D1_published[TYPO]) <= 1.0
assert abs(359480 * ratio - D1.values[0, 0][TYPO]) <= 1.0
print(
    f"    the excluded cell reconciles: paper's A1 359,840 -> {359840 * ratio:,.0f} "
    f"(paper prints {D1_published[TYPO]:,.0f}); "
    f"genins' 359,480 -> {359480 * ratio:,.0f}"
)

d2_dev = np.abs(D2.values[0, 0, 0] - D2_published).max()
assert d2_dev <= 0.0005, f"D2 deviates from the paper by {d2_dev:.6f}"
print(f"D2: matches the published exhibit (max deviation {d2_dev:.6f})")

d3_dev = np.abs(D3.values[0, 0, 0] - D3_published).max()
assert d3_dev <= 0.002, f"D3 deviates from the paper by {d3_dev:.6f}"
print(f"D3: matches the published exhibit (max deviation {d3_dev:.6f})")

D1: matches the published exhibit (max deviation 2.69, 1 cell excluded)
    the excluded cell reconciles: paper's A1 359,840 -> 381,903 (paper prints 381,903); genins' 359,480 -> 381,520
D2: matches the published exhibit (max deviation 0.000410)
D3: matches the published exhibit (max deviation 0.000862)

### E: Calculation of Development Factors by Layer

### E1: Basic Limit

In [23]:
def layer(target_layer):
    return cl.Sahasrabuddhe(
        means=theta_10,
        trend=T,
        basic_limit=basic_limit,
        target_layer=target_layer,
    ).fit(development)


E1 = layer(target_layer=(0, basic_limit)).full_cdf_
E1

            12        24        36        48        60        72        84        96        108  120
2001  12.634047  3.590447  2.192669  1.530808  1.319190  1.211265  1.132835  1.084065  1.014624  1.0
2002  12.542336  3.789059  2.179048  1.524165  1.314775  1.208512  1.131509  1.083375  1.014441  1.0
2003  13.233037  3.760646  2.165033  1.517387  1.310284  1.205719  1.130166  1.082677  1.014255  1.0
2004  13.127703  3.731209  2.150647  1.510488  1.305725  1.202890  1.128809  1.081973  1.014068  1.0
2005  13.018549  3.700779  2.135915  1.503479  1.301105  1.200030  1.127439  1.081262  1.013879  1.0
2006  12.905653  3.669393  2.120865  1.496374  1.296434  1.197144  1.126059  1.080547  1.013689  1.0
2007  12.672130  3.604778  2.090324  1.482113  1.287091  1.191387  1.123313  1.079124  1.013312  1.0
2008  12.548665  3.570795  2.074492  1.474795  1.282311  1.188450  1.121914  1.078400  1.013120  1.0
2009  12.421868  3.536034  2.058454  1.467430  1.277510  1.185504  1.120514  1.077675  1.012928  1.0
2010  12.291862  3.500549  2.042239  1.460031  1.272696  1.182554  1.119112  1.076950  1.012736  1.0

### E1 as a development pattern

In [24]:
layer(target_layer=(0, basic_limit)).cdf_

          12-Ult    24-Ult    36-Ult    48-Ult    60-Ult   72-Ult    84-Ult    96-Ult   108-Ult  120-Ult
(All)  12.291862  3.536034  2.074492  1.482113  1.296434  1.20003  1.128809  1.082677  1.014441      1.0

### E2: Basic Limit to Policy Limit

In [25]:
E2 = layer(target_layer=(basic_limit, policy_limit)).full_cdf_
E2.to_frame(origin_as_datetime=False).style.format("{:,.3f}", na_rep="")

### E3: Policy Limit to Unlimited

In [26]:
E3 = layer(target_layer=(policy_limit, np.inf)).full_cdf_
E3.to_frame(origin_as_datetime=False).style.format("{:,.3f}", na_rep="")

### E4: Limit of Data in Triangle

In [27]:
E4 = layer(target_layer=(0, triangle_limit)).full_cdf_
E4

            12        24        36        48        60        72        84        96        108  120
2001  13.777120  3.913155  2.375374  1.628523  1.386745  1.255003  1.154635  1.095575  1.017725  1.0
2002  13.759920  4.155107  2.372443  1.626736  1.385425  1.254090  1.154150  1.095312  1.017652  1.0
2003  14.608574  4.149315  2.369182  1.624764  1.383976  1.253093  1.153624  1.095027  1.017574  1.0
2004  14.585924  4.142882  2.365567  1.622597  1.382393  1.252010  1.153056  1.094720  1.017489  1.0
2005  14.560868  4.135767  2.361579  1.620228  1.380671  1.250839  1.152446  1.094391  1.017399  1.0
2006  14.533255  4.127925  2.357195  1.617647  1.378806  1.249579  1.151792  1.094040  1.017304  1.0
2007  14.470661  4.110151  2.347304  1.611906  1.374690  1.246820  1.150374  1.093281  1.017097  1.0
2008  14.434582  4.099908  2.341633  1.608661  1.372380  1.245284  1.149590  1.092863  1.016983  1.0
2009  14.395381  4.088780  2.335495  1.605183  1.369919  1.243656  1.148764  1.092423  1.016864  1.0
2010  14.352928  4.076730  2.328878  1.601471  1.367304  1.241935  1.147894  1.091962  1.016739  1.0

### E5: Unadjusted Incremental Development Factors at Limits of Data Triangle

*Volume Weighted Averages*

In [28]:
unadjusted = cl.Development(average="volume").fit(genins)

E5 = unadjusted.ldf_
E5

          12-24     24-36     36-48     48-60     60-72     72-84     84-96    96-108   108-120
(All)  3.490607  1.747333  1.457413  1.173852  1.103824  1.086269  1.053874  1.076555  1.017725

### E6: Unadjusted Cumulative Development Factors

In [29]:
E6 = unadjusted.cdf_
E6

          12-Ult    24-Ult    36-Ult    48-Ult    60-Ult    72-Ult    84-Ult    96-Ult   108-Ult
(All)  14.446577  4.138701  2.368582  1.625196  1.384499  1.254276  1.154664  1.095637  1.017725

### E7: Differences

In [30]:
import pandas as pd

last_diagonal = np.array([E4.values[0, 0, 10 - 1 - j, j] for j in range(10)])
labels = list(E6.development) + ["120-Ult"]

E7 = pd.Series(
    (np.append(E6.values[0, 0, 0], 1.0) / last_diagonal - 1) * 100, index=labels
)
E7.round(1).to_frame("difference %").T

,12-Ult,24-Ult,36-Ult,48-Ult,60-Ult,72-Ult,84-Ult,96-Ult,108-Ult,120-Ult
difference %,0.7,1.2,1.2,0.8,0.4,0.3,0.1,0.1,0.0,0.0

Check the E series against the exhibits as printed in the paper.

E2 and E3 are compared only where the paper prints a number: it writes "very
large" wherever the layer has essentially no expected loss at that age, and
those cells are non-finite or astronomically large here for the same reason.

In [31]:
VERY_LARGE = np.nan

E1_published = np.array(
    [
        [12.633, 3.590, 2.193, 1.531, 1.319, 1.211, 1.133, 1.084, 1.015, 1.000],
        [12.541, 3.789, 2.179, 1.524, 1.315, 1.209, 1.132, 1.083, 1.014, None],
        [13.232, 3.761, 2.165, 1.517, 1.310, 1.206, 1.130, 1.083, None, None],
        [13.126, 3.731, 2.151, 1.510, 1.306, 1.203, 1.129, None, None, None],
        [13.017, 3.701, 2.136, 1.503, 1.301, 1.200, None, None, None, None],
        [12.904, 3.669, 2.121, 1.496, 1.296, None, None, None, None, None],
        [12.671, 3.605, 2.090, 1.482, None, None, None, None, None, None],
        [12.547, 3.571, 2.074, None, None, None, None, None, None, None],
        [12.421, 3.536, None, None, None, None, None, None, None, None],
        [12.291, None, None, None, None, None, None, None, None, None],
    ],
    dtype="float64",
)

E2_published = np.array(
    [
        [VERY_LARGE, 652.420, 32.802, 5.924, 3.380, 2.175, 1.499, 1.257, 1.057, 1.000],
        [VERY_LARGE, 946.242, 30.374, 5.704, 3.293, 2.140, 1.488, 1.252, 1.056, None],
        [VERY_LARGE, 807.075, 28.187, 5.498, 3.210, 2.107, 1.477, 1.247, None, None],
        [VERY_LARGE, 691.561, 26.215, 5.305, 3.132, 2.075, 1.466, None, None, None],
        [VERY_LARGE, 595.239, 24.431, 5.124, 3.058, 2.044, None, None, None, None],
        [VERY_LARGE, 514.560, 22.814, 4.954, 2.987, None, None, None, None, None],
        [VERY_LARGE, 390.710, 20.042, 4.647, None, None, None, None, None, None],
        [VERY_LARGE, 341.869, 18.820, None, None, None, None, None, None, None],
        [VERY_LARGE, 300.278, None, None, None, None, None, None, None, None],
        [VERY_LARGE, None, None, None, None, None, None, None, None, None],
    ],
    dtype="float64",
)

E3_published = np.array(
    [
        [
            VERY_LARGE,
            VERY_LARGE,
            84538.278,
            279.503,
            48.056,
            11.155,
            3.254,
            1.887,
            1.183,
            1.000,
        ],
        [
            VERY_LARGE,
            VERY_LARGE,
            62192.336,
            240.423,
            43.321,
            10.464,
            3.157,
            1.857,
            1.178,
            None,
        ],
        [
            VERY_LARGE,
            VERY_LARGE,
            46166.664,
            207.723,
            39.172,
            9.835,
            3.066,
            1.829,
            None,
            None,
        ],
        [
            VERY_LARGE,
            VERY_LARGE,
            34571.138,
            180.241,
            35.524,
            9.261,
            2.979,
            None,
            None,
            None,
        ],
        [
            VERY_LARGE,
            VERY_LARGE,
            26108.458,
            157.047,
            32.309,
            8.735,
            None,
            None,
            None,
            None,
        ],
        [
            VERY_LARGE,
            VERY_LARGE,
            19880.311,
            137.391,
            29.466,
            None,
            None,
            None,
            None,
            None,
        ],
        [
            VERY_LARGE,
            VERY_LARGE,
            11880.695,
            106.724,
            None,
            None,
            None,
            None,
            None,
            None,
        ],
        [VERY_LARGE, VERY_LARGE, 9257.797, None, None, None, None, None, None, None],
        [VERY_LARGE, VERY_LARGE, None, None, None, None, None, None, None, None],
        [VERY_LARGE, None, None, None, None, None, None, None, None, None],
    ],
    dtype="float64",
)

E4_published = np.array(
    [
        [13.776, 3.913, 2.375, 1.629, 1.387, 1.255, 1.155, 1.096, 1.018, 1.000],
        [13.759, 4.155, 2.372, 1.627, 1.385, 1.254, 1.154, 1.095, 1.018, None],
        [14.607, 4.149, 2.369, 1.625, 1.384, 1.253, 1.154, 1.095, None, None],
        [14.584, 4.143, 2.366, 1.623, 1.382, 1.252, 1.153, None, None, None],
        [14.559, 4.136, 2.362, 1.620, 1.381, 1.251, None, None, None, None],
        [14.532, 4.128, 2.357, 1.618, 1.379, None, None, None, None, None],
        [14.469, 4.110, 2.347, 1.612, None, None, None, None, None, None],
        [14.433, 4.100, 2.342, None, None, None, None, None, None, None],
        [14.394, 4.089, None, None, None, None, None, None, None, None],
        [14.352, None, None, None, None, None, None, None, None, None],
    ],
    dtype="float64",
)

E5_published = np.array([3.490, 1.747, 1.457, 1.174, 1.104, 1.086, 1.054, 1.077, 1.018])
E6_published = np.array([
    14.445,
    4.139,
    2.369,
    1.625,
    1.384,
    1.254,
    1.155,
    1.096,
    1.018,
])
E7_published = np.array([0.7, 1.2, 1.2, 0.8, 0.4, 0.3, 0.1, 0.1, 0.0, 0.0])

for name, computed, published, tol in [
    ("E1", E1.values[0, 0], E1_published, 0.002),
    ("E2", E2.values[0, 0], E2_published, 0.002),
    ("E3", E3.values[0, 0], E3_published, 0.010),
    ("E4", E4.values[0, 0], E4_published, 0.002),
]:
    comparable = np.isfinite(published)
    # E3's largest printed factor carries five significant figures, so compare
    # it relatively rather than absolutely.
    deviation = np.abs(computed[comparable] / published[comparable] - 1).max()
    assert deviation <= tol, f"{name} deviates from the paper by {deviation:.5f}"
    print(
        f"{name}: matches the published exhibit "
        f"(max relative deviation {deviation:.5f}, {comparable.sum()} cells)"
    )

E1: matches the published exhibit (max relative deviation 0.00043, 55 cells)
E2: matches the published exhibit (max relative deviation 0.00038, 45 cells)
E3: matches the published exhibit (max relative deviation 0.00039, 36 cells)
E4: matches the published exhibit (max relative deviation 0.00039, 55 cells)

E5 and E6 are fitted on the raw triangle, so the A1 typo found in the D
series reaches them too -- and only through the 12-24 factor, whose
denominator includes exposure period 8 at age 12.  The first factor is
therefore checked by reconciliation rather than by tolerance.

In [32]:
raw = genins.values[0, 0]
paper_ldf_12_24 = np.nansum(raw[:9, 1]) / (np.nansum(raw[:9, 0]) + (359840 - 359480))
assert abs(paper_ldf_12_24 - E5_published[0]) <= 0.0005
print(
    f"E5: first factor reconciles to the paper's A1 "
    f"({paper_ldf_12_24:.5f} vs published {E5_published[0]:.3f}); "
    f"genins gives {E5.values[0, 0, 0, 0]:.5f}"
)

for name, computed, published, tol, skip in [
    ("E5", E5.values[0, 0, 0], E5_published, 0.0005, 1),
    ("E6", E6.values[0, 0, 0], E6_published, 0.002, 0),
    ("E7", E7.values, E7_published, 0.05, 0),
]:
    deviation = np.abs(computed[skip:] - published[skip:]).max()
    assert deviation <= tol, f"{name} deviates from the paper by {deviation:.5f}"
    note = " (first factor excluded)" if skip else ""
    print(
        f"{name}: matches the published exhibit (max deviation {deviation:.5f}){note}"
    )

E5: first factor reconciles to the paper's A1 (3.49023 vs published 3.490); genins gives 3.49061
E5: matches the published exhibit (max deviation 0.00044) (first factor excluded)
E6: matches the published exhibit (max deviation 0.00158)
E7: matches the published exhibit (max deviation 0.04912)