# Chapter 13 - Berquist-Sherman Techniques

In [2]:
import numpy as np
import pandas as pd
import chainladder as cl
from IPython.display import display

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)

# Helper functions, skip to the next section for actual exhibits
# def to_series(tri):
#     s = tri.to_frame(origin_as_datetime=False).iloc[:, 0]
#     # s.index = [int(getattr(i, "year", i)) for i in s.index]
#     return s


def to_triangle_frame(tri):
    df = tri.to_frame(origin_as_datetime=False)
    # df.index = [int(getattr(i, "year", i)) for i in df.index]
    return df


def to_link_ratio_frame(tri, decimals=3):
    df = np.round(tri.link_ratio.to_frame(origin_as_datetime=False), decimals)
    df.index = [int(getattr(i, "year", i)) for i in df.index]
    return df

## P294 (Exhibit I Sheet 1)

In [6]:
mm = cl.load_sample("friedland_med_mal")
reported = mm["Reported Claims"]

# Part 1
exhibit_i_s1_tri = to_triangle_frame(reported)
display(exhibit_i_s1_tri)

# Part 2 
exhibit_i_s1_lr = to_link_ratio_frame(reported)
display(exhibit_i_s1_lr)

# Part 3
dev_reported = cl.Development(average="simple").fit(reported)
avg_ldf = np.round(dev_reported.ldf_.to_frame(origin_as_datetime=False).values.flatten(), 3)
exhibit_i_s1_avg = pd.Series(
    avg_ldf,
    index=["12-24", "24-36", "36-48", "48-60", "60-72", "72-84", "84-96"],
    name="Simple Average All Years",
)
display(exhibit_i_s1_avg.to_frame().T)

# Part 4
selected_ldf = {
    12: 2.532,
    24: 1.921,
    36: 1.503,
    48: 1.170,
    60: 1.206,
    72: 1.052,
    84: 1.027,
    96: 1.000,
}
# or this
selected_ldf = dict(zip([12, 24, 36, 48, 60, 72, 84, 96], [*avg_ldf, 1.000]))

reported_dev = cl.DevelopmentConstant(patterns=selected_ldf, style="ldf").fit(reported)
cdf = np.round(reported_dev.cdf_.to_frame().values.flatten(), 3)
pct_reported = np.round(1.0 / cdf, 3)

exhibit_i_s1_sel = pd.DataFrame(
    {
        "Selected": list(selected_ldf.values()),
        "CDF to Ultimate": cdf,
        "Percent Reported": pct_reported,
    },
    index=["12-24", "24-36", "36-48", "48-60", "60-72", "72-84", "84-96", "96-108"],
)
display(exhibit_i_s1_sel.T)

              12          24          36          48          60          72          84          96
1969   2897000.0   5160000.0  10714000.0  15228000.0  16611000.0  20899000.0  22892000.0  23506000.0
1970   4828000.0  10707000.0  16907000.0  22840000.0  26211000.0  31970000.0  32216000.0         NaN
1971   5455000.0  11941000.0  20733000.0  30928000.0  42395000.0  48377000.0         NaN         NaN
1972   8732000.0  18633000.0  32143000.0  57196000.0  61163000.0         NaN         NaN         NaN
1973  11228000.0  19967000.0  50143000.0  73733000.0         NaN         NaN         NaN         NaN
1974   8706000.0  33459000.0  63477000.0         NaN         NaN         NaN         NaN         NaN
1975  12928000.0  48904000.0         NaN         NaN         NaN         NaN         NaN         NaN
1976  15791000.0         NaN         NaN         NaN         NaN         NaN         NaN         NaN

      12-24  24-36  36-48  48-60  60-72  72-84  84-96
1969  1.781  2.076  1.421  1.091  1.258  1.095  1.027
1970  2.218  1.579  1.351  1.148  1.220  1.008    NaN
1971  2.189  1.736  1.492  1.371  1.141    NaN    NaN
1972  2.134  1.725  1.779  1.069    NaN    NaN    NaN
1973  1.778  2.511  1.470    NaN    NaN    NaN    NaN
1974  3.843  1.897    NaN    NaN    NaN    NaN    NaN
1975  3.783    NaN    NaN    NaN    NaN    NaN    NaN

                          12-24  24-36  36-48  48-60  60-72  72-84  84-96
Simple Average All Years  2.532  1.921  1.503   1.17  1.206  1.052  1.027

                   12-24  24-36  36-48  48-60  60-72  72-84  84-96  96-108
Selected           2.532  1.921  1.503  1.170  1.206  1.052  1.027     1.0
CDF to Ultimate   11.145  4.402  2.291  1.524  1.303  1.080  1.027     1.0
Percent Reported   0.090  0.227  0.436  0.656  0.767  0.926  0.974     1.0

## P295 (Exhibit I Sheet 2)

In [ ]:
paid = mm["Paid Claims"]

# Part 1
exhibit_i_s2_tri = to_triangle_frame(paid)
display(exhibit_i_s2_tri)

# Part 2
exhibit_i_s2_lr = to_link_ratio_frame(paid)
display(exhibit_i_s2_lr)

# Part 3
dev_paid = cl.Development(average="volume").fit(paid)
avg_ldf = np.round(dev_paid.ldf_.to_frame().values.flatten(), 3)
exhibit_i_s2_avg = pd.Series(
    avg_ldf,
    index=["12-24", "24-36", "36-48", "48-60", "60-72", "72-84", "84-96"],
    name="Volume-weighted Average All Years",
)
display(exhibit_i_s2_avg.to_frame().T)

# Part 4
selected_ldf = {
    12: 6.185,
    24: 3.709,
    36: 2.455,
    48: 1.952,
    60: 1.718,
    72: 1.407,
    84: 1.251,
    96: 1.486,
}
# or this
selected_ldf = dict(zip([12, 24, 36, 48, 60, 72, 84, 96], [*avg_ldf, 1.486]))

paid_dev = cl.DevelopmentConstant(patterns=selected_ldf, style="ldf").fit(paid)
cdf = np.round(paid_dev.cdf_.to_frame(origin_as_datetime=False).values.flatten(), 3)
pct_paid = np.round(1.0 / cdf, 3)

exhibit_i_s2_sel = pd.DataFrame(
    {
        "Selected": list(selected_ldf.values()),
        "CDF to Ultimate": cdf,
        "Percent Paid": pct_paid,
    },
    index=["12-24", "24-36", "36-48", "48-60", "60-72", "72-84", "84-96", "96-108"],
)
display(exhibit_i_s2_sel.T)

            12         24         36          48          60          72          84          96
1969  125000.0   406000.0  1443000.0   2986000.0   4467000.0   8179000.0  12638000.0  15815000.0
1970   43000.0   529000.0  2016000.0   3641000.0   7523000.0  14295000.0  18983000.0         NaN
1971  295000.0  1147000.0  2479000.0   5071000.0  11399000.0  17707000.0         NaN         NaN
1972   50000.0   786000.0  3810000.0   9771000.0  18518000.0         NaN         NaN         NaN
1973  213000.0   833000.0  3599000.0  11292000.0         NaN         NaN         NaN         NaN
1974  172000.0  1587000.0  6267000.0         NaN         NaN         NaN         NaN         NaN
1975  210000.0  1565000.0        NaN         NaN         NaN         NaN         NaN         NaN
1976  209000.0        NaN        NaN         NaN         NaN         NaN         NaN         NaN

       12-24  24-36  36-48  48-60  60-72  72-84  84-96
1969   3.248  3.554  2.069  1.496  1.831  1.545  1.251
1970  12.302  3.811  1.806  2.066  1.900  1.328    NaN
1971   3.888  2.161  2.046  2.248  1.553    NaN    NaN
1972  15.720  4.847  2.565  1.895    NaN    NaN    NaN
1973   3.911  4.321  3.138    NaN    NaN    NaN    NaN
1974   9.227  3.949    NaN    NaN    NaN    NaN    NaN
1975   7.452    NaN    NaN    NaN    NaN    NaN    NaN

                                   12-24  24-36  36-48  48-60  60-72  72-84  84-96
Volume-weighted Average All Years  6.185  3.709  2.455  1.952  1.718  1.407  1.251

                   12-24   24-36   36-48  48-60  60-72  72-84  84-96  96-108
Selected           6.185   3.709   2.455  1.952  1.718  1.407  1.251   1.486
CDF to Ultimate  493.993  79.870  21.534  8.771  4.494  2.616  1.859   1.486
Percent Paid       0.002   0.013   0.046  0.114  0.223  0.382  0.538   0.673