In [124]:
import pandas as pd
import chainladder as cl
import numpy as np

In [125]:
# Page 140, Exhibit I Sheet 1 Columns 1-2
auto_bi = cl.load_sample("friedland_auto_bi_insurer")
auto_bi["Reported Claims"].latest_diagonal

            2008
2000  10000000.0
2001   8000000.0
2002   9400000.0
2003  15600000.0
2004  16500000.0
2005  18500000.0
2006  16500000.0
2007  14000000.0
2008   8700000.0

In [126]:
# Page 140, Exhibit I Sheet 1 Column 3
auto_bi["Paid Claims"].latest_diagonal

            2008
2000   9500000.0
2001   7200000.0
2002   7600000.0
2003   7800000.0
2004  11200000.0
2005  10200000.0
2006   6000000.0
2007   3000000.0
2008    750000.0

In [127]:
# Page 140, Exhibit I Sheet 1 Columns 4-5
# Direct age(in months): value representation per LOB
reported_pattern = {12: 4.0, 24: 2.9, 36: 1.8, 48: 1.4, 60: 1.2, 72: 1.1, 84: 1.03, 96: 1.02, 108: 1.005}
paid_pattern = {12: 90.0, 24: 15.0, 36: 5.0, 48: 2.5, 60: 1.75, 72: 1.35, 84: 1.25, 96: 1.15, 108: 1.05}

In [128]:
# Page 140, Exhibit I Sheet 1 Column 6
Reported_BI = cl.DevelopmentConstant(patterns=reported_pattern, style='cdf').fit_transform(auto_bi["Reported Claims"])
reported_ultimate = cl.Chainladder().fit(Reported_BI).ultimate_
reported_ultimate

            2261
2000  10050000.0
2001   8160000.0
2002   9682000.0
2003  17160000.0
2004  19800000.0
2005  25900000.0
2006  29700000.0
2007  40600000.0
2008  34800000.0

In [129]:
# Page 140, Exhibit I Sheet 1 Column 7
Paid_BI = cl.DevelopmentConstant(patterns=paid_pattern, style='cdf').fit_transform(auto_bi["Paid Claims"])
paid_ultimate = cl.Chainladder().fit(Paid_BI).ultimate_
paid_ultimate

            2261
2000   9975000.0
2001   8280000.0
2002   9500000.0
2003  10530000.0
2004  19600000.0
2005  25500000.0
2006  30000000.0
2007  45000000.0
2008  67500000.0

In [130]:
# Page 140, Exhibit I Sheet 1 Column 8
inital_selected_ultiamte_claims = (reported_ultimate + paid_ultimate)/2
inital_selected_ultiamte_claims

            2261
2000  10012500.0
2001   8220000.0
2002   9591000.0
2003  13845000.0
2004  19700000.0
2005  25700000.0
2006  29850000.0
2007  42800000.0
2008  51150000.0

In [131]:
# Page 140, Exhibit I Sheet 1 Column 9
auto_bi["Earned Premium"].latest_diagonal

            2008
2000  24000000.0
2001  18000000.0
2002  19000000.0
2003  23000000.0
2004  32000000.0
2005  47000000.0
2006  50000000.0
2007  57000000.0
2008  62000000.0

In [132]:
# Page 140, Exhibit I Sheet 1 Column 10
trend_factors = np.round(cl.Trend(trends=[0.145], dates=[("2008-12-31", "2000-01-01")]).fit(auto_bi["Earned Premium"]).trend_.latest_diagonal,3)
trend_factors

       2008
2000  2.954
2001  2.580
2002  2.253
2003  1.968
2004  1.719
2005  1.501
2006  1.311
2007  1.145
2008  1.000

In [133]:
# Page 140, Exhibit I Sheet 1 Column 11
tort_factors = [0.670, 0.670, 0.670, 0.670, 0.750, 1.0, 1.0, 1.0, 1.0]
tort_factors

[0.67, 0.67, 0.67, 0.67, 0.75, 1.0, 1.0, 1.0, 1.0]

In [134]:
# Page 140, Exhibit I Sheet 1 Column 12
trended_adj_ultimate_claims = trend_factors * inital_selected_ultiamte_claims * np.array(tort_factors).reshape(1, 1, -1, 1)
trended_adj_ultimate_claims

             2008
2000  19816539.75
2001  14209092.00
2002  14477710.41
2003  18255463.20
2004  25398225.00
2005  38575700.00
2006  39133350.00
2007  49006000.00
2008  51150000.00

In [135]:
# Page 140, Exhibit I Sheet 1 Column 13
trended_adjusted_claim_ratio = np.round(trended_adj_ultimate_claims/auto_bi["Earned Premium"].latest_diagonal,2)
trended_adjusted_claim_ratio

      2008
2000  0.83
2001  0.79
2002  0.76
2003  0.79
2004  0.79
2005  0.82
2006  0.78
2007  0.86
2008  0.82

In [136]:
# Page 140, Exhibit I Sheet 1 Item 14
print("Average 2000 to 2005:", np.round(trended_adjusted_claim_ratio.iloc[:, :, 0:6, :].mean(),3))
loss_ratios_00_05 = trended_adjusted_claim_ratio.iloc[:, :, 0:6, :].values.flatten()
print("Average 2000 to 2005 Ex High Ex Low:", np.round((loss_ratios_00_05.sum() - loss_ratios_00_05.max() - loss_ratios_00_05.min()) / (len(loss_ratios_00_05) - 2), 3))
print("Average 2001 to 2006:", np.round(trended_adjusted_claim_ratio.iloc[:, :, 1:7, :].mean(),3))
loss_ratios_01_06 = trended_adjusted_claim_ratio.iloc[:, :, 1:7, :].values.flatten()
print("Average 2000 to 2005 Ex High Ex Low:", np.round((loss_ratios_01_06.sum() - loss_ratios_01_06.max() - loss_ratios_01_06.min()) / (len(loss_ratios_01_06) - 2), 3)) # small rounding error due to python's 64 bit float storage

Average 2000 to 2005: 0.797
Average 2000 to 2005 Ex High Ex Low: 0.798
Average 2001 to 2006: 0.788
Average 2000 to 2005 Ex High Ex Low: 0.787

In [137]:
# Page 140, Exhibit I Item 15
selected_claim_ratio = 0.80
selected_claim_ratio

0.8

In [138]:
# Page 140, Exhibit I Item 16
earned_premium = auto_bi["Earned Premium"].loc[:, :, "2008", :].latest_diagonal
exlected_claims_2008 = earned_premium * selected_claim_ratio
exlected_claims_2008

np.float64(49600000.0)

In [139]:
# Page 140, Exhibit I Item 17
print("Total Unpaid Claims:", exlected_claims_2008 - auto_bi["Paid Claims"].loc[:, :, "2008", :].latest_diagonal)
print("Total IBNR:", exlected_claims_2008 - auto_bi["Reported Claims"].loc[:, :, "2008", :].latest_diagonal)

Total Unpaid Claims: 48850000.0
Total IBNR: 40900000.0

In [140]:
# Page 141, Exhibit I Sheet 2, columns 1-2
friedland_gl_self_insurer = cl.load_sample("friedland_gl_self_insurer")
friedland_gl_self_insurer["Reported Claims"].latest_diagonal

           2008
1998   900000.0
1999  1200000.0
2000  1300000.0
2001  1800000.0
2002  1450000.0
2003  1400000.0
2004  2400000.0
2005  1800000.0
2006  1500000.0
2007  1200000.0
2008   600000.0

In [141]:
# Page 141, Exhibit I Sheet 2, column 3
friedland_gl_self_insurer["Paid Claims"].latest_diagonal

           2008
1998   890000.0
1999  1170000.0
2000  1265000.0
2001  1600000.0
2002  1200000.0
2003  1050000.0
2004   900000.0
2005   860000.0
2006   525000.0
2007   750000.0
2008   170000.0

In [142]:
# Page 4, Exhibit I Sheet 2 Columns 4-5
reported_pattern = {12: 3.104, 24: 1.940, 36: 1.616, 48: 1.394, 60: 1.244, 72: 1.131, 84: 1.077, 96: 1.051, 108: 1.030, 120: 1.020, 132: 1.015}
paid_pattern = {12: 20.373, 24: 5.093, 36: 3.183, 48: 2.274, 60: 1.749, 72: 1.489, 84: 1.306, 96: 1.187, 108: 1.109, 120: 1.067, 132: 1.046}

In [143]:
# Page 141, Exhibit I Sheet 2 Columns 6
reported = cl.DevelopmentConstant(patterns=reported_pattern, style='cdf').fit_transform(friedland_gl_self_insurer["Reported Claims"])
reported_ultimate = cl.Chainladder().fit(reported).ultimate_
reported_ultimate

           2261
1998   913500.0
1999  1224000.0
2000  1339000.0
2001  1891800.0
2002  1561650.0
2003  1583400.0
2004  2985600.0
2005  2509200.0
2006  2424000.0
2007  2328000.0
2008  1862400.0

In [144]:
# Page 141, Exhibit I Sheet 2 Columns 7
paid = cl.DevelopmentConstant(patterns=paid_pattern, style='cdf').fit_transform(friedland_gl_self_insurer["Paid Claims"])
paid_ultimate = cl.Chainladder().fit(paid).ultimate_
paid_ultimate

           2261
1998   930940.0
1999  1248390.0
2000  1402885.0
2001  1899200.0
2002  1567200.0
2003  1563450.0
2004  1574100.0
2005  1955640.0
2006  1671075.0
2007  3819750.0
2008  3463410.0

In [145]:
# Page 141, Exhibit I Sheet 2 Columns 8
selected_ultimate = (reported_ultimate + paid_ultimate)/2
selected_ultimate

           2261
1998   922220.0
1999  1236195.0
2000  1370942.5
2001  1895500.0
2002  1564425.0
2003  1573425.0
2004  2279850.0
2005  2232420.0
2006  2047537.5
2007  3073875.0
2008  2662905.0

In [146]:
# Page 141, Exhibit I Sheet 2 Columns 9
population = friedland_gl_self_insurer["Population"].loc[:, :, "2008", :].latest_diagonal
population

          2008
1998  709000.0
1999  724000.0
2000  736000.0
2001  740000.0
2002  750000.0
2003  760000.0
2004  770000.0
2005  775000.0
2006  780000.0
2007  785000.0
2008  790000.0

In [147]:
# Page 141, Exhibit I Sheet 2 Column 10
trend_factors = np.round(cl.Trend(trends=[0.075], dates=[("2008-12-31", "1998-01-01")]).fit(friedland_gl_self_insurer["Population"]).trend_.latest_diagonal,3)
trend_factors

       2008
1998  2.061
1999  1.917
2000  1.783
2001  1.659
2002  1.543
2003  1.436
2004  1.335
2005  1.242
2006  1.156
2007  1.075
2008  1.000

In [152]:
# Page 141, Exhibit I Sheet 2 Column 11
trended_adj_ultimate_claims = selected_ultimate * trend_factors
trended_adj_ultimate_claims

              2261
1998  1.900695e+06
1999  2.369786e+06
2000  2.444390e+06
2001  3.144634e+06
2002  2.413908e+06
2003  2.259438e+06
2004  3.043600e+06
2005  2.772666e+06
2006  2.366953e+06
2007  3.304416e+06
2008  2.662905e+06

In [155]:
# Page 141, Exhibit I Sheet 2 Column 12
trended_pure_premium = np.round(trended_adj_ultimate_claims / population, 2)
trended_pure_premium

      2261
1998  2.68
1999  3.27
2000  3.32
2001  4.25
2002  3.22
2003  2.97
2004  3.95
2005  3.58
2006  3.03
2007  4.21
2008  3.37

In [165]:
# Page 141, Exhibit I Sheet 2 Item 13
print("Average 2000 to 2005:", np.round(trended_pure_premium.iloc[:, :, 2:8, :].mean(),2))
loss_ratios_00_05 = trended_pure_premium.iloc[:, :, 2:8, :].values.flatten()
print("Average 2000 to 2005 Ex High Ex Low:", np.round((loss_ratios_00_05.sum() - loss_ratios_00_05.max() - loss_ratios_00_05.min()) / (len(loss_ratios_00_05) - 2), 2))
print("Average 2001 to 2006:", np.round(trended_pure_premium.iloc[:, :, 3:9, :].mean(),2))
loss_ratios_01_06 = trended_pure_premium.iloc[:, :, 3:9, :].values.flatten()
print("Average 2001 to 2006 Ex High Ex Low:", np.round((loss_ratios_01_06.sum() - loss_ratios_01_06.max() - loss_ratios_01_06.min()) / (len(loss_ratios_01_06) - 2), 2)) # small rounding error due to python's 64 bit float storage

Average 2000 to 2005: 3.55
Average 2000 to 2005 Ex High Ex Low: 3.52
Average 2001 to 2006: 3.5
Average 2001 to 2006 Ex High Ex Low: 3.44

In [167]:
# Page 141, Exhibit I Sheet 2 Item 14
selected_pure_premium = 3.50
selected_pure_premium

3.5

In [186]:
# Page 141, Exhibit I Sheet 2 Item 15

expected_claims_2008 = selected_pure_premium * population.loc[:, :, "2008", :].latest_diagonal
expected_claims_2008

np.float64(2765000.0)

In [ ]:
# Page 141, Exhibit I Item 16
print("Total Unpaid Claims:", exlected_claims_2008 - auto_bi["Paid Claims"].loc[:, :, "2008", :].latest_diagonal)
print("Total IBNR:", exlected_claims_2008 - auto_bi["Reported Claims"].loc[:, :, "2008", :].latest_diagonal)

In [150]:
assert False

AssertionError:

In [ ]:
# Page 142, Exhibit II Sheet 1, columns 1-2
friedland_us_industry_auto = cl.load_sample("friedland_us_industry_auto")
friedland_us_industry_auto["Reported Claims"].latest_diagonal

            2007
1998  47742304.0
1999  51185767.0
2000  54837929.0
2001  56299562.0
2002  58592712.0
2003  57565344.0
2004  56976657.0
2005  56786410.0
2006  54641339.0
2007  48853563.0

In [ ]:
# Page 142, Exhibit II Sheet 1, columns 3
friedland_us_industry_auto["Paid Claims"].latest_diagonal

            2007
1998  47644187.0
1999  51000534.0
2000  54533225.0
2001  55878421.0
2002  57807215.0
2003  55930654.0
2004  53774672.0
2005  50644994.0
2006  43606497.0
2007  27229969.0

In [ ]:
# Page 142, Exhibit II Sheet 1, columns 4-5
reported_pattern = {12: 1.292, 24: 1.110, 36: 1.051, 48: 1.023, 60: 1.011, 72: 1.006, 84: 1.003, 96: 1.001, 108: 1.000, 120: 1.000}
paid_pattern = {12: 2.390, 24: 1.404, 36: 1.184, 48: 1.085, 60: 1.040, 72: 1.020, 84: 1.011, 96: 1.006, 108: 1.004, 120: 1.002}

In [ ]:
# Page 142, Exhibit II Sheet 1, column 6
reported_ultimate = cl.Chainladder().fit(cl.DevelopmentConstant(patterns=reported_pattern, style='cdf').fit_transform(friedland_us_industry_auto["Reported Claims"])).ultimate_
reported_ultimate

              2261
1998  4.774230e+07
1999  5.118577e+07
2000  5.489277e+07
2001  5.646846e+07
2002  5.894427e+07
2003  5.819856e+07
2004  5.828712e+07
2005  5.968252e+07
2006  6.065189e+07
2007  6.311880e+07

In [ ]:
# Page 142, Exhibit II Sheet 1, column 7
paid_ultimate = cl.Chainladder().fit(cl.DevelopmentConstant(patterns=paid_pattern, style='cdf').fit_transform(friedland_us_industry_auto["Paid Claims"])).ultimate_
paid_ultimate

              2261
1998  4.773948e+07
1999  5.120454e+07
2000  5.486042e+07
2001  5.649308e+07
2002  5.896336e+07
2003  5.816788e+07
2004  5.834552e+07
2005  5.996367e+07
2006  6.122352e+07
2007  6.507963e+07

In [ ]:
# Page 142, Exhibit II Sheet 1, column 8
selected_ultimate = (reported_ultimate + paid_ultimate)/2
selected_ultimate

              2261
1998  4.774089e+07
1999  5.119515e+07
2000  5.487660e+07
2001  5.648077e+07
2002  5.895381e+07
2003  5.818322e+07
2004  5.831632e+07
2005  5.982309e+07
2006  6.093770e+07
2007  6.409921e+07

In [ ]:
# Page 142, Exhibit II Sheet 1, column 9
earned_premium =friedland_us_industry_auto["Earned Premium"].latest_diagonal
earned_premium

            2007
1998  68574209.0
1999  68544981.0
2000  68907977.0
2001  72544955.0
2002  79228887.0
2003  86643542.0
2004  91763523.0
2005  94115312.0
2006  95272279.0
2007  95176240.0

In [ ]:
# Page 142, Exhibit II Sheet 1, column 10
np.round(selected_ultimate / earned_premium, 3)

       2261
1998  0.696
1999  0.747
2000  0.796
2001  0.779
2002  0.744
2003  0.672
2004  0.636
2005  0.636
2006  0.640
2007  0.673

In [ ]:
# Page 142, Exhibit II Sheet 1, column 11
selected_claim_ratio = [0.75, 0.75, 0.75, 0.75, 0.75, 0.65, 0.65, 0.65, 0.65, 0.65]
selected_claim_ratio

[0.75, 0.75, 0.75, 0.75, 0.75, 0.65, 0.65, 0.65, 0.65, 0.65]

In [ ]:
# Page 142, Exhibit II Sheet 1, column 12
expected_claims = earned_premium * np.array(selected_claim_ratio).reshape(1, 1, -1, 1)
expected_claims

             2007
1998  51430656.75
1999  51408735.75
2000  51680982.75
2001  54408716.25
2002  59421665.25
2003  56318302.30
2004  59646289.95
2005  61174952.80
2006  61926981.35
2007  61864556.00

In [ ]:
# Page 143, Exhibit II Sheet 2, columns 1-2
print(friedland_us_industry_auto["Reported Claims"].latest_diagonal)
print("Total:", friedland_us_industry_auto["Reported Claims"].latest_diagonal.sum())

            2007
1998  47742304.0
1999  51185767.0
2000  54837929.0
2001  56299562.0
2002  58592712.0
2003  57565344.0
2004  56976657.0
2005  56786410.0
2006  54641339.0
2007  48853563.0
Total: 543481587.0

In [ ]:
# Page 143, Exhibit II Sheet 2, column 3
print(friedland_us_industry_auto["Paid Claims"].latest_diagonal)
print("Total:", friedland_us_industry_auto["Paid Claims"].latest_diagonal.sum())

            2007
1998  47644187.0
1999  51000534.0
2000  54533225.0
2001  55878421.0
2002  57807215.0
2003  55930654.0
2004  53774672.0
2005  50644994.0
2006  43606497.0
2007  27229969.0
Total: 498050368.0

In [ ]:
# Page 143, Exhibit II Sheet 2, column 4
print(np.round(expected_claims, 0))
print("Total:", np.round(expected_claims.sum(), 0))

            2007
1998  51430657.0
1999  51408736.0
2000  51680983.0
2001  54408716.0
2002  59421665.0
2003  56318302.0
2004  59646290.0
2005  61174953.0
2006  61926981.0
2007  61864556.0
Total: 569281839.0

In [ ]:
# Page 143, Exhibit II Sheet 2, column 5
case_outstanding = friedland_us_industry_auto["Reported Claims"].latest_diagonal - friedland_us_industry_auto["Paid Claims"].latest_diagonal
print(case_outstanding)
print("Total:", case_outstanding.sum())

            2007
1998     98117.0
1999    185233.0
2000    304704.0
2001    421141.0
2002    785497.0
2003   1634690.0
2004   3201985.0
2005   6141416.0
2006  11034842.0
2007  21623594.0
Total: 45431219.0