# Chapter 13 - Berquist-Sherman Techniques

In [33]:
import numpy as np
import pandas as pd
import chainladder as cl
import matplotlib.pyplot as plt
from IPython.display import display

## P294 (Exhibit I Sheet 1)

In [ ]:
mm = cl.load_sample("friedland_med_mal")
reported = mm["Reported Claims"]

# Part 1
exhibit_i_s1_tri = reported.to_frame(origin_as_datetime=False)
display(exhibit_i_s1_tri)

# Part 2 
display(np.round(reported.link_ratio.to_frame(origin_as_datetime=False), 3))

# Part 3
dev_reported = cl.Development(average="simple").fit(reported)
display(np.round(dev_reported.ldf_.to_frame(), 3))

# Part 4
selected_ldf = {
    12: 2.532,
    24: 1.921,
    36: 1.503,
    48: 1.170,
    60: 1.206,
    72: 1.052,
    84: 1.027,
    96: 1.000,
}
# or this
avg_ldf = np.round(dev_reported.ldf_.to_frame().values.flatten(), 3)
selected_ldf = dict(zip([12, 24, 36, 48, 60, 72, 84, 96], [*avg_ldf, 1.000]))

reported_dev = cl.DevelopmentConstant(patterns=selected_ldf, style="ldf").fit(reported)
cdf = np.round(reported_dev.cdf_.to_frame().values.flatten(), 3) # it's unclear why the text shows different CDFs here, not reconciling using rounded nor unroudned values
pct_reported = np.round(1.0 / cdf, 3)

exhibit_i_s1_sel = pd.DataFrame(
    {
        "Selected": list(selected_ldf.values()),
        "CDF to Ultimate": cdf,
        "Percent Reported": pct_reported,
    },
    index=["12-24", "24-36", "36-48", "48-60", "60-72", "72-84", "84-96", "96-108"],
)
display(exhibit_i_s1_sel.T)

              12          24          36          48          60          72          84          96
1969   2897000.0   5160000.0  10714000.0  15228000.0  16611000.0  20899000.0  22892000.0  23506000.0
1970   4828000.0  10707000.0  16907000.0  22840000.0  26211000.0  31970000.0  32216000.0         NaN
1971   5455000.0  11941000.0  20733000.0  30928000.0  42395000.0  48377000.0         NaN         NaN
1972   8732000.0  18633000.0  32143000.0  57196000.0  61163000.0         NaN         NaN         NaN
1973  11228000.0  19967000.0  50143000.0  73733000.0         NaN         NaN         NaN         NaN
1974   8706000.0  33459000.0  63477000.0         NaN         NaN         NaN         NaN         NaN
1975  12928000.0  48904000.0         NaN         NaN         NaN         NaN         NaN         NaN
1976  15791000.0         NaN         NaN         NaN         NaN         NaN         NaN         NaN

      12-24  24-36  36-48  48-60  60-72  72-84  84-96
1969  1.781  2.076  1.421  1.091  1.258  1.095  1.027
1970  2.218  1.579  1.351  1.148  1.220  1.008    NaN
1971  2.189  1.736  1.492  1.371  1.141    NaN    NaN
1972  2.134  1.725  1.779  1.069    NaN    NaN    NaN
1973  1.778  2.511  1.470    NaN    NaN    NaN    NaN
1974  3.843  1.897    NaN    NaN    NaN    NaN    NaN
1975  3.783    NaN    NaN    NaN    NaN    NaN    NaN

       12-24  24-36  36-48  48-60  60-72  72-84  84-96
(All)  2.532  1.921  1.503   1.17  1.206  1.052  1.027

                   12-24  24-36  36-48  48-60  60-72  72-84  84-96  96-108
Selected           2.532  1.921  1.503  1.170  1.206  1.052  1.027     1.0
CDF to Ultimate   11.145  4.402  2.291  1.524  1.303  1.080  1.027     1.0
Percent Reported   0.090  0.227  0.436  0.656  0.767  0.926  0.974     1.0

## P295 (Exhibit I Sheet 2)

In [54]:
paid = mm["Paid Claims"]

# Part 1
exhibit_i_s2_tri = paid.to_frame(origin_as_datetime=False)
display(exhibit_i_s2_tri)

# Part 2
display(np.round(paid.link_ratio.to_frame(origin_as_datetime=False), decimals=3))

# Part 3
dev_paid = cl.Development(average="volume").fit(paid)
avg_ldf = np.round(dev_paid.ldf_.to_frame(origin_as_datetime=False).values.flatten(), 3)
display(np.round(dev_paid.ldf_.to_frame(), 3))

# Part 4
selected_ldf = {
    12: 6.185,
    24: 3.709,
    36: 2.455,
    48: 1.952,
    60: 1.718,
    72: 1.407,
    84: 1.251,
    96: 1.486,
}
# or this
selected_ldf = dict(zip([12, 24, 36, 48, 60, 72, 84, 96], [*avg_ldf, 1.486]))

paid_dev = cl.DevelopmentConstant(patterns=selected_ldf, style="ldf").fit(paid)
cdf = np.round(paid_dev.cdf_.to_frame(origin_as_datetime=False).values.flatten(), 3)
pct_paid = np.round(1.0 / cdf, 3)

exhibit_i_s2_sel = pd.DataFrame(
    {
        "Selected": list(selected_ldf.values()),
        "CDF to Ultimate": cdf,
        "Percent Paid": pct_paid,
    },
    index=["12-24", "24-36", "36-48", "48-60", "60-72", "72-84", "84-96", "96-108"],
)
display(exhibit_i_s2_sel.T)

            12         24         36          48          60          72          84          96
1969  125000.0   406000.0  1443000.0   2986000.0   4467000.0   8179000.0  12638000.0  15815000.0
1970   43000.0   529000.0  2016000.0   3641000.0   7523000.0  14295000.0  18983000.0         NaN
1971  295000.0  1147000.0  2479000.0   5071000.0  11399000.0  17707000.0         NaN         NaN
1972   50000.0   786000.0  3810000.0   9771000.0  18518000.0         NaN         NaN         NaN
1973  213000.0   833000.0  3599000.0  11292000.0         NaN         NaN         NaN         NaN
1974  172000.0  1587000.0  6267000.0         NaN         NaN         NaN         NaN         NaN
1975  210000.0  1565000.0        NaN         NaN         NaN         NaN         NaN         NaN
1976  209000.0        NaN        NaN         NaN         NaN         NaN         NaN         NaN

       12-24  24-36  36-48  48-60  60-72  72-84  84-96
1969   3.248  3.554  2.069  1.496  1.831  1.545  1.251
1970  12.302  3.811  1.806  2.066  1.900  1.328    NaN
1971   3.888  2.161  2.046  2.248  1.553    NaN    NaN
1972  15.720  4.847  2.565  1.895    NaN    NaN    NaN
1973   3.911  4.321  3.138    NaN    NaN    NaN    NaN
1974   9.227  3.949    NaN    NaN    NaN    NaN    NaN
1975   7.452    NaN    NaN    NaN    NaN    NaN    NaN

       12-24  24-36  36-48  48-60  60-72  72-84  84-96
(All)  6.185  3.709  2.455  1.952  1.718  1.407  1.251

                   12-24   24-36   36-48  48-60  60-72  72-84  84-96  96-108
Selected           6.185   3.709   2.455  1.952  1.718  1.407  1.251   1.486
CDF to Ultimate  493.993  79.870  21.534  8.771  4.494  2.616  1.859   1.486
Percent Paid       0.002   0.013   0.046  0.114  0.223  0.382  0.538   0.673

## P296 (Exhibit I Sheet 3)

In [ ]:
reported_latest = reported.latest_diagonal.to_frame(origin_as_datetime=False).iloc[:, 0]
paid_latest = paid.latest_diagonal.to_frame(origin_as_datetime=False).iloc[:, 0]

ages = sorted(reported.development, reverse=True)
age_to_cdf_reported = dict(zip([12, 24, 36, 48, 60, 72, 84, 96], exhibit_i_s1_sel["CDF to Ultimate"]))
age_to_cdf_paid = dict(zip([12, 24, 36, 48, 60, 72, 84, 96], exhibit_i_s2_sel["CDF to Ultimate"]))

# The exhibit applies the CDFs as printed, so feed the rounded CDFs to the method
cl_reported = cl.Chainladder().fit(
    cl.DevelopmentConstant(patterns=age_to_cdf_reported, style="cdf").fit_transform(reported)
)
cl_paid = cl.Chainladder().fit(
    cl.DevelopmentConstant(patterns=age_to_cdf_paid, style="cdf").fit_transform(paid)
)
ult_reported = cl_reported.ultimate_.to_frame(origin_as_datetime=False).iloc[:, 0]
ult_paid = cl_paid.ultimate_.to_frame(origin_as_datetime=False).iloc[:, 0]

exhibit_i_s3 = pd.DataFrame(
    {
        "Age (2)": ages,
        "Reported (3)": reported_latest.values,
        "Paid (4)": paid_latest.values,
        "CDF Reported (5)": [age_to_cdf_reported[a] for a in ages],
        "CDF Paid (6)": [age_to_cdf_paid[a] for a in ages],
        "Ult Reported (7)": ult_reported.values,
        "Ult Paid (8)": ult_paid.values,
    },
    index=reported_latest.index,
) 
display(exhibit_i_s3)
display(exhibit_i_s3[["Reported (3)", "Paid (4)", "Ult Reported (7)", "Ult Paid (8)"]].sum().to_frame("Total").T)

      Age (2)  Reported (3)    Paid (4)  CDF Reported (5)  CDF Paid (6)  Ult Reported (7)  Ult Paid (8)
1969       96    23506000.0  15815000.0             1.000         1.486        23506000.0    23501090.0
1970       84    32216000.0  18983000.0             1.027         1.859        33085832.0    35289397.0
1971       72    48377000.0  17707000.0             1.080         2.616        52247160.0    46321512.0
1972       60    61163000.0  18518000.0             1.303         4.494        79695389.0    83219892.0
1973       48    73733000.0  11292000.0             1.524         8.771       112369092.0    99042132.0
1974       36    63477000.0   6267000.0             2.291        21.534       145425807.0   134953578.0
1975       24    48904000.0   1565000.0             4.402        79.870       215275408.0   124996550.0
1976       12    15791000.0    209000.0            11.145       493.993       175990695.0   103244537.0

       Reported (3)    Paid (4)  Ult Reported (7)  Ult Paid (8)
Total   367167000.0  90356000.0       837595383.0   650568688.0

## P297 (Exhibit I Sheet 4)

In [ ]:
case = mm["Case Outstanding"]
open_counts = mm["Open Claim Counts"]

exhibit_i_s4_case = case.to_frame(origin_as_datetime=False)
display(exhibit_i_s4_case)

exhibit_i_s4_open = open_counts.to_frame(origin_as_datetime=False)
display(exhibit_i_s4_open)

avg_case = case / open_counts
exhibit_i_s4_avg = np.round(avg_case.to_frame(origin_as_datetime=False))
display(exhibit_i_s4_avg)

avg_df = avg_case.to_frame(origin_as_datetime=False)
avg_df.index = [int(getattr(i, "year", i)) for i in avg_df.index]

# This calculation falls outside of the scope of this package
from scipy.stats import linregress

def exp_trend(s):
    s = s.dropna()
    fit = linregress(s.index.astype(float), np.log(s))
    return pd.Series({"Annual Change": np.exp(fit.slope) - 1, "R-Squared": fit.rvalue ** 2})

exhibit_i_s4_trend = np.round(avg_df.iloc[:, :-1].apply(exp_trend), 3) 
display(exhibit_i_s4_trend)

              12          24          36          48          60          72          84         96
1969   2772000.0   4754000.0   9271000.0  12242000.0  12144000.0  12720000.0  10254000.0  7691000.0
1970   4785000.0  10178000.0  14891000.0  19199000.0  18688000.0  17675000.0  13233000.0        NaN
1971   5160000.0  10794000.0  18254000.0  25857000.0  30996000.0  30670000.0         NaN        NaN
1972   8682000.0  17847000.0  28333000.0  47425000.0  42645000.0         NaN         NaN        NaN
1973  11015000.0  19134000.0  46544000.0  62441000.0         NaN         NaN         NaN        NaN
1974   8534000.0  31872000.0  57210000.0         NaN         NaN         NaN         NaN        NaN
1975  12718000.0  47339000.0         NaN         NaN         NaN         NaN         NaN        NaN
1976  15582000.0         NaN         NaN         NaN         NaN         NaN         NaN        NaN

          12      24      36      48      60      72     84     96
1969   749.0   840.0  1001.0  1206.0  1034.0   765.0  533.0  359.0
1970   660.0   957.0  1149.0  1350.0  1095.0   755.0  539.0    NaN
1971   878.0  1329.0  1720.0  1799.0  1428.0  1056.0    NaN    NaN
1972  1043.0  1561.0  1828.0  1894.0  1522.0     NaN    NaN    NaN
1973  1088.0  1388.0  1540.0  1877.0     NaN     NaN    NaN    NaN
1974  1033.0  1418.0  1663.0     NaN     NaN     NaN    NaN    NaN
1975  1138.0  1472.0     NaN     NaN     NaN     NaN    NaN    NaN
1976  1196.0     NaN     NaN     NaN     NaN     NaN    NaN    NaN

           12       24       36       48       60       72       84       96
1969   3701.0   5660.0   9262.0  10151.0  11745.0  16627.0  19238.0  21423.0
1970   7250.0  10635.0  12960.0  14221.0  17067.0  23411.0  24551.0      NaN
1971   5877.0   8122.0  10613.0  14373.0  21706.0  29044.0      NaN      NaN
1972   8324.0  11433.0  15499.0  25040.0  28019.0      NaN      NaN      NaN
1973  10124.0  13785.0  30223.0  33266.0      NaN      NaN      NaN      NaN
1974   8261.0  22477.0  34402.0      NaN      NaN      NaN      NaN      NaN
1975  11176.0  32160.0      NaN      NaN      NaN      NaN      NaN      NaN
1976  13028.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN

                  12     24     36     48     60     72     84
Annual Change  0.156  0.295  0.311  0.342  0.330  0.322  0.276
R-Squared      0.800  0.895  0.858  0.941  0.989  0.983  1.000

## P298 (Exhibit I Sheet 5)

In [ ]:
exhibit_i_s5_paid = paid.to_frame(origin_as_datetime=False)
display(exhibit_i_s5_paid)

exhibit_i_s5_ratio = np.round((paid / reported).to_frame(origin_as_datetime=False), 3)
display(exhibit_i_s5_ratio)

# Don't know where this is from, but did find these same numbers from another text: 
# Loss Reserve Adequacy Testing: A Comprehensive Systematic Approach
# https://www.casact.org/abstract/loss-reserve-adequacy-testing-comprehensive-systematic-approach
# These values are not used anywhere else, beisdes calcuating the trend below
exhibit_i_s5_avg = pd.DataFrame(
    [
        [402, 539, 2971, 8620, 9199, 12669, 17084, 16634],
        [110, 919, 5487, 9129, 12403, 18452, 19533, np.nan],
        [706, 1115, 5644, 4928, 12994, 14948, np.nan, np.nan],
        [161, 862, 5782, 9477, 14085, np.nan, np.nan, np.nan],
        [724, 541, 4003, 11709, np.nan, np.nan, np.nan, np.nan],
        [518, 1394, 7635, np.nan, np.nan, np.nan, np.nan, np.nan],
        [517, 1494, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan],
        [525, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan],
    ],
    index=range(1969, 1977),
    columns=[12, 24, 36, 48, 60, 72, 84, 96],
    dtype=float,
)
display(exhibit_i_s5_avg)

exhibit_i_s5_trend = np.round(exhibit_i_s5_avg.iloc[:, :-1].apply(exp_trend), 3)
display(exhibit_i_s5_trend)

            12         24         36          48          60          72          84          96
1969  125000.0   406000.0  1443000.0   2986000.0   4467000.0   8179000.0  12638000.0  15815000.0
1970   43000.0   529000.0  2016000.0   3641000.0   7523000.0  14295000.0  18983000.0         NaN
1971  295000.0  1147000.0  2479000.0   5071000.0  11399000.0  17707000.0         NaN         NaN
1972   50000.0   786000.0  3810000.0   9771000.0  18518000.0         NaN         NaN         NaN
1973  213000.0   833000.0  3599000.0  11292000.0         NaN         NaN         NaN         NaN
1974  172000.0  1587000.0  6267000.0         NaN         NaN         NaN         NaN         NaN
1975  210000.0  1565000.0        NaN         NaN         NaN         NaN         NaN         NaN
1976  209000.0        NaN        NaN         NaN         NaN         NaN         NaN         NaN

         12     24     36     48     60     72     84     96
1969  0.043  0.079  0.135  0.196  0.269  0.391  0.552  0.673
1970  0.009  0.049  0.119  0.159  0.287  0.447  0.589    NaN
1971  0.054  0.096  0.120  0.164  0.269  0.366    NaN    NaN
1972  0.006  0.042  0.119  0.171  0.303    NaN    NaN    NaN
1973  0.019  0.042  0.072  0.153    NaN    NaN    NaN    NaN
1974  0.020  0.047  0.099    NaN    NaN    NaN    NaN    NaN
1975  0.016  0.032    NaN    NaN    NaN    NaN    NaN    NaN
1976  0.013    NaN    NaN    NaN    NaN    NaN    NaN    NaN

         12      24      36       48       60       72       84       96
1969  402.0   539.0  2971.0   8620.0   9199.0  12669.0  17084.0  16634.0
1970  110.0   919.0  5487.0   9129.0  12403.0  18452.0  19533.0      NaN
1971  706.0  1115.0  5644.0   4928.0  12994.0  14948.0      NaN      NaN
1972  161.0   862.0  5782.0   9477.0  14085.0      NaN      NaN      NaN
1973  724.0   541.0  4003.0  11709.0      NaN      NaN      NaN      NaN
1974  518.0  1394.0  7635.0      NaN      NaN      NaN      NaN      NaN
1975  517.0  1494.0     NaN      NaN      NaN      NaN      NaN      NaN
1976  525.0     NaN     NaN      NaN      NaN      NaN      NaN      NaN

                  12     24     36     48     60     72     84
Annual Change  0.129  0.120  0.115  0.067  0.142  0.086  0.143
R-Squared      0.183  0.353  0.379  0.101  0.846  0.193  1.000

## P299 (Exhibit I Sheet 6)

In [ ]:
med_mal = cl.load_sample("berqsherm").loc["MedMal"]
bs = cl.BerquistSherman(
    paid_amount="Paid",
    incurred_amount="Incurred",
    reported_count="Reported",
    closed_count="Closed",
    trend=0.15,
).fit(med_mal)

adj_reported = bs.adjusted_triangle_["Incurred"]
adj_avg_case = (adj_reported - med_mal["Paid"]) / (med_mal["Reported"] - med_mal["Closed"])
exhibit_i_s6_avg = np.round(adj_avg_case.to_frame(origin_as_datetime=False))
display(exhibit_i_s6_avg)

exhibit_i_s6_reported = np.round(adj_reported.to_frame(origin_as_datetime=False))
display(exhibit_i_s6_reported)

           12       24       36       48       60       72       84       96
1969   4898.0  13904.0  17104.0  19020.0  18423.0  21961.0  21349.0  21423.0
1970   5633.0  15989.0  19669.0  21873.0  21186.0  25255.0  24551.0      NaN
1971   6477.0  18387.0  22620.0  25154.0  24364.0  29044.0      NaN      NaN
1972   7449.0  21145.0  26013.0  28927.0  28019.0      NaN      NaN      NaN
1973   8566.0  24317.0  29915.0  33266.0      NaN      NaN      NaN      NaN
1974   9851.0  27965.0  34402.0      NaN      NaN      NaN      NaN      NaN
1975  11329.0  32160.0      NaN      NaN      NaN      NaN      NaN      NaN
1976  13028.0      NaN      NaN      NaN      NaN      NaN      NaN      NaN

              12          24          36          48          60          72          84          96
1969   3793504.0  12084942.0  18563821.0  25924316.0  23516364.0  24979245.0  24016864.0  23506000.0
1970   3760482.0  15830500.0  24615996.0  33169802.0  30722141.0  33362729.0  32216000.0         NaN
1971   5982185.0  25583831.0  41384825.0  50323342.0  46191356.0  48377000.0         NaN         NaN
1972   7819355.0  33794110.0  51361061.0  64559286.0  61163000.0         NaN         NaN         NaN
1973   9533246.0  34585431.0  49667342.0  73733000.0         NaN         NaN         NaN         NaN
1974  10348458.0  41241243.0  63477000.0         NaN         NaN         NaN         NaN         NaN
1975  13102479.0  48904000.0         NaN         NaN         NaN         NaN         NaN         NaN
1976  15791000.0         NaN         NaN         NaN         NaN         NaN         NaN         NaN

## P300 (Exhibit I Sheet 7)

In [40]:
# Part 1: Data Triangle
exhibit_i_s7_tri = adj_reported.to_frame(origin_as_datetime=False)
display(exhibit_i_s7_tri)

# Part 2: Age-to-age factors
display(np.round(adj_reported.link_ratio.to_frame(origin_as_datetime=False), decimals=3))

dev_adj_reported = cl.Development(average="simple").fit(adj_reported)
avg_ldf = np.round(
    dev_adj_reported.ldf_.to_frame(origin_as_datetime=False).values.flatten(), 3
)
display(np.round(dev_adj_reported.ldf_.to_frame(), 3))

selected_ldf = {
    12: 3.906,
    24: 1.534,
    36: 1.340,
    48: 0.925,
    60: 1.065,
    72: 0.964,
    84: 0.979,
    96: 1.000,
}
# or this
selected_ldf = dict(zip([12, 24, 36, 48, 60, 72, 84, 96], [*avg_ldf, 1.000]))

# Part 4: Selected age-to-age factors
adj_reported_dev = cl.DevelopmentConstant(patterns=selected_ldf, style="ldf").fit(
    adj_reported
)
cdf = np.round(adj_reported_dev.cdf_.to_frame(origin_as_datetime=False).values.flatten(), 3)
pct_reported = np.round(1.0 / cdf, 3)

exhibit_i_s7_sel = pd.DataFrame(
    {
        "Unadj Selected": list(exhibit_i_s1_sel["Selected"]),
        "Adj Selected": list(selected_ldf.values()),
        "CDF to Ultimate": cdf,
        "Percent Reported": pct_reported,
    },
    index=["12-24", "24-36", "36-48", "48-60", "60-72", "72-84", "84-96", "96-108"],
)
display(exhibit_i_s7_sel.T)

                12            24            36            48            60            72            84          96
1969  3.793504e+06  1.208494e+07  1.856382e+07  2.592432e+07  2.351636e+07  2.497924e+07  2.401686e+07  23506000.0
1970  3.760482e+06  1.583050e+07  2.461600e+07  3.316980e+07  3.072214e+07  3.336273e+07  3.221600e+07         NaN
1971  5.982185e+06  2.558383e+07  4.138482e+07  5.032334e+07  4.619136e+07  4.837700e+07           NaN         NaN
1972  7.819355e+06  3.379411e+07  5.136106e+07  6.455929e+07  6.116300e+07           NaN           NaN         NaN
1973  9.533246e+06  3.458543e+07  4.966734e+07  7.373300e+07           NaN           NaN           NaN         NaN
1974  1.034846e+07  4.124124e+07  6.347700e+07           NaN           NaN           NaN           NaN         NaN
1975  1.310248e+07  4.890400e+07           NaN           NaN           NaN           NaN           NaN         NaN
1976  1.579100e+07           NaN           NaN           NaN           NaN           NaN           NaN         NaN

      12-24  24-36  36-48  48-60  60-72  72-84  84-96
1969  3.186  1.536  1.396  0.907  1.062  0.961  0.979
1970  4.210  1.555  1.347  0.926  1.086  0.966    NaN
1971  4.277  1.618  1.216  0.918  1.047    NaN    NaN
1972  4.322  1.520  1.257  0.947    NaN    NaN    NaN
1973  3.628  1.436  1.485    NaN    NaN    NaN    NaN
1974  3.985  1.539    NaN    NaN    NaN    NaN    NaN
1975  3.732    NaN    NaN    NaN    NaN    NaN    NaN

                          12-24  24-36  36-48  48-60  60-72  72-84  84-96
Simple Average All Years  3.906  1.534   1.34  0.925  1.065  0.964  0.979

                  12-24  24-36  36-48  48-60  60-72  72-84  84-96  96-108
Unadj Selected    2.532  1.921  1.503  1.170  1.206  1.052  1.027     1.0
Adj Selected      3.906  1.534  1.340  0.925  1.065  0.964  0.979     1.0
CDF to Ultimate   7.465  1.911  1.246  0.930  1.005  0.944  0.979     1.0
Percent Reported  0.134  0.523  0.803  1.075  0.995  1.059  1.021     1.0

## P301 (Exhibit I Sheet 8)

In [41]:
adj_reported_latest = (
    dev_adj_reported.fit_transform(adj_reported)
    .latest_diagonal.to_frame(origin_as_datetime=False)
    .iloc[:, 0]
)

age_to_cdf_adj_reported = dict(
    zip([12, 24, 36, 48, 60, 72, 84, 96], exhibit_i_s7_sel["CDF to Ultimate"])
)

cl_adj_reported = cl.Chainladder().fit(
    cl.DevelopmentConstant(patterns=age_to_cdf_adj_reported, style="cdf").fit_transform(
        adj_reported
    )
)
ult_adj_reported = cl_adj_reported.ultimate_.to_frame(origin_as_datetime=False).iloc[:, 0]

exhibit_i_s8 = pd.DataFrame(
    {
        "Age (2)": ages,
        "Reported (3)": reported_latest.values,
        "Paid (4)": paid_latest.values,
        "Adj Reported (5)": adj_reported_latest.values,
        "CDF Reported (6)": [age_to_cdf_reported[a] for a in ages],
        "CDF Paid (7)": [age_to_cdf_paid[a] for a in ages],
        "CDF Adj Reported (8)": [age_to_cdf_adj_reported[a] for a in ages],
        "Ult Reported (9)": ult_reported.values,
        "Ult Paid (10)": ult_paid.values,
        "Ult Adj Reported (11)": ult_adj_reported.values,
    },
    index=reported_latest.index,
)
display(exhibit_i_s8)
display(
    exhibit_i_s8[
        ["Reported (3)", "Paid (4)", "Adj Reported (5)", "Ult Reported (9)", "Ult Paid (10)", "Ult Adj Reported (11)"]
    ]
    .sum()
    .to_frame("Total")
    .T
)

      Age (2)  Reported (3)    Paid (4)  Adj Reported (5)  CDF Reported (6)  CDF Paid (7)  CDF Adj Reported (8)  Ult Reported (9)  Ult Paid (10)  Ult Adj Reported (11)
1969       96    23506000.0  15815000.0        23506000.0             1.000         1.486                 1.000        23506000.0     23501090.0             23506000.0
1970       84    32216000.0  18983000.0        32216000.0             1.027         1.859                 0.979        33085832.0     35289397.0             31539464.0
1971       72    48377000.0  17707000.0        48377000.0             1.080         2.616                 0.944        52247160.0     46321512.0             45667888.0
1972       60    61163000.0  18518000.0        61163000.0             1.303         4.494                 1.005        79695389.0     83219892.0             61468815.0
1973       48    73733000.0  11292000.0        73733000.0             1.524         8.771                 0.930       112369092.0     99042132.0             68571690.0
1974       36    63477000.0   6267000.0        63477000.0             2.291        21.534                 1.246       145425807.0    134953578.0             79092342.0
1975       24    48904000.0   1565000.0        48904000.0             4.402        79.870                 1.911       215275408.0    124996550.0             93455544.0
1976       12    15791000.0    209000.0        15791000.0            11.145       493.993                 7.465       175990695.0    103244537.0            117879815.0

       Reported (3)    Paid (4)  Adj Reported (5)  Ult Reported (9)  Ult Paid (10)  Ult Adj Reported (11)
Total   367167000.0  90356000.0       367167000.0       837595383.0    650568688.0            521181558.0

## P302 (Exhibit I Sheet 9)

In [42]:
case_latest = case.latest_diagonal.to_frame(origin_as_datetime=False).iloc[:, 0]

exhibit_i_s9 = pd.DataFrame(
    {
        "Reported (2)": exhibit_i_s8["Reported (3)"],
        "Paid (3)": exhibit_i_s8["Paid (4)"],
        "Ult Reported (4)": exhibit_i_s8["Ult Reported (9)"],
        "Ult Paid (5)": exhibit_i_s8["Ult Paid (10)"],
        "Ult Adj Reported (6)": exhibit_i_s8["Ult Adj Reported (11)"],
        "Case Outstanding (7)": case_latest.values,
        "IBNR Reported (8)": cl_reported.ibnr_.to_frame(origin_as_datetime=False).iloc[:, 0].values,
        # Paid IBNR in the exhibit is ult paid − reported = paid.ibnr_ − case outstanding
        "IBNR Paid (9)": cl_paid.ibnr_.to_frame(origin_as_datetime=False).iloc[:, 0].values
        - case_latest.values,
        "IBNR Adj Reported (10)": cl_adj_reported.ibnr_.to_frame(origin_as_datetime=False).iloc[:, 0].values,
    },
    index=exhibit_i_s8.index,
)
exhibit_i_s9["Total Unpaid Reported (11)"] = (
    exhibit_i_s9["Case Outstanding (7)"] + exhibit_i_s9["IBNR Reported (8)"]
)
exhibit_i_s9["Total Unpaid Paid (12)"] = (
    exhibit_i_s9["Case Outstanding (7)"] + exhibit_i_s9["IBNR Paid (9)"]
)
exhibit_i_s9["Total Unpaid Adj Reported (13)"] = (
    exhibit_i_s9["Case Outstanding (7)"] + exhibit_i_s9["IBNR Adj Reported (10)"]
)
display(exhibit_i_s9)
display(exhibit_i_s9.sum().to_frame("Total").T)

      Reported (2)    Paid (3)  Ult Reported (4)  Ult Paid (5)  Ult Adj Reported (6)  Case Outstanding (7)  IBNR Reported (8)  IBNR Paid (9)  IBNR Adj Reported (10)  Total Unpaid Reported (11)  Total Unpaid Paid (12)  Total Unpaid Adj Reported (13)
1969    23506000.0  15815000.0        23506000.0    23501090.0            23506000.0             7691000.0                NaN        -4910.0                     NaN                         NaN               7686090.0                             NaN
1970    32216000.0  18983000.0        33085832.0    35289397.0            31539464.0            13233000.0           869832.0      3073397.0               -676536.0                  14102832.0              16306397.0                      12556464.0
1971    48377000.0  17707000.0        52247160.0    46321512.0            45667888.0            30670000.0          3870160.0     -2055488.0              -2709112.0                  34540160.0              28614512.0                      27960888.0
1972    61163000.0  18518000.0        79695389.0    83219892.0            61468815.0            42645000.0         18532389.0     22056892.0                305815.0                  61177389.0              64701892.0                      42950815.0
1973    73733000.0  11292000.0       112369092.0    99042132.0            68571690.0            62441000.0         38636092.0     25309132.0              -5161310.0                 101077092.0              87750132.0                      57279690.0
1974    63477000.0   6267000.0       145425807.0   134953578.0            79092342.0            57210000.0         81948807.0     71476578.0              15615342.0                 139158807.0             128686578.0                      72825342.0
1975    48904000.0   1565000.0       215275408.0   124996550.0            93455544.0            47339000.0        166371408.0     76092550.0              44551544.0                 213710408.0             123431550.0                      91890544.0
1976    15791000.0    209000.0       175990695.0   103244537.0           117879815.0            15582000.0        160199695.0     87453537.0             102088815.0                 175781695.0             103035537.0                     117670815.0

       Reported (2)    Paid (3)  Ult Reported (4)  Ult Paid (5)  Ult Adj Reported (6)  Case Outstanding (7)  IBNR Reported (8)  IBNR Paid (9)  IBNR Adj Reported (10)  Total Unpaid Reported (11)  Total Unpaid Paid (12)  Total Unpaid Adj Reported (13)
Total   367167000.0  90356000.0       837595383.0   650568688.0           521181558.0           276811000.0        470428383.0    283401688.0             154014558.0                 739548383.0             560212688.0                     423134558.0

## P303 (Exhibit I Sheet 10)

In [43]:
# unadj_unpaid = exhibit_i_s9["Total Unpaid Reported (11)"].sum()
# trends = np.arange(0, 36, 5) / 100
# adj_unpaid = []
# for trend in trends:
#     adj = cl.BerquistSherman(
#         paid_amount="Paid",
#         incurred_amount="Incurred",
#         reported_count="Reported",
#         closed_count="Closed",
#         trend=trend,
#     ).fit(med_mal).adjusted_triangle_["Incurred"]
#     avg_ldf = np.round(
#         cl.Development(average="simple").fit(adj).ldf_.to_frame(origin_as_datetime=False).values.flatten(),
#         3,
#     )
#     selected_ldf = dict(zip([12, 24, 36, 48, 60, 72, 84, 96], [*avg_ldf, 1.000]))
#     cdf = np.round(
#         cl.DevelopmentConstant(patterns=selected_ldf, style="ldf")
#         .fit(adj)
#         .cdf_.to_frame(origin_as_datetime=False)
#         .values.flatten(),
#         3,
#     )
#     ult = (
#         cl.Chainladder()
#         .fit(
#             cl.DevelopmentConstant(
#                 patterns=dict(zip([12, 24, 36, 48, 60, 72, 84, 96], cdf)),
#                 style="cdf",
#             ).fit_transform(adj)
#         )
#         .ultimate_.to_frame(origin_as_datetime=False)
#         .iloc[:, 0]
#     )
#     adj_unpaid.append((case_latest.values + ult.values - reported_latest.values).sum())

# exhibit_i_s10 = pd.DataFrame(
#     {
#         "After Adjustment": np.array(adj_unpaid) / 1e6,
#         "Before Adjustment": unadj_unpaid / 1e6,
#         "% of Unadjusted": np.array(adj_unpaid) / unadj_unpaid,
#     },
#     index=[f"{t:.0%}" for t in trends],
# )
# display(exhibit_i_s10)

# fig, ax = plt.subplots(figsize=(8, 5))
# ax.plot(trends, exhibit_i_s10["After Adjustment"], marker="o", label="After Adjustment")
# ax.plot(trends, exhibit_i_s10["Before Adjustment"], marker="o", label="Before Adjustment")
# ax.set_xlabel("Annual Severity Trend")
# ax.set_ylabel("Unpaid Claim Estimate ($ Millions)")
# ax.set_xlim(0, 0.35)
# ax.set_ylim(0, 900)
# ax.set_xticks(trends)
# ax.xaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f"{x:.0%}"))
# ax2 = ax.twinx()
# ax2.set_ylabel("Percent of Unadjusted Unpaid Claim Estimate")
# ax2.set_ylim(0, 1.20)
# ax2.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f"{x:.0%}"))
# ax.legend(loc="upper left")
# ax.set_title("Sensitivity of Unpaid Claim Estimate to Assumed Annual Severity Trend")
# plt.show()