In [2]:
import pandas as pd
import chainladder as cl
import numpy as np

In [4]:
# Page 140, Exhibit I Sheet 1 Columns 1-2
auto_bi = cl.load_sample("friedland_auto_bi_insurer")
print(auto_bi["Reported Claims"].latest_diagonal)
assert np.allclose(
    (auto_bi["Reported Claims"].latest_diagonal).values,
    np.array(
        [
            [
                [
                    [10000000],
                    [8000000],
                    [9400000],
                    [15600000],
                    [16500000],
                    [18500000],
                    [16500000],
                    [14000000],
                    [8700000],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

            2008
2000  10000000.0
2001   8000000.0
2002   9400000.0
2003  15600000.0
2004  16500000.0
2005  18500000.0
2006  16500000.0
2007  14000000.0
2008   8700000.0

In [8]:
# Page 140, Exhibit I Sheet 1 Column 3
print(auto_bi["Paid Claims"].latest_diagonal)
assert np.allclose(
    (auto_bi["Paid Claims"].latest_diagonal).values,
    np.array(
        [
            [
                [
                    [9500000],
                    [7200000],
                    [7600000],
                    [7800000],
                    [11200000],
                    [10200000],
                    [6000000],
                    [3000000],
                    [750000],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

            2008
2000   9500000.0
2001   7200000.0
2002   7600000.0
2003   7800000.0
2004  11200000.0
2005  10200000.0
2006   6000000.0
2007   3000000.0
2008    750000.0

In [ ]:
# Page 140, Exhibit I Sheet 1 Columns 4-5
reported_pattern = {
    12: 4.0,
    24: 2.9,
    36: 1.8,
    48: 1.4,
    60: 1.2,
    72: 1.1,
    84: 1.03,
    96: 1.02,
    108: 1.005,
}
paid_pattern = {
    12: 90.0,
    24: 15.0,
    36: 5.0,
    48: 2.5,
    60: 1.75,
    72: 1.35,
    84: 1.25,
    96: 1.15,
    108: 1.05,
}

In [14]:
# Page 140, Exhibit I Sheet 1 Column 6
Reported_BI = cl.DevelopmentConstant(
    patterns=reported_pattern, style="cdf"
).fit_transform(auto_bi["Reported Claims"])
reported_ultimate = cl.Chainladder().fit(Reported_BI).ultimate_
print(reported_ultimate)
assert np.allclose(
    (reported_ultimate).values,
    np.array(
        [
            [
                [
                    [10050000],
                    [8160000],
                    [9682000],
                    [17160000],
                    [19800000],
                    [25900000],
                    [29700000],
                    [40600000],
                    [34800000],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

            2261
2000  10050000.0
2001   8160000.0
2002   9682000.0
2003  17160000.0
2004  19800000.0
2005  25900000.0
2006  29700000.0
2007  40600000.0
2008  34800000.0

In [19]:
# Page 140, Exhibit I Sheet 1 Column 7
Paid_BI = cl.DevelopmentConstant(patterns=paid_pattern, style="cdf").fit_transform(
    auto_bi["Paid Claims"]
)
paid_ultimate = cl.Chainladder().fit(Paid_BI).ultimate_
print(paid_ultimate)
assert np.allclose(
    (paid_ultimate).values,
    np.array(
        [
            [
                [
                    [9975000],
                    [8280000],
                    [9500000],
                    [10530000],
                    [19600000],
                    [25500000],
                    [30000000],
                    [45000000],
                    [67500000],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

            2261
2000   9975000.0
2001   8280000.0
2002   9500000.0
2003  10530000.0
2004  19600000.0
2005  25500000.0
2006  30000000.0
2007  45000000.0
2008  67500000.0

In [21]:
# Page 140, Exhibit I Sheet 1 Column 8
inital_selected_ultiamte_claims = (reported_ultimate + paid_ultimate) / 2
print(inital_selected_ultiamte_claims)
assert np.allclose(
    (inital_selected_ultiamte_claims).values,
    np.array(
        [
            [
                [
                    [10012500],
                    [8220000],
                    [9591000],
                    [13845000],
                    [19700000],
                    [25700000],
                    [29850000],
                    [42800000],
                    [51150000],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

            2261
2000  10012500.0
2001   8220000.0
2002   9591000.0
2003  13845000.0
2004  19700000.0
2005  25700000.0
2006  29850000.0
2007  42800000.0
2008  51150000.0

In [23]:
# Page 140, Exhibit I Sheet 1 Column 9
print(auto_bi["Earned Premium"].latest_diagonal)
assert np.allclose(
    (auto_bi["Earned Premium"].latest_diagonal).values,
    np.array(
        [
            [
                [
                    [24000000],
                    [18000000],
                    [19000000],
                    [23000000],
                    [32000000],
                    [47000000],
                    [50000000],
                    [57000000],
                    [62000000],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

            2008
2000  24000000.0
2001  18000000.0
2002  19000000.0
2003  23000000.0
2004  32000000.0
2005  47000000.0
2006  50000000.0
2007  57000000.0
2008  62000000.0

In [24]:
# Page 140, Exhibit I Sheet 1 Column 10
trend_factors = np.round(
    cl.Trend(trends=[0.145], dates=[("2008-12-31", "2000-01-01")])
    .fit(auto_bi["Earned Premium"])
    .trend_.latest_diagonal,
    3,
)
print(trend_factors)
assert np.allclose(
    (trend_factors).values,
    np.array(
        [
            [
                [
                    [2.954],
                    [2.58],
                    [2.253],
                    [1.968],
                    [1.719],
                    [1.501],
                    [1.311],
                    [1.145],
                    [1.0],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

       2008
2000  2.954
2001  2.580
2002  2.253
2003  1.968
2004  1.719
2005  1.501
2006  1.311
2007  1.145
2008  1.000

In [25]:
# Page 140, Exhibit I Sheet 1 Column 11
tort_factors = [0.670, 0.670, 0.670, 0.670, 0.750, 1.0, 1.0, 1.0, 1.0]
tort_factors

[0.67, 0.67, 0.67, 0.67, 0.75, 1.0, 1.0, 1.0, 1.0]

In [ ]:
# Page 140, Exhibit I Sheet 1 Column 12
trended_adj_ultimate_claims = np.round(
    (
        trend_factors
        * inital_selected_ultiamte_claims
        * np.array(tort_factors).reshape(1, 1, -1, 1)
    ),
    0,
)
print(trended_adj_ultimate_claims)
assert np.allclose(
    (trended_adj_ultimate_claims).values,
    np.array(
        [
            [
                [
                    [19816540],
                    [14209092],
                    [14477710],
                    [18255463],
                    [25398225],
                    [38575700],
                    [39133350],
                    [49006000],
                    [51150000],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

            2008
2000  19816540.0
2001  14209092.0
2002  14477710.0
2003  18255463.0
2004  25398225.0
2005  38575700.0
2006  39133350.0
2007  49006000.0
2008  51150000.0

In [32]:
# Page 140, Exhibit I Sheet 1 Column 13
trended_adjusted_claim_ratio = np.round(
    trended_adj_ultimate_claims / auto_bi["Earned Premium"].latest_diagonal, 2
)
print(trended_adjusted_claim_ratio)
assert np.allclose(
    (trended_adjusted_claim_ratio).values,
    np.array(
        [[[[0.83], [0.79], [0.76], [0.79], [0.79], [0.82], [0.78], [0.86], [0.82]]]]
    ),
    rtol=1e-6,
    equal_nan=True,
)

      2008
2000  0.83
2001  0.79
2002  0.76
2003  0.79
2004  0.79
2005  0.82
2006  0.78
2007  0.86
2008  0.82

In [ ]:
# Page 140, Exhibit I Sheet 1 Item 14
print(
    "Average 2000 to 2005:",
    np.round(trended_adjusted_claim_ratio.iloc[:, :, 0:6, :].mean(), 3),
)
assert np.isclose(
    np.round(trended_adjusted_claim_ratio.iloc[:, :, 0:6, :].mean(), 3),
    0.797,
    rtol=1e-9,
)
loss_ratios_00_05 = trended_adjusted_claim_ratio.iloc[:, :, 0:6, :].values.flatten()
print(
    "Average 2000 to 2005 Ex High Ex Low:",
    np.round(
        (loss_ratios_00_05.sum() - loss_ratios_00_05.max() - loss_ratios_00_05.min())
        / (len(loss_ratios_00_05) - 2),
        3,
    ),
)
assert np.isclose(
    np.round(
        (loss_ratios_00_05.sum() - loss_ratios_00_05.max() - loss_ratios_00_05.min())
        / (len(loss_ratios_00_05) - 2),
        3,
    ),
    0.798,
    rtol=1e-9,
)
print(
    "Average 2001 to 2006:",
    np.round(trended_adjusted_claim_ratio.iloc[:, :, 1:7, :].mean(), 3),
)
assert np.isclose(
    np.round(trended_adjusted_claim_ratio.iloc[:, :, 1:7, :].mean(), 3),
    0.788,
    rtol=1e-9,
)
loss_ratios_01_06 = trended_adjusted_claim_ratio.iloc[:, :, 1:7, :].values.flatten()
print(
    "Average 2000 to 2005 Ex High Ex Low:",
    np.round(
        (loss_ratios_01_06.sum() - loss_ratios_01_06.max() - loss_ratios_01_06.min())
        / (len(loss_ratios_01_06) - 2),
        3,
    ),
)
assert np.isclose(
    np.round(
        (loss_ratios_01_06.sum() - loss_ratios_01_06.max() - loss_ratios_01_06.min())
        / (len(loss_ratios_01_06) - 2),
        3,
    ),
    0.788,
    rtol=0.0015,  # small rounding error due to python's 64 bit float storage
)

Average 2000 to 2005: 0.797
Average 2000 to 2005 Ex High Ex Low: 0.798
Average 2001 to 2006: 0.788
Average 2000 to 2005 Ex High Ex Low: 0.787

In [57]:
# Page 140, Exhibit I Item 15
selected_claim_ratio = 0.80
selected_claim_ratio

0.8

In [60]:
# Page 140, Exhibit I Item 16
earned_premium = auto_bi["Earned Premium"].loc[:, :, "2008", :].latest_diagonal
expected_claims_2008 = earned_premium * selected_claim_ratio
print(expected_claims_2008)
assert np.isclose(expected_claims_2008, 49600000, rtol=1e-9)

49600000.0

In [62]:
# Page 140, Exhibit I Item 17
print(
    "Total Unpaid Claims:",
    expected_claims_2008 - auto_bi["Paid Claims"].loc[:, :, "2008", :].latest_diagonal,
)
assert np.isclose(
    expected_claims_2008 - auto_bi["Paid Claims"].loc[:, :, "2008", :].latest_diagonal,
    48850000,
    rtol=1e-9,
)
print(
    "Total IBNR:",
    expected_claims_2008
    - auto_bi["Reported Claims"].loc[:, :, "2008", :].latest_diagonal,
)
assert np.isclose(
    expected_claims_2008
    - auto_bi["Reported Claims"].loc[:, :, "2008", :].latest_diagonal,
    40900000,
    rtol=1e-9,
)

Total Unpaid Claims: 48850000.0
Total IBNR: 40900000.0

In [ ]:
# Page 141, Exhibit I Sheet 2, columns 1-2
friedland_gl_self_insurer = cl.load_sample("friedland_gl_self_insurer")
assert np.allclose(
    friedland_gl_self_insurer.values,
    np.array(
        [
            [
                [
                    [900000.0],
                    [1200000.0],
                    [1300000.0],
                    [1800000.0],
                    [1450000.0],
                    [1400000.0],
                    [2400000.0],
                    [1800000.0],
                    [1500000.0],
                    [1200000.0],
                    [600000.0],
                ],
                [
                    [890000.0],
                    [1170000.0],
                    [1265000.0],
                    [1600000.0],
                    [1200000.0],
                    [1050000.0],
                    [900000.0],
                    [860000.0],
                    [525000.0],
                    [750000.0],
                    [170000.0],
                ],
                [
                    [709000.0],
                    [724000.0],
                    [736000.0],
                    [740000.0],
                    [750000.0],
                    [760000.0],
                    [770000.0],
                    [775000.0],
                    [780000.0],
                    [785000.0],
                    [790000.0],
                ],
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)
friedland_gl_self_insurer["Reported Claims"].latest_diagonal
assert np.allclose(
    (friedland_gl_self_insurer["Reported Claims"].latest_diagonal).values,
    np.array(
        [
            [
                [
                    [900000.0],
                    [1200000.0],
                    [1300000.0],
                    [1800000.0],
                    [1450000.0],
                    [1400000.0],
                    [2400000.0],
                    [1800000.0],
                    [1500000.0],
                    [1200000.0],
                    [600000.0],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

           2008
1998   900000.0
1999  1200000.0
2000  1300000.0
2001  1800000.0
2002  1450000.0
2003  1400000.0
2004  2400000.0
2005  1800000.0
2006  1500000.0
2007  1200000.0
2008   600000.0

In [ ]:
# Page 141, Exhibit I Sheet 2, column 3
friedland_gl_self_insurer["Paid Claims"].latest_diagonal
assert np.allclose(
    (friedland_gl_self_insurer["Paid Claims"].latest_diagonal).values,
    np.array(
        [
            [
                [
                    [890000.0],
                    [1170000.0],
                    [1265000.0],
                    [1600000.0],
                    [1200000.0],
                    [1050000.0],
                    [900000.0],
                    [860000.0],
                    [525000.0],
                    [750000.0],
                    [170000.0],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

           2008
1998   890000.0
1999  1170000.0
2000  1265000.0
2001  1600000.0
2002  1200000.0
2003  1050000.0
2004   900000.0
2005   860000.0
2006   525000.0
2007   750000.0
2008   170000.0

In [ ]:
# Page 4, Exhibit I Sheet 2 Columns 4-5
reported_pattern = {
    12: 3.104,
    24: 1.940,
    36: 1.616,
    48: 1.394,
    60: 1.244,
    72: 1.131,
    84: 1.077,
    96: 1.051,
    108: 1.030,
    120: 1.020,
    132: 1.015,
}
assert reported_pattern == {
    12: 3.104,
    24: 1.94,
    36: 1.616,
    48: 1.394,
    60: 1.244,
    72: 1.131,
    84: 1.077,
    96: 1.051,
    108: 1.03,
    120: 1.02,
    132: 1.015,
}
paid_pattern = {
    12: 20.373,
    24: 5.093,
    36: 3.183,
    48: 2.274,
    60: 1.749,
    72: 1.489,
    84: 1.306,
    96: 1.187,
    108: 1.109,
    120: 1.067,
    132: 1.046,
}
assert paid_pattern == {
    12: 20.373,
    24: 5.093,
    36: 3.183,
    48: 2.274,
    60: 1.749,
    72: 1.489,
    84: 1.306,
    96: 1.187,
    108: 1.109,
    120: 1.067,
    132: 1.046,
}

In [ ]:
# Page 141, Exhibit I Sheet 2 Columns 6
reported = cl.DevelopmentConstant(patterns=reported_pattern, style="cdf").fit_transform(
    friedland_gl_self_insurer["Reported Claims"]
)
assert np.allclose(
    reported.values,
    np.array(
        [
            [
                [
                    [900000.0],
                    [1200000.0],
                    [1300000.0],
                    [1800000.0],
                    [1450000.0],
                    [1400000.0],
                    [2400000.0],
                    [1800000.0],
                    [1500000.0],
                    [1200000.0],
                    [600000.0],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)
reported_ultimate = cl.Chainladder().fit(reported).ultimate_
assert np.allclose(
    reported_ultimate.values,
    np.array(
        [
            [
                [
                    [913499.9999999999],
                    [1224000.0],
                    [1339000.0],
                    [1891799.9999999998],
                    [1561650.0],
                    [1583400.0],
                    [2985600.0],
                    [2509200.0],
                    [2424000.0],
                    [2328000.0],
                    [1862400.0],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)
reported_ultimate
assert np.allclose(
    (reported_ultimate).values,
    np.array(
        [
            [
                [
                    [913499.9999999999],
                    [1224000.0],
                    [1339000.0],
                    [1891799.9999999998],
                    [1561650.0],
                    [1583400.0],
                    [2985600.0],
                    [2509200.0],
                    [2424000.0],
                    [2328000.0],
                    [1862400.0],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

           2261
1998   913500.0
1999  1224000.0
2000  1339000.0
2001  1891800.0
2002  1561650.0
2003  1583400.0
2004  2985600.0
2005  2509200.0
2006  2424000.0
2007  2328000.0
2008  1862400.0

In [ ]:
# Page 141, Exhibit I Sheet 2 Columns 7
paid = cl.DevelopmentConstant(patterns=paid_pattern, style="cdf").fit_transform(
    friedland_gl_self_insurer["Paid Claims"]
)
assert np.allclose(
    paid.values,
    np.array(
        [
            [
                [
                    [890000.0],
                    [1170000.0],
                    [1265000.0],
                    [1600000.0],
                    [1200000.0],
                    [1050000.0],
                    [900000.0],
                    [860000.0],
                    [525000.0],
                    [750000.0],
                    [170000.0],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)
paid_ultimate = cl.Chainladder().fit(paid).ultimate_
assert np.allclose(
    paid_ultimate.values,
    np.array(
        [
            [
                [
                    [930940.0],
                    [1248390.0],
                    [1402885.0],
                    [1899200.0],
                    [1567200.0],
                    [1563450.0],
                    [1574100.0000000002],
                    [1955640.0000000005],
                    [1671075.0000000002],
                    [3819750.0000000005],
                    [3463410.000000001],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)
paid_ultimate
assert np.allclose(
    (paid_ultimate).values,
    np.array(
        [
            [
                [
                    [930940.0],
                    [1248390.0],
                    [1402885.0],
                    [1899200.0],
                    [1567200.0],
                    [1563450.0],
                    [1574100.0000000002],
                    [1955640.0000000005],
                    [1671075.0000000002],
                    [3819750.0000000005],
                    [3463410.000000001],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

           2261
1998   930940.0
1999  1248390.0
2000  1402885.0
2001  1899200.0
2002  1567200.0
2003  1563450.0
2004  1574100.0
2005  1955640.0
2006  1671075.0
2007  3819750.0
2008  3463410.0

In [ ]:
# Page 141, Exhibit I Sheet 2 Columns 8
selected_ultimate = (reported_ultimate + paid_ultimate) / 2
assert np.allclose(
    selected_ultimate.values,
    np.array(
        [
            [
                [
                    [922220.0],
                    [1236195.0],
                    [1370942.5],
                    [1895500.0],
                    [1564425.0],
                    [1573425.0],
                    [2279850.0],
                    [2232420.0],
                    [2047537.5],
                    [3073875.0],
                    [2662905.0000000005],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)
selected_ultimate
assert np.allclose(
    (selected_ultimate).values,
    np.array(
        [
            [
                [
                    [922220.0],
                    [1236195.0],
                    [1370942.5],
                    [1895500.0],
                    [1564425.0],
                    [1573425.0],
                    [2279850.0],
                    [2232420.0],
                    [2047537.5],
                    [3073875.0],
                    [2662905.0000000005],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

           2261
1998   922220.0
1999  1236195.0
2000  1370942.5
2001  1895500.0
2002  1564425.0
2003  1573425.0
2004  2279850.0
2005  2232420.0
2006  2047537.5
2007  3073875.0
2008  2662905.0

In [78]:
# Page 141, Exhibit I Sheet 2 Columns 9
population = (
    friedland_gl_self_insurer["Population"].latest_diagonal
)
print(population)
assert np.allclose(
    population.values,
    np.array(
        [
            [
                [
                    [709000],
                    [724000],
                    [736000],
                    [740000],
                    [750000],
                    [760000],
                    [770000],
                    [775000],
                    [780000],
                    [785000],
                    [790000],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

          2008
1998  709000.0
1999  724000.0
2000  736000.0
2001  740000.0
2002  750000.0
2003  760000.0
2004  770000.0
2005  775000.0
2006  780000.0
2007  785000.0
2008  790000.0

In [79]:
# Page 141, Exhibit I Sheet 2 Column 10
trend_factors = np.round(
    cl.Trend(trends=[0.075], dates=[("2008-12-31", "1998-01-01")])
    .fit(friedland_gl_self_insurer["Population"])
    .trend_.latest_diagonal,
    3,
)
print(trend_factors)
assert np.allclose(
    (trend_factors).values,
    np.array(
        [
            [
                [
                    [2.061],
                    [1.917],
                    [1.783],
                    [1.659],
                    [1.543],
                    [1.436],
                    [1.335],
                    [1.242],
                    [1.156],
                    [1.075],
                    [1.0],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

       2008
1998  2.061
1999  1.917
2000  1.783
2001  1.659
2002  1.543
2003  1.436
2004  1.335
2005  1.242
2006  1.156
2007  1.075
2008  1.000

In [80]:
# Page 141, Exhibit I Sheet 2 Column 11
trended_adj_ultimate_claims = np.round(selected_ultimate * trend_factors, 0)
print(trended_adj_ultimate_claims)
assert np.allclose(
    (trended_adj_ultimate_claims).values,
    np.array(
        [
            [
                [
                    [1900695],
                    [2369786],
                    [2444390],
                    [3144635],
                    [2413908],
                    [2259438],
                    [3043600],
                    [2772666],
                    [2366953],
                    [3304416],
                    [2662905],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

           2261
1998  1900695.0
1999  2369786.0
2000  2444390.0
2001  3144634.0
2002  2413908.0
2003  2259438.0
2004  3043600.0
2005  2772666.0
2006  2366954.0
2007  3304416.0
2008  2662905.0

In [84]:
# Page 141, Exhibit I Sheet 2 Column 12
trended_pure_premium = np.round(trended_adj_ultimate_claims / population, 2)
print(trended_pure_premium)
assert np.allclose(
    (trended_pure_premium).values,
    np.array(
        [
            [
                [
                    [2.68],
                    [3.27],
                    [3.32],
                    [4.25],
                    [3.22],
                    [2.97],
                    [3.95],
                    [3.58],
                    [3.03],
                    [4.21],
                    [3.37],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

      2261
1998  2.68
1999  3.27
2000  3.32
2001  4.25
2002  3.22
2003  2.97
2004  3.95
2005  3.58
2006  3.03
2007  4.21
2008  3.37

In [91]:
# Page 141, Exhibit I Sheet 2 Item 13
print(
    "Average 2000 to 2005:", np.round(trended_pure_premium.iloc[:, :, 2:8, :].mean(), 2)
)
assert np.isclose(
    np.round(trended_pure_premium.iloc[:, :, 2:8, :].mean(), 2), 3.55, rtol=1e-9
)
loss_ratios_00_05 = trended_pure_premium.iloc[:, :, 2:8, :].values.flatten()
print(
    "Average 2000 to 2005 Ex High Ex Low:",
    np.round(
        (loss_ratios_00_05.sum() - loss_ratios_00_05.max() - loss_ratios_00_05.min())
        / (len(loss_ratios_00_05) - 2),
        2,
    ),
)
assert np.isclose(
    np.round(
        (loss_ratios_00_05.sum() - loss_ratios_00_05.max() - loss_ratios_00_05.min())
        / (len(loss_ratios_00_05) - 2),
        2,
    ),
    3.52,
    rtol=1e-9,
)
print(
    "Average 2001 to 2006:", np.round(trended_pure_premium.iloc[:, :, 3:9, :].mean(), 2)
)
assert np.isclose(
    np.round(trended_pure_premium.iloc[:, :, 3:9, :].mean(), 2), 3.50, rtol=1e-9
)
loss_ratios_01_06 = trended_pure_premium.iloc[:, :, 3:9, :].values.flatten()
print(
    "Average 2001 to 2006 Ex High Ex Low:",
    np.round(
        (loss_ratios_01_06.sum() - loss_ratios_01_06.max() - loss_ratios_01_06.min())
        / (len(loss_ratios_01_06) - 2),
        2,
    ),
) 
assert np.isclose(
    np.round(
        (loss_ratios_01_06.sum() - loss_ratios_01_06.max() - loss_ratios_01_06.min())
        / (len(loss_ratios_01_06) - 2),
        2,
    ),
    3.45,
    rtol=0.015,  # small rounding error due to python's 64 bit float storage
)

Average 2000 to 2005: 3.55
Average 2000 to 2005 Ex High Ex Low: 3.52
Average 2001 to 2006: 3.5
Average 2001 to 2006 Ex High Ex Low: 3.44

In [92]:
# Page 141, Exhibit I Sheet 2 Item 14
selected_pure_premium = 3.50
selected_pure_premium

3.5

In [93]:
# Page 141, Exhibit I Sheet 2 Item 15

expected_claims_2008 = (
    selected_pure_premium * population.loc[:, :, "2008", :].latest_diagonal
)
print(expected_claims_2008)
assert np.isclose(expected_claims_2008, 2765000, rtol=1e-9)

2765000.0

In [94]:
# Page 141, Exhibit I Item 16
print(
    "Total Unpaid Claims:",
    expected_claims_2008
    - friedland_gl_self_insurer["Paid Claims"].loc[:, :, "2008", :].latest_diagonal,
)
assert np.isclose(
    expected_claims_2008
    - friedland_gl_self_insurer["Paid Claims"].loc[:, :, "2008", :].latest_diagonal,
    2595000,
    rtol=1e-9,
)
print(
    "Total IBNR:",
    expected_claims_2008
    - friedland_gl_self_insurer["Reported Claims"].loc[:, :, "2008", :].latest_diagonal,
)
assert np.isclose(
    expected_claims_2008
    - friedland_gl_self_insurer["Reported Claims"].loc[:, :, "2008", :].latest_diagonal,
    2165000,
    rtol=1e-9,
)

Total Unpaid Claims: 2595000.0
Total IBNR: 2165000.0

In [96]:
# Page 142, Exhibit II Sheet 1, columns 1-2
friedland_us_industry_auto = cl.load_sample("friedland_us_industry_auto")
print(friedland_us_industry_auto["Reported Claims"].latest_diagonal)
assert np.allclose(
    (friedland_us_industry_auto["Reported Claims"].latest_diagonal).values,
    np.array(
        [
            [
                [
                    [47742304],
                    [51185767],
                    [54837929],
                    [56299562],
                    [58592712],
                    [57565344],
                    [56976657],
                    [56786410],
                    [54641339],
                    [48853563],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

            2007
1998  47742304.0
1999  51185767.0
2000  54837929.0
2001  56299562.0
2002  58592712.0
2003  57565344.0
2004  56976657.0
2005  56786410.0
2006  54641339.0
2007  48853563.0

In [98]:
# Page 142, Exhibit II Sheet 1, columns 3
print(friedland_us_industry_auto["Paid Claims"].latest_diagonal)
assert np.allclose(
    (friedland_us_industry_auto["Paid Claims"].latest_diagonal).values,
    np.array(
        [
            [
                [
                    [47644187],
                    [51000534],
                    [54533225],
                    [55878421],
                    [57807215],
                    [55930654],
                    [53774672],
                    [50644994],
                    [43606497],
                    [27229969],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

            2007
1998  47644187.0
1999  51000534.0
2000  54533225.0
2001  55878421.0
2002  57807215.0
2003  55930654.0
2004  53774672.0
2005  50644994.0
2006  43606497.0
2007  27229969.0

In [99]:
# Page 142, Exhibit II Sheet 1, columns 4-5
reported_pattern = {
    12: 1.292,
    24: 1.110,
    36: 1.051,
    48: 1.023,
    60: 1.011,
    72: 1.006,
    84: 1.003,
    96: 1.001,
    108: 1.000,
    120: 1.000,
}
paid_pattern = {
    12: 2.390,
    24: 1.404,
    36: 1.184,
    48: 1.085,
    60: 1.040,
    72: 1.020,
    84: 1.011,
    96: 1.006,
    108: 1.004,
    120: 1.002,
}

In [100]:
# Page 142, Exhibit II Sheet 1, column 6
reported_ultimate = (
    cl.Chainladder()
    .fit(
        cl.DevelopmentConstant(patterns=reported_pattern, style="cdf").fit_transform(
            friedland_us_industry_auto["Reported Claims"]
        )
    )
    .ultimate_
)
print(reported_ultimate)
assert np.allclose(
    (reported_ultimate).values,
    np.array(
        [
            [
                [
                    [47742304],
                    [51185767],
                    [54892767],
                    [56468461],
                    [58944268],
                    [58198563],
                    [58287120],
                    [59682517],
                    [60651886],
                    [63118803],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

              2261
1998  4.774230e+07
1999  5.118577e+07
2000  5.489277e+07
2001  5.646846e+07
2002  5.894427e+07
2003  5.819856e+07
2004  5.828712e+07
2005  5.968252e+07
2006  6.065189e+07
2007  6.311880e+07

In [101]:
# Page 142, Exhibit II Sheet 1, column 7
paid_ultimate = (
    cl.Chainladder()
    .fit(
        cl.DevelopmentConstant(patterns=paid_pattern, style="cdf").fit_transform(
            friedland_us_industry_auto["Paid Claims"]
        )
    )
    .ultimate_
)
print(paid_ultimate)
assert np.allclose(
    (paid_ultimate).values,
    np.array(
        [
            [
                [
                    [47739475],
                    [51204536],
                    [54860424],
                    [56493084],
                    [58963359],
                    [58167880],
                    [58345519],
                    [59963673],
                    [61223522],
                    [65079626],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

              2261
1998  4.773948e+07
1999  5.120454e+07
2000  5.486042e+07
2001  5.649308e+07
2002  5.896336e+07
2003  5.816788e+07
2004  5.834552e+07
2005  5.996367e+07
2006  6.122352e+07
2007  6.507963e+07

In [104]:
# Page 142, Exhibit II Sheet 1, column 8
selected_ultimate = np.round((reported_ultimate + paid_ultimate) / 2, 0)
print(selected_ultimate)
assert np.allclose(
    selected_ultimate.values,
    np.array(
        [
            [
                [
                    [47740890],
                    [51195152],
                    [54876596],
                    [56480772],
                    [58953814],
                    [58183221],
                    [58316320],
                    [59823095],
                    [60937704],
                    [64099215],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

            2261
1998  47740890.0
1999  51195152.0
2000  54876596.0
2001  56480772.0
2002  58953814.0
2003  58183221.0
2004  58316320.0
2005  59823095.0
2006  60937704.0
2007  64099215.0

In [105]:
# Page 142, Exhibit II Sheet 1, column 9
earned_premium = friedland_us_industry_auto["Earned Premium"].latest_diagonal
print(earned_premium)
assert np.allclose(
    (earned_premium).values,
    np.array(
        [
            [
                [
                    [68574209],
                    [68544981],
                    [68907977],
                    [72544955],
                    [79228887],
                    [86643542],
                    [91763523],
                    [94115312],
                    [95272279],
                    [95176240],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

            2007
1998  68574209.0
1999  68544981.0
2000  68907977.0
2001  72544955.0
2002  79228887.0
2003  86643542.0
2004  91763523.0
2005  94115312.0
2006  95272279.0
2007  95176240.0

In [108]:
# Page 142, Exhibit II Sheet 1, column 10
estimated_claim_ratios = np.round(selected_ultimate / earned_premium, 3)
print(estimated_claim_ratios)
assert np.allclose(
    estimated_claim_ratios.values,
    np.array(
        [
            [
                [
                    [0.696],
                    [0.747],
                    [0.796],
                    [0.779],
                    [0.744],
                    [0.672],
                    [0.636],
                    [0.636],
                    [0.64],
                    [0.673],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

       2261
1998  0.696
1999  0.747
2000  0.796
2001  0.779
2002  0.744
2003  0.672
2004  0.636
2005  0.636
2006  0.640
2007  0.673

In [109]:
# Page 142, Exhibit II Sheet 1, column 11
selected_claim_ratio = [0.75, 0.75, 0.75, 0.75, 0.75, 0.65, 0.65, 0.65, 0.65, 0.65]
selected_claim_ratio

[0.75, 0.75, 0.75, 0.75, 0.75, 0.65, 0.65, 0.65, 0.65, 0.65]

In [111]:
# Page 142, Exhibit II Sheet 1, column 12
expected_claims = np.round(earned_premium * np.array(selected_claim_ratio).reshape(1, 1, -1, 1), 0)
print(expected_claims)
assert np.allclose(
    (expected_claims).values,
    np.array(
        [
            [
                [
                    [51430657],
                    [51408736],
                    [51680983],
                    [54408716],
                    [59421665],
                    [56318302],
                    [59646290],
                    [61174953],
                    [61926981],
                    [61864556],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

            2007
1998  51430657.0
1999  51408736.0
2000  51680983.0
2001  54408716.0
2002  59421665.0
2003  56318302.0
2004  59646290.0
2005  61174953.0
2006  61926981.0
2007  61864556.0

In [ ]:
# Page 143, Exhibit II Sheet 2, columns 1-2
print(friedland_us_industry_auto["Reported Claims"].latest_diagonal)
assert np.allclose(
    (friedland_us_industry_auto["Reported Claims"].latest_diagonal).values,
    np.array(
        [
            [
                [
                    [47742304.0],
                    [51185767.0],
                    [54837929.0],
                    [56299562.0],
                    [58592712.0],
                    [57565344.0],
                    [56976657.0],
                    [56786410.0],
                    [54641339.0],
                    [48853563.0],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)
print("Total:", friedland_us_industry_auto["Reported Claims"].latest_diagonal.sum())
assert np.isclose(
    friedland_us_industry_auto["Reported Claims"].latest_diagonal.sum(),
    543481587.0,
    rtol=1e-9,
)

            2007
1998  47742304.0
1999  51185767.0
2000  54837929.0
2001  56299562.0
2002  58592712.0
2003  57565344.0
2004  56976657.0
2005  56786410.0
2006  54641339.0
2007  48853563.0
Total: 543481587.0

In [ ]:
# Page 143, Exhibit II Sheet 2, column 3
print(friedland_us_industry_auto["Paid Claims"].latest_diagonal)
assert np.allclose(
    (friedland_us_industry_auto["Paid Claims"].latest_diagonal).values,
    np.array(
        [
            [
                [
                    [47644187.0],
                    [51000534.0],
                    [54533225.0],
                    [55878421.0],
                    [57807215.0],
                    [55930654.0],
                    [53774672.0],
                    [50644994.0],
                    [43606497.0],
                    [27229969.0],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)
print("Total:", friedland_us_industry_auto["Paid Claims"].latest_diagonal.sum())
assert np.isclose(
    friedland_us_industry_auto["Paid Claims"].latest_diagonal.sum(),
    498050368.0,
    rtol=1e-9,
)

            2007
1998  47644187.0
1999  51000534.0
2000  54533225.0
2001  55878421.0
2002  57807215.0
2003  55930654.0
2004  53774672.0
2005  50644994.0
2006  43606497.0
2007  27229969.0
Total: 498050368.0

In [ ]:
# Page 143, Exhibit II Sheet 2, column 4
print(np.round(expected_claims, 0))
assert np.allclose(
    (np.round(expected_claims, 0)).values,
    np.array(
        [
            [
                [
                    [51430657.0],
                    [51408736.0],
                    [51680983.0],
                    [54408716.0],
                    [59421665.0],
                    [56318302.0],
                    [59646290.0],
                    [61174953.0],
                    [61926981.0],
                    [61864556.0],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)
print("Total:", np.round(expected_claims.sum(), 0))
assert np.isclose(np.round(expected_claims.sum(), 0), 569281839.0, rtol=1e-9)

            2007
1998  51430657.0
1999  51408736.0
2000  51680983.0
2001  54408716.0
2002  59421665.0
2003  56318302.0
2004  59646290.0
2005  61174953.0
2006  61926981.0
2007  61864556.0
Total: 569281839.0

In [ ]:
# Page 143, Exhibit II Sheet 2, column 5
case_outstanding = (
    friedland_us_industry_auto["Reported Claims"].latest_diagonal
    - friedland_us_industry_auto["Paid Claims"].latest_diagonal
)
assert np.allclose(
    case_outstanding.values,
    np.array(
        [
            [
                [
                    [98117.0],
                    [185233.0],
                    [304704.0],
                    [421141.0],
                    [785497.0],
                    [1634690.0],
                    [3201985.0],
                    [6141416.0],
                    [11034842.0],
                    [21623594.0],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)
print(case_outstanding)
assert np.allclose(
    (case_outstanding).values,
    np.array(
        [
            [
                [
                    [98117.0],
                    [185233.0],
                    [304704.0],
                    [421141.0],
                    [785497.0],
                    [1634690.0],
                    [3201985.0],
                    [6141416.0],
                    [11034842.0],
                    [21623594.0],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)
print("Total:", case_outstanding.sum())
assert np.isclose(case_outstanding.sum(), 45431219.0, rtol=1e-9)

            2007
1998     98117.0
1999    185233.0
2000    304704.0
2001    421141.0
2002    785497.0
2003   1634690.0
2004   3201985.0
2005   6141416.0
2006  11034842.0
2007  21623594.0
Total: 45431219.0

In [ ]:
# Page 143, Exhibit II Sheet 2, column 6
ibnr = np.round(
    expected_claims - friedland_us_industry_auto["Reported Claims"].latest_diagonal, 0
)
assert np.allclose(
    ibnr.values,
    np.array(
        [
            [
                [
                    [3688353.0],
                    [222969.0],
                    [-3156946.0],
                    [-1890846.0],
                    [828953.0],
                    [-1247042.0],
                    [2669633.0],
                    [4388543.0],
                    [7285642.0],
                    [13010993.0],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)
print(ibnr)
assert np.allclose(
    (ibnr).values,
    np.array(
        [
            [
                [
                    [3688353.0],
                    [222969.0],
                    [-3156946.0],
                    [-1890846.0],
                    [828953.0],
                    [-1247042.0],
                    [2669633.0],
                    [4388543.0],
                    [7285642.0],
                    [13010993.0],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)
print("Total:", ibnr.sum())
assert np.isclose(ibnr.sum(), 25800252.0, rtol=1e-9)

            2007
1998   3688353.0
1999    222969.0
2000  -3156946.0
2001  -1890846.0
2002    828953.0
2003  -1247042.0
2004   2669633.0
2005   4388543.0
2006   7285642.0
2007  13010993.0
Total: 25800252.0

In [ ]:
# Page 143, Exhibit II Sheet 2, column 7
total_unpaid = np.round(
    expected_claims - friedland_us_industry_auto["Paid Claims"].latest_diagonal, 0
)
assert np.allclose(
    total_unpaid.values,
    np.array(
        [
            [
                [
                    [3786470.0],
                    [408202.0],
                    [-2852242.0],
                    [-1469705.0],
                    [1614450.0],
                    [387648.0],
                    [5871618.0],
                    [10529959.0],
                    [18320484.0],
                    [34634587.0],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)
print(total_unpaid)
assert np.allclose(
    (total_unpaid).values,
    np.array(
        [
            [
                [
                    [3786470.0],
                    [408202.0],
                    [-2852242.0],
                    [-1469705.0],
                    [1614450.0],
                    [387648.0],
                    [5871618.0],
                    [10529959.0],
                    [18320484.0],
                    [34634587.0],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)
print("Total:", total_unpaid.sum())
assert np.isclose(total_unpaid.sum(), 71231471.0, rtol=1e-9)

            2007
1998   3786470.0
1999    408202.0
2000  -2852242.0
2001  -1469705.0
2002   1614450.0
2003    387648.0
2004   5871618.0
2005  10529959.0
2006  18320484.0
2007  34634587.0
Total: 71231471.0

In [ ]:
# Page 144, Exhibit III Sheet 1, columns 1-2
friedland_xyz_auto_bi = cl.load_sample("friedland_xyz_auto_bi")
assert np.allclose(
    friedland_xyz_auto_bi.values,
    np.array(
        [
            [
                [
                    [
                        np.nan,
                        np.nan,
                        6309.0,
                        8521.0,
                        10082.0,
                        11620.0,
                        13242.0,
                        14419.0,
                        15311.0,
                        15764.0,
                        15822.0,
                    ],
                    [
                        np.nan,
                        4666.0,
                        9861.0,
                        13971.0,
                        18127.0,
                        22032.0,
                        23511.0,
                        24146.0,
                        24592.0,
                        24817.0,
                        np.nan,
                    ],
                    [
                        1302.0,
                        6513.0,
                        12139.0,
                        17828.0,
                        24030.0,
                        28853.0,
                        33222.0,
                        35902.0,
                        36782.0,
                        np.nan,
                        np.nan,
                    ],
                    [
                        1539.0,
                        5952.0,
                        12319.0,
                        18609.0,
                        24387.0,
                        31090.0,
                        37070.0,
                        38519.0,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        2318.0,
                        7932.0,
                        13822.0,
                        22095.0,
                        31945.0,
                        40629.0,
                        44437.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        1743.0,
                        6240.0,
                        12683.0,
                        22892.0,
                        34505.0,
                        39320.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        2221.0,
                        9898.0,
                        25950.0,
                        43439.0,
                        52811.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        3043.0,
                        12219.0,
                        27073.0,
                        40026.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        3531.0,
                        11778.0,
                        22819.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        3529.0,
                        11865.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        3409.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                ],
                [
                    [
                        np.nan,
                        np.nan,
                        11171.0,
                        12380.0,
                        13216.0,
                        14067.0,
                        14688.0,
                        16366.0,
                        16163.0,
                        15835.0,
                        15822.0,
                    ],
                    [
                        np.nan,
                        13255.0,
                        16405.0,
                        19639.0,
                        22473.0,
                        23764.0,
                        25094.0,
                        24795.0,
                        25071.0,
                        25107.0,
                        np.nan,
                    ],
                    [
                        15676.0,
                        18749.0,
                        21900.0,
                        27144.0,
                        29488.0,
                        34458.0,
                        36949.0,
                        37505.0,
                        37246.0,
                        np.nan,
                        np.nan,
                    ],
                    [
                        11827.0,
                        16004.0,
                        21022.0,
                        26578.0,
                        34205.0,
                        37136.0,
                        38541.0,
                        38798.0,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        12811.0,
                        20370.0,
                        26656.0,
                        37667.0,
                        44414.0,
                        48701.0,
                        48169.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        9651.0,
                        16995.0,
                        30354.0,
                        40594.0,
                        44231.0,
                        44373.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        16995.0,
                        40180.0,
                        58866.0,
                        71707.0,
                        70288.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        28674.0,
                        47432.0,
                        70340.0,
                        70655.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        27066.0,
                        46783.0,
                        48804.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        19477.0,
                        31732.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        18632.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                ],
                [
                    [
                        np.nan,
                        np.nan,
                        np.nan,
                        510.0,
                        547.0,
                        575.0,
                        598.0,
                        612.0,
                        620.0,
                        635.0,
                        637.0,
                    ],
                    [
                        np.nan,
                        np.nan,
                        686.0,
                        819.0,
                        910.0,
                        980.0,
                        1007.0,
                        1036.0,
                        1039.0,
                        1044.0,
                        np.nan,
                    ],
                    [
                        np.nan,
                        650.0,
                        932.0,
                        1095.0,
                        1216.0,
                        1292.0,
                        1367.0,
                        1391.0,
                        1402.0,
                        np.nan,
                        np.nan,
                    ],
                    [
                        304.0,
                        681.0,
                        936.0,
                        1092.0,
                        1225.0,
                        1357.0,
                        1432.0,
                        1446.0,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        203.0,
                        607.0,
                        841.0,
                        1089.0,
                        1327.0,
                        1464.0,
                        1523.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        181.0,
                        614.0,
                        941.0,
                        1263.0,
                        1507.0,
                        1568.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        235.0,
                        848.0,
                        1442.0,
                        1852.0,
                        2029.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        295.0,
                        1119.0,
                        1664.0,
                        1946.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        307.0,
                        906.0,
                        1201.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        329.0,
                        791.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        276.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                ],
                [
                    [
                        np.nan,
                        np.nan,
                        np.nan,
                        634.0,
                        635.0,
                        635.0,
                        637.0,
                        637.0,
                        637.0,
                        637.0,
                        637.0,
                    ],
                    [
                        np.nan,
                        np.nan,
                        1026.0,
                        1039.0,
                        1047.0,
                        1050.0,
                        1053.0,
                        1047.0,
                        1047.0,
                        1047.0,
                        np.nan,
                    ],
                    [
                        np.nan,
                        1354.0,
                        1397.0,
                        1411.0,
                        1410.0,
                        1408.0,
                        1408.0,
                        1408.0,
                        1408.0,
                        np.nan,
                        np.nan,
                    ],
                    [
                        1305.0,
                        1421.0,
                        1449.0,
                        1458.0,
                        1458.0,
                        1455.0,
                        1455.0,
                        1455.0,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        1342.0,
                        1514.0,
                        1548.0,
                        1557.0,
                        1549.0,
                        1552.0,
                        1554.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        1373.0,
                        1616.0,
                        1630.0,
                        1626.0,
                        1629.0,
                        1629.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        1932.0,
                        2168.0,
                        2234.0,
                        2249.0,
                        2258.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        2067.0,
                        2293.0,
                        2367.0,
                        2390.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        1473.0,
                        1645.0,
                        1657.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        1192.0,
                        1264.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        1036.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                ],
                [
                    [
                        np.nan,
                        np.nan,
                        4861.0,
                        3859.0,
                        3134.0,
                        2447.0,
                        1446.0,
                        1947.0,
                        853.0,
                        71.0,
                        np.nan,
                    ],
                    [
                        np.nan,
                        8589.0,
                        6544.0,
                        5668.0,
                        4347.0,
                        1732.0,
                        1583.0,
                        649.0,
                        479.0,
                        290.0,
                        np.nan,
                    ],
                    [
                        14374.0,
                        12237.0,
                        9760.0,
                        9316.0,
                        5458.0,
                        5605.0,
                        3727.0,
                        1603.0,
                        465.0,
                        np.nan,
                        np.nan,
                    ],
                    [
                        10288.0,
                        10052.0,
                        8703.0,
                        7969.0,
                        9818.0,
                        6046.0,
                        1471.0,
                        278.0,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        10494.0,
                        12439.0,
                        12833.0,
                        15572.0,
                        12469.0,
                        8072.0,
                        3731.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        7908.0,
                        10755.0,
                        17671.0,
                        17702.0,
                        9726.0,
                        5052.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        14774.0,
                        30281.0,
                        32916.0,
                        28268.0,
                        17477.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        25631.0,
                        35213.0,
                        43268.0,
                        30629.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        23535.0,
                        35005.0,
                        25985.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        15948.0,
                        19867.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        15223.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                ],
                [
                    [
                        np.nan,
                        np.nan,
                        np.nan,
                        19526.0,
                        20813.0,
                        22152.0,
                        23058.0,
                        25692.0,
                        25374.0,
                        24859.0,
                        24839.0,
                    ],
                    [
                        np.nan,
                        np.nan,
                        15989.0,
                        18902.0,
                        21464.0,
                        22632.0,
                        23831.0,
                        23682.0,
                        23946.0,
                        23980.0,
                        np.nan,
                    ],
                    [
                        np.nan,
                        13847.0,
                        15676.0,
                        19237.0,
                        20914.0,
                        24473.0,
                        26242.0,
                        26637.0,
                        26453.0,
                        np.nan,
                        np.nan,
                    ],
                    [
                        9063.0,
                        11262.0,
                        14508.0,
                        18229.0,
                        23460.0,
                        25523.0,
                        26489.0,
                        26665.0,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        9546.0,
                        13455.0,
                        17219.0,
                        24192.0,
                        28673.0,
                        31379.0,
                        30997.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        7029.0,
                        10517.0,
                        18622.0,
                        24966.0,
                        27152.0,
                        27239.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        8796.0,
                        18533.0,
                        26350.0,
                        31884.0,
                        31129.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        13872.0,
                        20686.0,
                        29717.0,
                        29563.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        18375.0,
                        28440.0,
                        29453.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        16340.0,
                        25104.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        17985.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                ],
                [
                    [
                        20000.0,
                        20000.0,
                        20000.0,
                        20000.0,
                        20000.0,
                        20000.0,
                        20000.0,
                        20000.0,
                        20000.0,
                        20000.0,
                        20000.0,
                    ],
                    [
                        31500.0,
                        31500.0,
                        31500.0,
                        31500.0,
                        31500.0,
                        31500.0,
                        31500.0,
                        31500.0,
                        31500.0,
                        31500.0,
                        np.nan,
                    ],
                    [
                        45000.0,
                        45000.0,
                        45000.0,
                        45000.0,
                        45000.0,
                        45000.0,
                        45000.0,
                        45000.0,
                        45000.0,
                        np.nan,
                        np.nan,
                    ],
                    [
                        50000.0,
                        50000.0,
                        50000.0,
                        50000.0,
                        50000.0,
                        50000.0,
                        50000.0,
                        50000.0,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        61183.0,
                        61183.0,
                        61183.0,
                        61183.0,
                        61183.0,
                        61183.0,
                        61183.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        69175.0,
                        69175.0,
                        69175.0,
                        69175.0,
                        69175.0,
                        69175.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        99322.0,
                        99322.0,
                        99322.0,
                        99322.0,
                        99322.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        138151.0,
                        138151.0,
                        138151.0,
                        138151.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        107578.0,
                        107578.0,
                        107578.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        62438.0,
                        62438.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                    [
                        47797.0,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                        np.nan,
                    ],
                ],
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)
friedland_xyz_auto_bi["Reported Claims"].latest_diagonal
assert np.allclose(
    (friedland_xyz_auto_bi["Reported Claims"].latest_diagonal).values,
    np.array(
        [
            [
                [
                    [15822.0],
                    [25107.0],
                    [37246.0],
                    [38798.0],
                    [48169.0],
                    [44373.0],
                    [70288.0],
                    [70655.0],
                    [48804.0],
                    [31732.0],
                    [18632.0],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

In [ ]:
# Page 144, Exhibit III Sheet 1, column 3
friedland_xyz_auto_bi["Paid Claims"].latest_diagonal
assert np.allclose(
    (friedland_xyz_auto_bi["Paid Claims"].latest_diagonal).values,
    np.array(
        [
            [
                [
                    [15822.0],
                    [24817.0],
                    [36782.0],
                    [38519.0],
                    [44437.0],
                    [39320.0],
                    [52811.0],
                    [40026.0],
                    [22819.0],
                    [11865.0],
                    [3409.0],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

In [ ]:
# Page 144, Exhibit III Sheet 1, columns 4-5
# Developed in Chapter 7, Exhibit II, Sheets 1 and 2
reported_pattern = {
    12: 2.551,
    24: 1.512,
    36: 1.196,
    48: 1.085,
    60: 1.064,
    72: 1.013,
    84: 1.003,
    96: 0.992,
    108: 0.992,
    120: 0.999,
    132: 1.000,
}
assert reported_pattern == {
    12: 2.551,
    24: 1.512,
    36: 1.196,
    48: 1.085,
    60: 1.064,
    72: 1.013,
    84: 1.003,
    96: 0.992,
    108: 0.992,
    120: 0.999,
    132: 1.0,
}
paid_pattern = {
    12: 21.999,
    24: 6.569,
    36: 3.160,
    48: 2.007,
    60: 1.525,
    72: 1.268,
    84: 1.116,
    96: 1.054,
    108: 1.031,
    120: 1.014,
    132: 1.010,
}
assert paid_pattern == {
    12: 21.999,
    24: 6.569,
    36: 3.16,
    48: 2.007,
    60: 1.525,
    72: 1.268,
    84: 1.116,
    96: 1.054,
    108: 1.031,
    120: 1.014,
    132: 1.01,
}

In [ ]:
# Page 144, Exhibit III Sheet 1, column 6
reported_ultimate = (
    cl.Chainladder()
    .fit(
        cl.DevelopmentConstant(patterns=reported_pattern, style="cdf").fit_transform(
            friedland_xyz_auto_bi["Reported Claims"]
        )
    )
    .ultimate_
)
assert np.allclose(
    reported_ultimate.values,
    np.array(
        [
            [
                [
                    [15822.0],
                    [25081.893],
                    [36948.032],
                    [38487.616],
                    [48313.507],
                    [44949.848999999995],
                    [74786.43199999999],
                    [76660.67499999999],
                    [58369.58399999999],
                    [47978.78399999999],
                    [47530.231999999996],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)
reported_ultimate
assert np.allclose(
    (reported_ultimate).values,
    np.array(
        [
            [
                [
                    [15822.0],
                    [25081.893],
                    [36948.032],
                    [38487.616],
                    [48313.507],
                    [44949.848999999995],
                    [74786.43199999999],
                    [76660.67499999999],
                    [58369.58399999999],
                    [47978.78399999999],
                    [47530.231999999996],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

In [ ]:
# Page 144, Exhibit III Sheet 1, column 7
paid_ultimate = (
    cl.Chainladder()
    .fit(
        cl.DevelopmentConstant(patterns=paid_pattern, style="cdf").fit_transform(
            friedland_xyz_auto_bi["Paid Claims"]
        )
    )
    .ultimate_
)
assert np.allclose(
    paid_ultimate.values,
    np.array(
        [
            [
                [
                    [15980.22],
                    [25164.438000000002],
                    [37922.242],
                    [40599.026000000005],
                    [49591.692],
                    [49857.76],
                    [80536.775],
                    [80332.182],
                    [72108.04000000001],
                    [77941.185],
                    [74994.591],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)
paid_ultimate
assert np.allclose(
    (paid_ultimate).values,
    np.array(
        [
            [
                [
                    [15980.22],
                    [25164.438000000002],
                    [37922.242],
                    [40599.026000000005],
                    [49591.692],
                    [49857.76],
                    [80536.775],
                    [80332.182],
                    [72108.04000000001],
                    [77941.185],
                    [74994.591],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

In [ ]:
# Page 144, Exhibit III Sheet 1, column 8
selected_ultimate = (reported_ultimate + paid_ultimate) / 2
assert np.allclose(
    selected_ultimate.values,
    np.array(
        [
            [
                [
                    [15901.11],
                    [25123.165500000003],
                    [37435.137],
                    [39543.321],
                    [48952.5995],
                    [47403.8045],
                    [77661.6035],
                    [78496.4285],
                    [65238.812],
                    [62959.98449999999],
                    [61262.4115],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)
selected_ultimate
assert np.allclose(
    (selected_ultimate).values,
    np.array(
        [
            [
                [
                    [15901.11],
                    [25123.165500000003],
                    [37435.137],
                    [39543.321],
                    [48952.5995],
                    [47403.8045],
                    [77661.6035],
                    [78496.4285],
                    [65238.812],
                    [62959.98449999999],
                    [61262.4115],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

In [ ]:
# Page 144, Exhibit III Sheet 1, column 9
earned_premium = friedland_xyz_auto_bi["Earned Premium"].latest_diagonal
assert np.allclose(
    earned_premium.values,
    np.array(
        [
            [
                [
                    [20000.0],
                    [31500.0],
                    [45000.0],
                    [50000.0],
                    [61183.0],
                    [69175.0],
                    [99322.0],
                    [138151.0],
                    [107578.0],
                    [62438.0],
                    [47797.0],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)
earned_premium
assert np.allclose(
    (earned_premium).values,
    np.array(
        [
            [
                [
                    [20000.0],
                    [31500.0],
                    [45000.0],
                    [50000.0],
                    [61183.0],
                    [69175.0],
                    [99322.0],
                    [138151.0],
                    [107578.0],
                    [62438.0],
                    [47797.0],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

In [ ]:
# Page 144, Exhibit III Sheet 1, column 10
np.round(selected_ultimate / earned_premium, 3)
assert np.allclose(
    (np.round(selected_ultimate / earned_premium, 3)).values,
    np.array(
        [
            [
                [
                    [0.795],
                    [0.798],
                    [0.832],
                    [0.791],
                    [0.8],
                    [0.685],
                    [0.782],
                    [0.568],
                    [0.606],
                    [1.008],
                    [1.282],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)

In [ ]:
# Page 144, Exhibit III Sheet 1, column 11
# Selected for 1998-2003 based on average of estimated claim ratios in column 10; 2004-2008 selected in Exhibit III, Sheet 2
selected_claim_ratio = [
    0.783,
    0.783,
    0.783,
    0.783,
    0.783,
    0.783,
    0.871,
    0.783,
    0.658,
    0.638,
    0.825,
]
assert selected_claim_ratio == [
    0.783,
    0.783,
    0.783,
    0.783,
    0.783,
    0.783,
    0.871,
    0.783,
    0.658,
    0.638,
    0.825,
]
selected_claim_ratio
assert selected_claim_ratio == [
    0.783,
    0.783,
    0.783,
    0.783,
    0.783,
    0.783,
    0.871,
    0.783,
    0.658,
    0.638,
    0.825,
]

In [ ]:
# Page 144, Exhibit III Sheet 1, column 12
expected_claims = earned_premium * np.array(selected_claim_ratio).reshape(1, 1, -1, 1)
assert np.allclose(
    expected_claims.values,
    np.array(
        [
            [
                [
                    [15660.0],
                    [24664.5],
                    [35235.0],
                    [39150.0],
                    [47906.289000000004],
                    [54164.025],
                    [86509.462],
                    [108172.23300000001],
                    [70786.32400000001],
                    [39835.444],
                    [39432.525],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)
expected_claims
assert np.allclose(
    (expected_claims).values,
    np.array(
        [
            [
                [
                    [15660.0],
                    [24664.5],
                    [35235.0],
                    [39150.0],
                    [47906.289000000004],
                    [54164.025],
                    [86509.462],
                    [108172.23300000001],
                    [70786.32400000001],
                    [39835.444],
                    [39432.525],
                ]
            ]
        ]
    ),
    rtol=1e-6,
    equal_nan=True,
)