In [1]:
import pandas as pd
import chainladder as cl
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

auto_bi = cl.load_sample('friedland_auto_bi_insurer')

In [2]:
# Page 140, Exhibit I Sheet 1Column 1-2
auto_bi = cl.load_sample("friedland_auto_bi_insurer")
auto_bi["Reported Claims"].latest_diagonal

            2008
2000  10000000.0
2001   8000000.0
2002   9400000.0
2003  15600000.0
2004  16500000.0
2005  18500000.0
2006  16500000.0
2007  14000000.0
2008   8700000.0

In [3]:
# Page 140, Exhibit I Sheet 1 Column 3
auto_bi["Paid Claims"].latest_diagonal

            2008
2000   9500000.0
2001   7200000.0
2002   7600000.0
2003   7800000.0
2004  11200000.0
2005  10200000.0
2006   6000000.0
2007   3000000.0
2008    750000.0

In [4]:
# Page 140, Exhibit I Sheet 1 Columns 4-5
# Direct age(in months): value representation per LOB
reported_pattern = {12: 4.0, 24: 2.9, 36: 1.8, 48: 1.4, 60: 1.2, 72: 1.1, 84: 1.03, 96: 1.02, 108: 1.005}
paid_pattern = {12: 90.0, 24: 15.0, 36: 5.0, 48: 2.5, 60: 1.75, 72: 1.35, 84: 1.25, 96: 1.15, 108: 1.05}

In [5]:
# Page 140, Exhibit I Sheet 1 Column 6
Reported_BI = cl.DevelopmentConstant(patterns=reported_pattern, style='cdf').fit_transform(auto_bi["Reported Claims"])
reported_ultimate = cl.Chainladder().fit(Reported_BI).ultimate_
reported_ultimate

            2261
2000  10050000.0
2001   8160000.0
2002   9682000.0
2003  17160000.0
2004  19800000.0
2005  25900000.0
2006  29700000.0
2007  40600000.0
2008  34800000.0

In [6]:
# Page 140, Exhibit I Sheet 1 Column 7
Paid_BI = cl.DevelopmentConstant(patterns=paid_pattern, style='cdf').fit_transform(auto_bi["Paid Claims"])
paid_ultimate = cl.Chainladder().fit(Paid_BI).ultimate_
paid_ultimate

            2261
2000   9975000.0
2001   8280000.0
2002   9500000.0
2003  10530000.0
2004  19600000.0
2005  25500000.0
2006  30000000.0
2007  45000000.0
2008  67500000.0

In [7]:
# Page 140, Exhibit I Sheet 1 Column 8
inital_selected_ultiamte_claims = (reported_ultimate + paid_ultimate)/2
inital_selected_ultiamte_claims

            2261
2000  10012500.0
2001   8220000.0
2002   9591000.0
2003  13845000.0
2004  19700000.0
2005  25700000.0
2006  29850000.0
2007  42800000.0
2008  51150000.0

In [8]:
# Page 140, Exhibit I Sheet 1 Column 9
auto_bi["Earned Premium"].latest_diagonal

            2008
2000  24000000.0
2001  18000000.0
2002  19000000.0
2003  23000000.0
2004  32000000.0
2005  47000000.0
2006  50000000.0
2007  57000000.0
2008  62000000.0

In [9]:
# Page 140, Exhibit I Sheet 1 Column 10
trend_factors = np.round(cl.Trend(trends=[0.145], dates=[("2008-12-31", "2000-01-01")]).fit(auto_bi["Earned Premium"]).trend_.latest_diagonal,3)
trend_factors

       2008
2000  2.954
2001  2.580
2002  2.253
2003  1.968
2004  1.719
2005  1.501
2006  1.311
2007  1.145
2008  1.000

In [10]:
# Page 140, Exhibit I Sheet 1 Column 11
tort_factors = [0.670, 0.670, 0.670, 0.670, 0.750, 1.0, 1.0, 1.0, 1.0]
tort_factors

[0.67, 0.67, 0.67, 0.67, 0.75, 1.0, 1.0, 1.0, 1.0]

In [11]:
# Page 140, Exhibit I Sheet 1 Column 12
trended_adj_ultimate_claims = trend_factors * inital_selected_ultiamte_claims * np.array(tort_factors).reshape(1, 1, -1, 1)
trended_adj_ultimate_claims

             2008
2000  19816539.75
2001  14209092.00
2002  14477710.41
2003  18255463.20
2004  25398225.00
2005  38575700.00
2006  39133350.00
2007  49006000.00
2008  51150000.00

In [12]:
# Page 140, Exhibit I Sheet 1 Column 13
trended_adjusted_claim_ratio = np.round(trended_adj_ultimate_claims/auto_bi["Earned Premium"].latest_diagonal,2)
trended_adjusted_claim_ratio

      2008
2000  0.83
2001  0.79
2002  0.76
2003  0.79
2004  0.79
2005  0.82
2006  0.78
2007  0.86
2008  0.82

In [13]:
# Page 140, Exhibit I Sheet 1 Item 14
print("Average 2000 to 2005:", np.round(trended_adjusted_claim_ratio.iloc[:, :, 0:6, :].mean(),3))
loss_ratios_00_05 = trended_adjusted_claim_ratio.iloc[:, :, 0:6, :].values.flatten()
print("Average 2000 to 2005 Ex High Ex Low:", np.round((loss_ratios_00_05.sum() - loss_ratios_00_05.max() - loss_ratios_00_05.min()) / (len(loss_ratios_00_05) - 2), 3))
print("Average 2001 to 2006:", np.round(trended_adjusted_claim_ratio.iloc[:, :, 1:7, :].mean(),3))
loss_ratios_01_06 = trended_adjusted_claim_ratio.iloc[:, :, 1:7, :].values.flatten()
print("Average 2000 to 2005 Ex High Ex Low:", np.round((loss_ratios_01_06.sum() - loss_ratios_01_06.max() - loss_ratios_01_06.min()) / (len(loss_ratios_01_06) - 2), 3)) # small rounding error due to python's 64 bit float storage

Average 2000 to 2005: 0.797
Average 2000 to 2005 Ex High Ex Low: 0.798
Average 2001 to 2006: 0.788
Average 2000 to 2005 Ex High Ex Low: 0.787

In [14]:
# Page 140, Exhibit I Item 15
selected_claim_ratio = 0.80
selected_claim_ratio

0.8

In [15]:
# Page 140, Exhibit I Item 16
exlected_claims_2008 = auto_bi["Earned Premium"].loc[:, :, "2008", :].latest_diagonal * selected_claim_ratio
exlected_claims_2008

np.float64(49600000.0)

In [16]:
# Page 140, Exhibit I Item 17
print("Total Unpaid Claims:", exlected_claims_2008 - auto_bi["Paid Claims"].loc[:, :, "2008", :].latest_diagonal)
print("Total IBNR:", exlected_claims_2008 - auto_bi["Reported Claims"].loc[:, :, "2008", :].latest_diagonal)

Total Unpaid Claims: 48850000.0
Total IBNR: 40900000.0

In [ ]:
# Page 141, Exhibit I Sheet 2

In [ ]:
# Page 142, Exhibit II Sheet 1, columns 1-2
friedland_us_industry_auto = cl.load_sample("friedland_us_industry_auto")
friedland_us_industry_auto["Reported Claims"].latest_diagonal

            2007
1998  47742304.0
1999  51185767.0
2000  54837929.0
2001  56299562.0
2002  58592712.0
2003  57565344.0
2004  56976657.0
2005  56786410.0
2006  54641339.0
2007  48853563.0

In [ ]:
# Page 142, Exhibit II Sheet 1, columns 3
friedland_us_industry_auto["Paid Claims"].latest_diagonal

            2007
1998  47644187.0
1999  51000534.0
2000  54533225.0
2001  55878421.0
2002  57807215.0
2003  55930654.0
2004  53774672.0
2005  50644994.0
2006  43606497.0
2007  27229969.0

In [ ]:
# Page 142, Exhibit II Sheet 1, columns 4-5
# Direct age(in months): value representation per LOB
reported_pattern = {12: 1.292, 24: 1.110, 36: 1.051, 48: 1.023, 60: 1.011, 72: 1.006, 84: 1.003, 96: 1.001, 108: 1.000, 120: 1.000}
paid_pattern = {12: 2.390, 24: 1.404, 36: 1.184, 48: 1.085, 60: 1.040, 72: 1.020, 84: 1.011, 96: 1.006, 108: 1.004, 120: 1.002}